### ISSUE TITLE
[FEATURE] - Map Improvement

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#101]
**Is your feature request related to a problem? Please describe.**
It's frustrating to zoom out all the time on the map to see if anyone might be flying.

**Describe the solution you'd like**
Have the map start out further zoomed and let people hone in on the zone they wish to see.

**Describe alternatives you've considered**
N/A

**Additional context**
Starting out
![image](https://user-images.githubusercontent.com/127605985/232249884-da858e18-6b6a-48b2-9725-c24c7be3820b.png)

Ideal
![image](https://user-images.githubusercontent.com/127605985/232249888-25003540-c9d1-4c94-be64-96d0c98e6344.png)

**Comment by turbofandude** [comment]
Will be adjusted accordingly in the next update.
