### ISSUE TITLE
[FEATURE] - PIREP submission UX

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#104]
**Is your feature request related to a problem? Please describe.**
Sometimes a pilot may experience an error while filing a PIREP (example below). 
![image](https://user-images.githubusercontent.com/67948773/232262356-d7b34c8b-8937-4438-b22c-48b940e9f49a.png)
This could be due to a range of factors that are probably outside the scope of smartCARS however once you file a flight in the current version of smartCARS it just exits the page and all that data associated with the flight is lost (I assume). 

In smartCARS 2, if there was a failed response from the VA servers, you got a dialog advising of the failure and to check the VA servers before clicking cancel. 

**Describe the solution you'd like**
Something similar to SC2 implemented in SC3

**Describe alternatives you've considered**
Another option could be to log the current flight to a txt file and in the event a submission fails, the pilot could still send that file to VA administrators

**Additional context**
This could also be a good idea for a custom plugin (which I'm happy to make if I can get my hands on some docs 🙏)

**Comment by walkerairtrans** [comment]
Honestly -- If possible I would like to see a "submitting PIREP" waiting message (clock icon) something. Just so the user knows that when they hit the "END FLIGHT" it is going through. You hit it and then you wait for the green -- some users don't have fast connections across the water and they can sometimes have higher latency which results in couple more seconds before they would see the green toast.

I think the toast is perfect! Just maybe also add a "Standby, Submitting your flight to the server..."
