### ISSUE TITLE
[FEATURE] - Allow PIREP submission if the simulator is closed and flight status reached DEBOARDING

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#107]
**Is your feature request related to a problem? Please describe.**
Pretty much title. We should consider allowing the users submitting a PIREP even if the sim is disconnected, but only if the status has reached DEBOARDING

**Comment by bgiorgio0506** [comment]
handle the CONN_LOSS state  on deboarding
