### ISSUE TITLE
[BUG] - Report shows "bank exceeded 30 degrees" erroneously

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#108]
**Describe the bug**
I quite often get a warning that the bank exceeded 30 degrees when I believe it has not.

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: 1
 - Version: 0.7.0
 - Plugins used: flight-tracking

**Additional context**
Was using the Aerosoft CRJ-700 in MSFS

**Comment by turbofandude** [comment]
Found and fixed in f7018d45ad0295e687e0813ea9efe4ea45bcc67f

**Comment by turbofandude** [comment]
Fixed by f7018d4
