### ISSUE TITLE
[BUG] - Route box not populated when route exists in schedule

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#109]
**Describe the bug**
The route box is not being populated with the route pulled during booking search.

**To Reproduce**
1. Bid on a flight that has a predefined route included.
2. Click on flight to expose the route box

**Expected behavior**
Route box should autopopulate with the route provided with the bid.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/232319756-e77a6181-9add-403c-893f-082b2eda4d0c.png)

![image](https://user-images.githubusercontent.com/127605985/232319770-dfb1516a-8ef4-4f16-87c8-d5afee07dd35.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version: Latest
 - Plugins used: Flight Tracking, Flight Center

**Additional context**
N/A

**Comment by GenericNerd** [comment]
We provide `route` on /flight/search, we should aim to use that if it's available

**Comment by walkerairtrans** [comment]
This is what I think of as to who holds the truth on the route and sends it with the PIREP.

1. Route box (user always has control over it, otherwise remove it completely.)
2. simBrief if the pilot uses the built in plugin
3. Flight schedule route if the other 2 are unavailable (you already get the route.)

The issues here is that the route box is available to the user. You use the data in that box right now for the update (I see whatever I type in there come across my server.) You just don't carry it to the PIREP.

Hope that helps. :)

**Comment by turbofandude** [comment]
Found and fixed - thank you!
