### ISSUE TITLE
[FEATURE] - Absolute `Web Script URL` toggle

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#11]
**Is your feature request related to a problem? Please describe.**
It looks like the `Web script URL` within the SC3 Central auto appends `/` which doesn't work for our specific use case.

**Describe the solution you'd like**
Have an `Absolute path` toggle that when checked, will not automatically append the `/` and instead just use the path as entered

**Describe alternatives you've considered**
None that align with our configuration

**Additional context**
We're using Laravel under the hood so having a trailing slash will always throw a 301 for us.
The below error is what we receive when trying to update our Web script URL
![image](https://user-images.githubusercontent.com/67948773/224770841-23400659-ae71-48f8-aec2-9d7c212e3594.png)

**Comment by turbofandude** [comment]
We will adjust the validator to remove the trailing slash before using the URL. The actual URL served to the client will still contain the trailing /, but this shouldn't matter as it'll also have an actual endpoint.
