### ISSUE TITLE
[BUG] - Log Book Missing Information

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#110]
**Describe the bug**
There is missing information in the log book; I'm not sure if this is still WIP, but wanted to note it.

**To Reproduce**
1. Open logbook
2. Open PIREP

**Expected behavior**
See screenshots.
Log Book is missing Aircraft name (it's blank.)
Open any flight and the aircraft ID is being shown in the top right instead of the name of the aircraft

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/232320261-789b4135-49bd-4e60-afe4-35027952225d.png)

![image](https://user-images.githubusercontent.com/127605985/232320268-3af213be-804c-413a-a25e-d8ad302cdce4.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version: Latest
 - Plugins used: Flight Tracking, Flight Center, Logbook

**Additional context**
N/A

**Comment by turbofandude** [comment]
You are correct, it was missing. I've fixed this for the next update.
