### ISSUE TITLE
[FEATURE] - Show data in the user's preferred unit across the app

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#112]
**Describe the bug**
Currently the fuel usage in the logbook is only in lbs. We should show it in kgs if that is the unit the user set in their settings. This also applies to the log in the flight-tracking.

**Comment by turbofandude** [comment]
This will require us to build an SDK library specifically for conversion to/from user-specified units. This is so we can allow third party plugins to easily and natively support this as well.

**Comment by Thien42** [comment]
We could also only make the conversion in the UI if that makes more sense

**Comment by Thien42** [comment]
Will be implemented in the next release
