### ISSUE TITLE
[BUG] - Opening links from the home section causes smartCARS to be a perpetual web browser

### ISSUE THREAD

**Issue by arwasairl** [invernyx/smartcars-3-bugs#114]
**Describe the bug**
When opening any links on the home section of smartCARS (such as the bug report link) the entire link fills up the smartCARS window and has no window buttons. It now requires the program to be completely closed and reopened to get out of the browser.

**To Reproduce**
1. Login to VA
2. Click on any links on the home page of smartCARS
3. Observe how smartCARS becomes a perpetual web browser

**Expected behavior**
A new window is supposed to open OR is supposed to open whatever web browser is set as default in the client's computer 

**Screenshots**
![image](https://user-images.githubusercontent.com/48654776/233230070-1af730d1-85f2-4824-ad01-9c6631b34714.png)

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: [e.g. 2/any]
 - Version: 0.8.0.0
 - Plugins used: chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center

**Additional context**
N/A

**Comment by BossOfGames** [comment]
I can verify that I have encountered the same issue.

**Comment by Thien42** [comment]
Will be fixed in the next update
