### ISSUE TITLE
[BUG] - Cannot Submit PIREP Due To TFDi Credentials

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#115]
**Describe the bug**
Upon completing and submitting a flight. I encounter an error. When looking at the log, it appears that there's an issue with trying to retrieve TFDi Credentials.

**To Reproduce**
1. Login via TFDi Account.
2. Login to VA using VA Account
3. Complete a flight
4. Throws Error upon attempting to submit.

**Expected behavior**
I expected the flight to be submitted without error.

**Screenshots**
(error: Failed to call local API {"endpoint":"api/credentials/retrieve/tfdidesign","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://localhost:7172/api/credentials/retrieve/tfdidesign","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at http://localhost:7172/app/static/js/main.e24693b7.js:2:344427\n    at XMLHttpRequest.d (http://localhost:7172/app/static/js/main.e24693b7.js:2:344575)","status":404}})

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: smartCARS Development Center
 - Version: No version information available
 - Plugins used: flight-tracking

**Additional context**
N/A

**Comment by bgiorgio0506** [comment]
@BossOfGames Can you please provide your combined.log? This can be found at %localappdata%\TFDi Design\smartCARS\logs?
