### ISSUE TITLE
[FEATURE] - Dark Mode Icons for Plugin Developers

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#116]
**Is your feature request related to a problem? Please describe.**
When Using Light or Dark Mode, some plugin icons may not display properly.

**Describe the solution you'd like**
3rd party plugin developers should have the option to upload a “light mode” and “dark mode” version of their icon. For example, light mode could have a color icon, while dark mode would have a white icon. This will avoid situations like below, where the SimBrief logo is just a color inversion.

![image](https://user-images.githubusercontent.com/2882332/233293385-df39648b-847c-4912-988f-bc363afa6030.png)

**Additional context**
Do something like this. The UI would pull the dark icon when in dark mode.
![image](https://user-images.githubusercontent.com/2882332/233293706-1cc41b89-ee53-40d7-b195-a1cb53639944.png)

**Comment by turbofandude** [comment]
This will be mitigated by our upcoming UI/icon consistency pass. Thank you for the report!

**Comment by turbofandude** [comment]
Added as of 0.9.
