### ISSUE TITLE
[BUG] - Delete message icon for moderators extends outside the chat window

### ISSUE THREAD

**Issue by JoshRiley** [invernyx/smartcars-3-bugs#117]
**Describe the bug**
For moderators, the delete message icon in the application window extends outside of the area for the chat messages, appearing underneath the smartCARS logo.

**To Reproduce**
1. Go to the chat plugin (as an admin/mod)
2. Scroll the chat window and look around the smartCARS logo

**Expected behavior**
Icons to stop at the point of the horizontal line and not appear outside that area.

**Screenshots**
https://cdn.joshriley.dev/img/o9TlNvUMVS.jpg

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11 22H2] Windows 11 22621
 - Community ID: any
 - Version [e.g. 0.1.0]: 0.7 beta 
 - Plugins used: chat

**Comment by turbofandude** [comment]
This is **technically** still a bug, but the new UX for it avoids it.
