### ISSUE TITLE
[BUG] - Flight can be started for a bid that was deleted

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#119]
**Describe the bug**
If you sit at the Flight Center page, and then go to your VA and delete the bid, then go back to ACARS and hit the fly button. It will take you to the flight tracking page and act like it's logging even though the bid no longer exists.

**To Reproduce**
1. Bid a flight
2. Go to flight center
3. Go back to website and delete your bid (not through the ACARS)
4. Go back to ACARS (you are on the flight center already and the old bid is visible) and click fly
5. It says the flight is now started and shows flight tracking

**Expected behavior**
In the early alpha tests we had this would not happen. It would error out with a red toast and keep you on the flight center. I hadn't tested this in awhile until just now and it's not doing what it should before.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/233504308-6bc18570-6cac-4f32-a443-e62018f7a5ef.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version: Latest
 - Plugins used: Flight Tracking, Flight Center

**Additional context**
N/A

**Comment by jordanhavard** [comment]
This is also an issue for QV too occasionally. The work around is heavy communication to pilots about ensuring to click `refresh` before starting any flights. It would be a cool feature if SC3 could do a check with the bidId to ensure its still valid (active/not deleted) before allowing a flight to start.

**Comment by walkerairtrans** [comment]
> 

I'm pretty sure it was doing this early on--I remember specifically checking this when we first got access and it did not work.

This exists in update.php
```
if($flightDetails === array())
{
    error(404, 'There is no flight with the specified bid ID');
}
```

However it doesn't actually error out the app -- the app just stays stuck in flight tracking and it sends blank data feeds to server.

**Comment by walkerairtrans** [comment]
This is still an issue.
I deleted the bid from my website and then hit Fly!

It immediately started the flight tracking, gave me a green toast saying flight started, but is not sending data to server (which is good.)

But, it shouldn't be on this screen. It should have errored out and told the pilot there was a problem with the bid (it doesn't exist) and refresh the bid screen.

![image](https://user-images.githubusercontent.com/127605985/235318544-6f0c4dee-a91d-400d-81ea-f753ea474d50.png)
