### ISSUE TITLE
[BUG] - We could not file your flight due to an error

### ISSUE THREAD

**Issue by Viralwhite** [invernyx/smartcars-3-bugs#121]
**Describe the bug**
Completed my flight and went to submit the issue when I received an error stating, "We could not file your flight due to an error. Further information can be found in your log". This was using MSFS.

**To Reproduce**
Completed a flight from BOI-SEA using the PMDG 737-7 (BCF) and when I went to submit the flight I received this message.

**Expected behavior**
When clicking end flight, I would assume the flight should be submitted for review by the VA.

**Screenshots**
![image](https://user-images.githubusercontent.com/87394476/233510089-ade59ddc-389c-4778-b5b7-a4e50eb81007.png)

**System Information (please complete the following information):**
 - OS: W10 19045
 - Version Latest
 - Plugins used: Flight tracking and flight center

**Additional context**
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11291175/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11291176/error.log)

**Comment by BossOfGames** [comment]
Were you signed into a TFDi Account when using smartCARS? This could be a very similar issue to #115

**Comment by CaptainMac2336** [comment]
I have run into this same issue. 
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11297591/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11297592/error.log)

**Comment by AirmanMD** [comment]
Hey I am from Millennium Aviation, SmartCARS3 is running with no issues or error messages for me, but when is hit the finish button after completing my flight it tells my that my flight was saved and filed to the airline. When I got check my logbook and the airline website the flight I just flew was not saved or filed with no error messages.

**Comment by Viralwhite** [comment]
> Were you signed into a TFDi Account when using smartCARS? This could be a very similar issue to #115

I was logged in, yes.

**Comment by BossOfGames** [comment]
> > Were you signed into a TFDi Account when using smartCARS? This could be a very similar issue to #115
> 
> I was logged in, yes.

Logout of the TFDi account, then login to your VA normally (skip logging into your TFDi account), complete a quick flight, and report back if that solves your issue.

I have a feeling this is directly related to being logged into the TFDi Account when using smartCARS.

**Comment by Ravenshammer** [comment]
Had the same issue with not being able to file the PIREP due to error.
[Log.txt](https://github.com/invernyx/smartcars-3-bugs/files/11299638/Log.txt)

**Comment by Ravenshammer** [comment]
Another "We could not file your flight due to an error. Further information can be found in your log."
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11302708/error.log)
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11302710/combined.log)

I was not logged into the TFDi account.

**Comment by GenericNerd** [comment]
It seems that aircraft is being sent as null, which isn't valid.

**Comment by Ravenshammer** [comment]
Hello, another error filing a flight!
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11402322/error.log)
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11402323/combined.log)

**Comment by Ravenshammer** [comment]
Error filing the flight, saying it could not file it, however, the flight was filed with my VA.  For your perusal.
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11402326/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11402327/error.log)
