### ISSUE TITLE
[BUG] - Too Many Airports Returned To Custom Select, Causing a UI Overflow

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#122]
**Describe the bug**
The list returned with the custom select for airports extends well beyond the bounds of the window when a large list of airports is returned.

**To Reproduce**
1. Go to Flights Center
2. Click on Departure Airport
3. Type in any character 

**Expected behavior**
Only return a small list of airports, or, if the list overflows to the bottom, allow scrolling. Just like the Aircraft <select>.

**Screenshots**

![image](https://user-images.githubusercontent.com/2882332/233517327-b41a4c83-0a0c-4a0e-aac8-2954eab04b5d.png)

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: ANY
 - Version 0.8.0
 - Plugins used: flight-center

**Additional context**
I've also noticed that sometimes the input dropdown will shoot all the way to the right of the screen. Only a full restart of the app fixes this problem:

![image](https://user-images.githubusercontent.com/2882332/233517525-9fa8a489-0fc7-4cfc-9d8d-df1bb458bc0d.png)

**Comment by BossOfGames** [comment]
It appears when posting this, GitHub didn't like me.

Posting Screenshots here:

Overflow Situation:

![image](https://user-images.githubusercontent.com/2882332/233518285-7ebd08a7-2527-462b-bf95-12d3cf46f1b1.png)

List all the way in right field:

![image](https://user-images.githubusercontent.com/2882332/233518320-789e1804-724d-4681-8bbb-a5b507bf907d.png)

**Comment by Thien42** [comment]
Will be solved in the next release
