### ISSUE TITLE
[FEATURE] - SC3 Central to follow redirects for script URL

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#127]
### Is your feature request related to a problem? Please describe.

Some VAs have redirects in place and are not able to avoid a 301 redirect. 

### Describe the solution you'd like

If possible, have SC3 Central follow redirects and if the final destination is not a `200` then throw an error

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ChrisAHD** [comment]
I am getting this error thrown back when I try to link the website to smartCARS 3

PHP Fatal error:  require_once(): Failed opening required '0.3.1/handlers/phpvms5/environment.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/virtualowa/public_html/smartcars/api.php on line 171

**Comment by GenericNerd** [comment]
> I am getting this error thrown back when I try to link the website to smartCARS 3
> 
> PHP Fatal error: require_once(): Failed opening required '0.3.1/handlers/phpvms5/environment.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/virtualowa/public_html/smartcars/api.php on line 171

This is not relevant to this issue and suggests an error with your API installation

**Comment by turbofandude** [comment]
POST data is not forwarded during a redirect, meaning a redirect on your API will break smartCARS (and anything else that depends on it). This one, unfortunately, is not fixable right now.

**Comment by jordanhavard** [comment]
Definitely, I more so mean just follow redirects for the verification of the script when inserting into central. 

While I know this specific use case has been addressed, if entering /smartcars/ throws a 301 but a 200 for /smartcars the end result will be used so when the app connects it will connect to /smartcars and thus be a 200
