### ISSUE TITLE
[FEATURE] - Recheck for simulator connection

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#128]
### Is your feature request related to a problem? Please describe.

If a user is to start a flight before a connection has been established, you receive the below error
![image](https://user-images.githubusercontent.com/67948773/233654822-88cf9deb-a3e5-4d8f-98cf-ecae7fab78be.png)
When the user then starts their sim, this screen still remains.

### Describe the solution you'd like

SC3 should automatically recheck for a connection after a certain interval and if one if established, commence tracking automatically

### Describe alternatives you've considered

Restarting SC3

### Additional context

-

**Comment by jordanhavard** [comment]
You could argue this is a bug however I'm not sure this functionality was ever there so I would consider it a feature

**Comment by turbofandude** [comment]
We will handle this by adding a "Retry" button to that page.
