### ISSUE TITLE
[BUG] - Background Processes Running

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#132]
### Describe the bug

See the screenshot.

Just submitted a flight and checked inspector--nothing was running so unsure why this fired off?

Is it because I still have my simulator open?

### How do you reproduce this bug?

I don't know how I did this--first time I've ever seen the error.

### Expected behavior

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/233736956-13059755-2c99-4d4a-a911-9328612b65d6.png)

### Operating system

Windows 11

### Community airline

Walker Air Treansport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
In this case, it is referring to the flight. Did you just submit and then try to close?

**Comment by walkerairtrans** [comment]
> 

No, I had already submitted and received the confirmation. I was on my side reviewing the PIREP (which was already automatically processed and approved) for a few minutes and checking data. I showed my staff a couple things in the ACARS and then went to close so I could go to dinner.

It was at least 5 minutes or so from when I submitted to when I was ready to close it.

**Comment by walkerairtrans** [comment]
I left the app open for 3 hours after I submitted my flight. Got this notice.

![image](https://user-images.githubusercontent.com/127605985/233812313-f8abf80d-ee6d-423b-b94a-8a28c367ca82.png)

**Comment by GenericNerd** [comment]
We may have resolved this issue. Can you try again and see if this still happens in the newest update? (Will be out in the next couple of minutes)

**Comment by walkerairtrans** [comment]
> We may have resolved this issue. Can you try again and see if this still happens in the newest update? (Will be out in the next couple of minutes)

Just did a flight and it was able to close after completion--did not give me the error this time.

**Comment by turbofandude** [comment]
Please re-open if it reoccurs.

**Comment by walkerairtrans** [comment]
This is back again.
Anything I can check? I did get some weird error filing my PIREP that it couldn't file on the TFDi server?

![image](https://user-images.githubusercontent.com/127605985/236081287-83049c8d-9af0-4257-a74e-86ad707f579c.png)
