### ISSUE TITLE
[BUG] - Full flight not being tracked

### ISSUE THREAD

**Issue by Expressjetxe** [invernyx/smartcars-3-bugs#133]
### Describe the bug

Sc3 only logged 2 min of the 2 1/2 hr flight

### How do you reproduce this bug?

Happened during flight

### Screenshots

![IMG_0104](https://user-images.githubusercontent.com/131483820/233746489-466cd3b2-b7d3-48fb-a8ea-b36254449520.png)

### Operating system

Windows 11

### Community airline

VirtualUA 

### smartCARS Version

Sc3 beta

### Plugins installed

Unknown

**Comment by xusmcxjasonx** [comment]
production.ERROR: App\Services\UserService::adjustFlightTime(): Argument #2 ($minutes) must be of type int, null given

this is the log in phpvms7

**Comment by bgiorgio0506** [comment]
@Expressjetxe Can you please send us your combined.log? You can find this at %localappdata%\TFDi Design\smartCARS 3\logs
