### ISSUE TITLE
[BUG] - Chat horizontal scrollbar

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#134]
### Describe the bug

With a large user list, it looks like a horizontal scroll bar is being shown (this is on default window size when launching.)

### How do you reproduce this bug?

1. Open chat with a lot of users (at least enough to make the user list scrollable.

### Expected behavior

Horziontal scroll should not be there.

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/233747543-ae657c7a-6e94-4e98-bb1f-99d6f8fd2d2b.png)

### Operating system

Windows 11

### Community airline

Walker Air Treansport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

### Additional context

N/A

**Comment by walkerairtrans** [comment]
Also, it completely breaks up the chat view when you scroll the user list all the way to the bottom.

![image](https://user-images.githubusercontent.com/127605985/233747934-beccdb80-3e1a-4127-b596-c356f3222571.png)

**Comment by Jishwaah** [comment]
Confirmed and reproduced. Appears to only be an issue once the list of users online extends beyond the vertical height.

![9zCXQDzVDY](https://user-images.githubusercontent.com/7196643/233754677-d18aa5c1-22a6-4a8c-b680-8e10c02ecfcc.jpg)

**Comment by turbofandude** [comment]
This should be fixed in 0.8.1+.

**Comment by turbofandude** [comment]
This has been fixed as of 0.8.1.
