### ISSUE TITLE
[FEATURE] - Filter out non-VA pilots when in VA Chat mode

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#135]
### Is your feature request related to a problem? Please describe.

It is not.

### Describe the solution you'd like

When you click on your VA under conversations, have the user list filter out non-VA pilots.

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by turbofandude** [comment]
This has been implemented as of 0.8.1.

**Comment by turbofandude** [comment]
This was completed in 0.8.1.
