### ISSUE TITLE
[BUG] - Installing/Running as admin causes issues with the app

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#136]
### Describe the bug

Installing the application as admin and/or running the application as admin is causing issues.

Issue 1: JavaScript error occurred in the main process (see screenshot)
Issue 2: Unable to start a flight; states it cannot connect to the simulator

Opening the .EXE and unchecking "run as administrator" resolves both these issues immediately.

### How do you reproduce this bug?

1. Install and/or run the application as admin

### Expected behavior

Shouldn't break when 'running as admin' is enabled. Agree it shouldn't always be run like this but should definitely not break it.

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/233750873-32ae0eeb-283c-4927-bc3b-e303f35e9f53.png)

### Operating system

Windows 11

### Community airline

Walker Air Treansport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

### Additional context

N/A

**Comment by Thien42** [comment]
The app is not meant to be ran as admin, but we'll check why this error happens

**Comment by Thien42** [comment]
Will be fixed in the next update.
