### ISSUE TITLE
[FEATURE] - Change aircraft after bidding on a flight

### ISSUE THREAD

**Issue by ChrisAHD** [invernyx/smartcars-3-bugs#137]
### Describe the bug

After bidding on a flight, There is no where to go and change the aircraft type or Registration.
 

### How do you reproduce this bug?

Bid flight
Double Click on Bidded flight
No where to change Aircraft

### Expected behavior

There should be a dropdown capability to make an aircraft change before prodeeding to fly.

### Screenshots

![Screenshot_115](https://user-images.githubusercontent.com/23268962/233752961-283e5d4f-4c38-4657-9bcf-79d042c026ec.png)
![Screenshot_119](https://user-images.githubusercontent.com/23268962/233753021-12e2542f-69d5-4d1b-baa5-f8f7bcef1b29.png)

### Operating system

Windows 11

### Community airline

Virtual Oneworld Alliance 

### smartCARS Version

3.0.1

### Plugins installed

Flight Center, Chat, Flight Tracking, Logbook, Map, SimBrief

**Comment by GenericNerd** [comment]
This is not possible due to limitations with both phpVMS 7 and phpVMS 5. Some routes do not offer all aircraft to a user, meaning we'd need to present you with the "Search For a Flight" page again. It is easier to have you delete the bid and create a new one in this instance.
