### ISSUE TITLE
[BUG] - Failed to book flight

### ISSUE THREAD

**Issue by Expressjetxe** [invernyx/smartcars-3-bugs#138]
### Describe the bug

Sc3 won’t let me bid says failed to book flight

### How do you reproduce this bug?

Click on bid

### Expected behavior

Bids should become active

### Screenshots

![IMG_0105](https://user-images.githubusercontent.com/131483820/233753227-3a4ebe72-eca0-4893-8c96-43ec3ba3b348.jpeg)

### Operating system

Win 12

### Community airline

VirtualUA 

### smartCARS Version

Sc3

### Plugins installed

Chat flight center flight tracking logbook map

**Comment by bgiorgio0506** [comment]
@Expressjetxe We will need your combined.log to debug this issue further. Can you please send it to us? You can find it at %localappdata%\TFDi Design\smartCARS 3\logs

**Comment by GenericNerd** [comment]
Windows 12 isn't an operating system, could you please edit your post to include the correct Windows and smartCARS versions?

**Comment by GenericNerd** [comment]
No further information was given which was needed to resolve this issue. This will be closed as invalid. If you wish to provide the information requested, please open a new issue and refer back to this one.
