### ISSUE TITLE
[FEATURE] - Offer ability to change update frequency of ACARS

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#139]
### Is your feature request related to a problem? Please describe.

The current interval of sending information to APIs is `30 seconds`. Some VAs may want the data more or less frequently.

### Describe the solution you'd like

Offer the ability to allow VAs to choose update timeframes from something like the below

- `5 seconds`
- `15 seconds`
- `30 seconds`
- `60 seconds`

### Describe alternatives you've considered

Making a plugin

### Additional context

You would need to have a disclaimer about the shorter updates and how this will increase inbound network traffic

**Comment by GenericNerd** [comment]
We will not be allowing Virtual Airlines to change the frequency of the flight update. There are features planned in the future which will hopefully be clear as to why
