### ISSUE TITLE
[BUG] - `View Pireps` button in Flight Center not working

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#141]
### Describe the bug

Title says it all

### How do you reproduce this bug?

1. Navigate to Flight Center
2. Click on `View Pireps`

### Expected behavior

its taken you to your logbook

### Operating system

Win 10 Pro 10.0.19044

### Community airline

QVirtual

### smartCARS Version

0.8.0.2

### Plugins installed

All except simbrief

### Additional context

Would need to hide the button if the `logbook` plugin is not enabled

**Comment by Thien42** [comment]
Will be fixed in the next release
