### ISSUE TITLE
[FEATURE] - Maximum number of characters for welcome message

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#142]
### Is your feature request related to a problem? Please describe.

I tried to enter a long message in the welcome text in SC3 Central however it cut off the text when I hit update

### Describe the solution you'd like

Provide a helper text for the maximum number of allowable characters

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by turbofandude** [comment]
Fixed now - thank you!
