### ISSUE TITLE
[FEATURE] - Flying On or Off line selection?

### ISSUE THREAD

**Issue by PBCool1** [invernyx/smartcars-3-bugs#144]
### Is your feature request related to a problem? Please describe.

Is this not an option anymore for Sc3 or is this to become an add on?
![Screenshot (1)](https://user-images.githubusercontent.com/49513067/233864072-897ac85f-c34f-4f71-b6d3-1ac4689d0862.png)

### Describe the solution you'd like

Same as Sc2...able to select if online or not.

### Describe alternatives you've considered

None

### Additional context

This selection reports to Live Flight on the site.
![Screenshot_1](https://user-images.githubusercontent.com/49513067/233864044-e4a4febe-007a-463e-9289-c88e1a8a9662.png)

**Comment by Thien42** [comment]
I think it depends on what you mean by offline:
- You are able to fly without joining an online network like VATSIM/IVAO/POSCON etc ...
- However you will not be able to use the app without an internet connection

**Comment by GenericNerd** [comment]
@Thien42 I think they mean the first option, to not fly on a network but to fly with an internet connection.
Flying on smartCARS without an internet connection would cause quite a few issues.

**Comment by walkerairtrans** [comment]
He's talking about providing the option box to choose Offline, VATSIM, IVAO, Poscon, PilotEdge, etc. In SC2 you send the network with the update/position report. It's one of those listed above.

I use that information to color the aircraft icons on our maps to indicate if a pilot is flying offline, on VATSIM, PilotEdge, etc. It let's other pilots see who are on what networks and sometimes it gets folks joining up to do sectors with others.

I would like to see this option exist in the new app as well.

**Comment by BossOfGames** [comment]
Couldn't this be implemented by having the VA website watch the data feeds for the online network and detect if the flight is flown online? Wouldn't this be a more accurate solution than to have a dropdown that relies on the user to select if they're doing the flight online or not?

**Comment by johnatasmatos** [comment]
As there is still no tool for this, we created a way for the pilot to write the name of the flight network anywhere in the comments field and the system automatically identifies it, we also do this to signal when the pilot needs to switch to landing at the alternative airport and the system changes the pilot's position based on the code we created for alternative 1 and 2.

We hope to have tools like this natively.

**Comment by RandyD59** [comment]
This feature is important to us as we use this data firstly for our Vatsim VA audits.

**Comment by turbofandude** [comment]
We will re-add this and also allow an updated selection mid-flight (per user requests).

**Comment by walkerairtrans** [comment]
Perhaps a last used state too so it doesn't always default offline?

**Comment by turbofandude** [comment]
This has been added back to the flight center in 0.8.2. Thank you!

**Comment by walkerairtrans** [comment]
I don't see where we can change it in flight?

![image](https://user-images.githubusercontent.com/127605985/236077090-7c7aa237-e5ab-4975-b983-a354a4a0a501.png)
