### ISSUE TITLE
[BUG] - Units available without simBrief plugin installed

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#146]
### Describe the bug

Fabio said the units setting should only be visible with the simBrief plugin installed, however it is not.

### How do you reproduce this bug?

1. Don't install the simBrief plugin.
2. Check settings and you see the Units setting item.

### Expected behavior

If the Units setting is strictly for the simBrief plugin, remove it if the plugin is not installed. I also recommend changing the wording to say "Units to use with simBrief Plugin." I've had people asking why it isn't changing the log entries like it did in SC2.

### Screenshots

![smartcars3_CwFPSA6juF](https://user-images.githubusercontent.com/127605985/234113349-c0b20958-2eeb-4e9e-aa95-db58cc417886.png)

![smartcars3_NMj5BJ8R8e](https://user-images.githubusercontent.com/127605985/234113352-66b83a28-90fc-4f3f-8b9e-9004afb2eb75.png)

### Operating system

Windows 11

### Community airline

Walker Air Treansport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by Thien42** [comment]
We will support the units for the entire app and not only for the Simbrief plugin in the future

**Comment by Thien42** [comment]
Will be provided by https://github.com/invernyx/smartcars-3-bugs/issues/112
