### ISSUE TITLE
[BUG] - Aircraft null on complete

### ISSUE THREAD

**Issue by bgiorgio0506** [invernyx/smartcars-3-bugs#147]
Another "We could not file your flight due to an error. Further information can be found in your log."
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11302708/error.log)
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11302710/combined.log)

I was not logged into the TFDi account.

_Originally posted by @Ravenshammer in https://github.com/invernyx/smartcars-3-bugs/issues/121#issuecomment-1518924838_

**Comment by GenericNerd** [comment]
Duplicate
