### ISSUE TITLE
[BUG] - Non-partner communities are shown on the launch screen

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#148]
### Describe the bug

The launch screen shows non-partner VA's, even when not searching which is invalid behaviour

### How do you reproduce this bug?

1. Launch smartCARS
2. Log-in to TFDi Design (or skip)

### Expected behavior

Non-partner VA's should only be visible when searching

### Operating system

Windows 11 22H2

### Community airline

Any

### smartCARS Version

0.8.0.2

### Plugins installed

Irrelevant

**Comment by Thien42** [comment]
Will be fixed in the next update
