### ISSUE TITLE
[BUG] - Rank Icon should not be inverted if specified

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#149]
### Describe the bug

The rank icon is inverted in dark mode, even if specified.

### How do you reproduce this bug?

1. Log into a VA
2. Have a rank with an icon
3. Go to dark mode

### Operating system

Windows 11 22H2

### Community airline

Any

### smartCARS Version

0.8.1.2

### Plugins installed

Irrelevant

### Additional context

In smartCARS Hub.

**Comment by turbofandude** [comment]
This will be resolved in the next version. Thank you!
