### ISSUE TITLE
[BUG] - Broken dark mode logos

### ISSUE THREAD

**Issue by johnatasmatos** [invernyx/smartcars-3-bugs#150]
### Describe the bug

Dark mode logo images are not being scanned, the link is ending with '**.pn**' only.

### How do you reproduce this bug?

url of logos in dark mode ending with '**.png**'

### Operating system

Windows 11 Pro 22H2

### Community airline

FLYGOL

### smartCARS Version

0.8.1

### Plugins installed

chat, flight center, flight tracking, logbook, map

**Comment by jordanhavard** [comment]
@johnatasmatos might be best to attach some screenshots. Dark mode logos seem to be working ok for me. (Maybe try uploading new logos again in SC3 Central)

**Comment by johnatasmatos** [comment]
I tried to send it again today, and it won't go due to the url being incomplete.

![s1](https://user-images.githubusercontent.com/106502293/235162556-695b1b9c-953d-495d-83ee-da2ddd750202.png)



And in the other image, as it appears in CS3.

![s2](https://user-images.githubusercontent.com/106502293/235163083-6679a7f2-b4bf-43da-8418-cd32dc65d99b.png)

**Comment by turbofandude** [comment]
Turns out we had the field in the database set to too few characters. Fixed now - thank you!
