### ISSUE TITLE
[FEATURE] - Can Sc3 detect what Sim is being used?

### ISSUE THREAD

**Issue by PBCool1** [invernyx/smartcars-3-bugs#152]
### Is your feature request related to a problem? Please describe.

I would like the Pirep reports to also show what simulator is being used.

### Describe the solution you'd like

I would like the Pirep reports to also show what simulator is being used.

### Describe alternatives you've considered

Not sure

### Additional context

Appreciate all of the trouble shooting.

**Comment by jordanhavard** [comment]
Big +1 for this, even if it was a parameter that could be added to SC3 Central in the flight logger

**Comment by bgiorgio0506** [comment]
Yes it technically can detect client side but we do not use it

**Comment by walkerairtrans** [comment]
> 

Can we make this available so we can add it to the log? It would be helpful for us troubleshooting issues if we're able to know what simulator was used.

**Comment by turbofandude** [comment]
This will be added to 0.8.2

**Comment by walkerairtrans** [comment]
What is the variable?

I only see;

isXPlane: false
simulatorVersion: 13
