### ISSUE TITLE
[FEATURE] - Return to login if session is invalidated 

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#154]
### Describe the bug

If a users session is invalidated, the client will throw a 401 however won't redirect the user to the login screen

### How do you reproduce this bug?

1. Login to SC3
2. Make a login request through postman (or manually invalidate session through DB)
3. navigate to another page 
4. Observe 401 error in console

### Expected behavior

Redirect to login

### Operating system

Windows 10 pro 10.0.19044

### Community airline

QVirtual

### smartCARS Version

0.8.1.2

### Plugins installed

all except simbrief

### Additional context

while this may considered an edge case, I think its still something that should be implemented client side

**Comment by turbofandude** [comment]
We are going to change how session workflow works, eliminating the likelihood of a user being actively in the application with an expired session. This, therefore, removes the need for the UI to handle this.
