### ISSUE TITLE
[BUG] - PIREP filing issue

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#155]
### Describe the bug

I had a pilot complete a flight recently and was unable to submit with a weird sourceUri being passed by SC3

### How do you reproduce this bug?

Unsure on exact repo steps, Was filing ok for me 🤷‍♂️ 

### Operating system

Will update once known

### Community airline

QVirtual

### smartCARS Version

0.8.1.2

### Plugins installed

all except simbrief 

### Additional context

This was in the error log.

`error: Error could not complete flight, error code: 404 with message:  {"code":404,"name":"HttpClientError","response":{"message":""},"sourceUri":"https://staging-crew.qvirtual.com.au/api/smartcars/flights/complete","timestamp":"2023-04-28T05:29:28.209Z"}`

I'm awaiting a full log (will post once received)

**Comment by GenericNerd** [comment]
There should be a message should be provided when the API returns a 404, but I'm also aware you are using your own solution for an API. On our side, a 404 can only happen if the bid no longer exists.

**Comment by jordanhavard** [comment]
Will continue to investigate with more verbose logging - cheers 👌

**Comment by jordanhavard** [comment]
@GenericNerd Turns out `pirepID` must be sent back to the client. Pireps file no issues now
