### ISSUE TITLE
[BUG] - Reported bank exceeded 30 degrees on auto pilot

### ISSUE THREAD

**Issue by rstratman67** [invernyx/smartcars-3-bugs#156]
### Describe the bug

On take off on auto pilot smartcars reported exceed 30 degree bank, X-Crafts Legacy 650

Flying Embraer ERJ Family Legacy X-Crafts X-CRAFTS

2023-04-28T16:19:45.689Z - Bank exceeded 30 degrees

### How do you reproduce this bug?

Second flight where minimal turns in flight plan - again on auto pilot

### Expected behavior

not to exceed bank of 30 degrees

### Operating system

Windows 10 latest build

### Community airline

Fly Virtual

### smartCARS Version

v0.8.1.2

### Plugins installed

All verified plugins

**Comment by turbofandude** [comment]
The code checks for bank angle > 30 degrees blindly - is it possible the wings did exceed that roll, even if only briefly?

**Comment by turbofandude** [comment]
No response or recreation - closing. Please re-report if it reoccurs.
