### ISSUE TITLE
[BUG] - Icons messed up in Dark Mode?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#157]
### Describe the bug

Looks like all the icons are different with dark mode now? Also, Chat icon appears to be completely black, and others do not change if you are on them.

Not sure if this is expected or not.

See screenshot.

### How do you reproduce this bug?

1. Open the app and enable dark mode.

### Expected behavior

I think the icon colors (not selected) are good, but they should be a different color when you select one?

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/235273743-2b1bd8e7-ba34-44e6-96dc-bc3fcb341540.png)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
I was not able to reproduce this. The icons are white/light when in dark mode here. Can you clarify the steps to reproduce?

**Comment by walkerairtrans** [comment]
> I was not able to reproduce this. The icons are white/light when in dark mode here. Can you clarify the steps to reproduce?

Apologies I didn't realize this but they seem to have fixed themselves.

I don't know what I did. Maybe it was combination of update/relaunching the app that sorted it.

**Comment by turbofandude** [comment]
It's possible caching/outdated files were at play here. Thank you for following up!
