### ISSUE TITLE
[BUG] - Bids & Flights not being shown

### ISSUE THREAD

**Issue by DeltaVirtualOrg** [invernyx/smartcars-3-bugs#158]
### Describe the bug

Bids and flights not showing up in smartcars for our VA users. when you get to those pages it says failed to fetch flights and failed to fetch bids

### How do you reproduce this bug?

1. Navigate to log book or flight center

### Expected behavior

for it to show pireps flights and bids

### Operating system

Windows 10

### Community airline

Delta Virtual

### smartCARS Version

0.8.1.2

### Plugins installed

chat, map, flight center, logbook

### Additional context

this is whats being recieved from the api
`[{"bidID":1892,"code":"AAL","number":1,"type":"P","departureAirport":"KJFK","arrivalAirport":"KLAX","flightLevel":null,"distance":2148.3,"departureTime":null,"arrivalTime":null,"flightTime":1.6664999999999999,"daysOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],"notes":"Expected Callsign: AMERICAN 1 (AAL1). Please check: https://www.flightradar24.com/data/flights/aa1","aircraft":[1,2,3,5,132,159,165,190,196,292,296,297,328,329,330,331,335,360,364,365,369,390,414,455,463,468,471,483,485,499,544,545,571,580,584,596,598,605,607,608,610,612,614,618,624,631,676,686,708,719,721,724,752,766,770,793,817,821,822,826,831,841,865,866,876,1850,1868,1978,2009,2050,2240,2250,2441,2529,2619,2732,2838,2858,2898,2900,3048,3177,3198,3223,3293,3339,3625,3886,4048,4058,4185,4277,4314,4632,4641,4826,4836,4851,4956,5058,5105,5128,5263,5280,5329,5416,5424,5529,5846,6091,6490,7009,7059,7173,7363,7591,7592,7593,7595,7596,7599,7625,7706,7780,7792,7793,7800,7917,7944,7947,7951,7952,8097,8107,8145,8149,8177,8310,8311,8312,8341,8360,8376,8477,8570,8600,8655,8768,8788,8847,8865,8946,8976,8986,8987,9230,9264,9339,9382,9423,9424,9425,9426,9427,9428,9429,9430,9431,9432,9433,9434,9435,9436,9437,9438,9439,9440,9441,9442,9443,9444,9445,9446,9447,9448,9449,9450,9451,9452,9453,9454,9455,9456,9457,9458,9459,9460,9461,9462,9463,9464,9465,9466,9467,9468,9469,9470,9471,9472,9473,9474,9475,9476,9477,9478,9479,9480,9481,9482,9483,9484,9485,9486,9487,9488,9489,9490,9491,9492,9493,9494,9495,9496,9497,9498,9499,9500,9501,9502,9503,9504,9505,9506,9507,9508,9509,9510,9511,9512,9513,9514,9515,9516,9517,9518,9519,9520,9521,9522,9523,9524,9525,9526,9527,9528,9529,9530,9531,9532,9533,9534,9535,9536,9537,9538,9539,9540,9541,9542,9543,9544,9545,9546,9547,9548,9549,9550,9551,9552,9553,9554,9555,9556,9557,9558,9559,9560,9561,9562,9563,9564,9565,9566,9567,9568,9569,9570,9571,9572,9573,9574,9575,9577,9578,9579,9580,9581,9582,9584,9587,9588,9589,9590,9591,9592,9593,9594,9595,9596,9597,9598,9599,9600,9601,9602,9603,9604,9605,9606,9607,9608,9611,9612,9613,9614,9615,9616,9617,9618,9619,9620,9621,9622,9623,9624,9625,9626,9627,9628,9629,9630,9631,9632,9633,9634,9635,9636,9637,9638,9639,9640,9641,9642,9643,9644,9645,9646,9647,9648,9649,9650,9651,9652,9653,9654,9657,9659,9660,9661,9662,9663,9664,9665,9666,9667,9668,9669,9670,9671,9672,9673,9674,9680,9681,9682,9683,9684,9685,9686,9687,9688,9689,9690,9691,9692,9693,9694,9695,9696,9697,9698,9699,9700,9701,9702,9703,9704,9705,9706,9707,9708,9709,9710,9711,9712,9713,9714,9715,9716,9717,9718,9719,9720,9721,9722,9723,9724,9725,9726,9727,9728,9729,9730,9731,9732,9733,9735,9736,9737,9738,9739,9740,9741,9742,9743,9744,9745,9746,9747,9748,9749,9751,9753,9756,9757,9758,9759,9760,9761,9762,9763,9764,9765,9776,9777,9778,9779,9780,9781,9792,9802,9803,9804,9805,9806,9807,9808,9809,9810,9811,9812,9813,9814,9815,9816,9817,9818,9819,9820,9821,9822,9823,9824,9825,9826,9827,9828,9829,9830,9831,9832,9833,9834,9835,9836,9837,9838,9839,9840,9841,9842,9843,9844,9845,9846,9847,9848,9849,9850,9851,9852,9853,9854,9855,9856,9857,9858,9859,9860,9862,9863,9864,9865,9866,9867,9868,9869,9870,9871,9872,9873,9874,9875,9876,9877,9878,9879,9880,9881,9882,9883,9884,9885,9886,9887,9888,9889,9890,9891,9892,9893,9894,9895,9896,9897,9898,9900,9901,9902,9903,9904,9905,9906,9907,9908,9909,9910,9911,9912,9913,9914,9915,9916,9917,9918,9919,9920,9921,9922,9923,9924,9925,9926,9927,9928,9929,9930,9931,9932,9933,9934,9935,9936,9937,9938,9939,9940,9941,9942,9943,9944,9945,9946,9947,9948,9949,9950,9951,9952,9953,9954,9955,9956,9957,9958,9959,9960,9961,9962,9963,9964,9965,9966,9967,9968,9969,9970,9971,9972,9973,9974,9975,9976,9977,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064,10065,10066,10067,10068,10069,10070,10071,10072,10073,10074,10075,10076,10077,10078,10079,10080,10081,10082,10083,10084,10085,10086,10087,10088,10089,10090,10091,10092,10093,10094,10095,10096,10097,10098,10099,10100,10101,10102,10103,10104,10105,10106,10107,10108,10109,10110,10111,10112,10113,10114,10115,10116,10117,10118,10119,10120,10121,10122,10123,10124,10125,10126,10127,10128,10129,10130,10131,10132,10133,10134,10135,10136,10137,10138,10139,10140,10141,10142,10143,10144,10145,10146,10147,10148,10149,10150,10151,10152,10153,10154,10155,10156,10157,10158,10159,10160,10161,10162,10163,10164,10165,10166,10167,10168,10169,10170,10171,10172,10173,10174,10175,10176,10177,10178,10179,10180,10181,10182,10183,10184,10185,10186,10187,10188,10189,10190,10191,10192,10193,10194,10195,10196,10197,10198,10199,10200,10201,10202,10203,10204,10205,10206,10207,10208,10209,10210,10211,10212,10213,10214,10215,10216,10217,10218,10219,10220,10221,10222,10223,10224,10225,10226,10227,10228,10229,10230,10231,10232,10233,10234,10235,10236,10237,10238,10239,10240,10241,10242,10243,10244,10245,10246,10247,10248,10249,10250,10251,10252,10253,10254,10255,10256,10257,10258,10259,10260,10261,10262,10263,10264,10265,10266,10267,10268,10269,10270,10271,10272,10273,10274,10275,10276,10277,10278,10279,10280,10281,10282,10283,10284,10285,10286,10287,10288,10289,10290,10291,10292,10293,10294,10295,10296,10297,10298,10299,10300,10301,10302,10303,10304,10305,10306,10307,10308,10309,10310,10311,10312,10313,10314,10315,10316,10317,10318,10319,10320,10321,10322,10323,10333,10343,10353,10354,10355,10356,10357,10358,10359,10360,10361,10362,10363,10364,10365,10366,10367,10368,10369,10370,10371,10372,10373,10374,10375,10376,10377,10378,10379,10380,10381,10382,10383,10384,10385,10386,10387,10388,10389,10390,10391,10392,10393,10394,10395,10396,10397,10398,10399,10400,10401,10402,10403,10404,10405,10406,10407,10408,10409,10410,10411,10412,10413,10414,10415,10416,10417,10418,10419,10420,10421,10422,10423,10424,10425,10426,10427,10428,10429,10430]}]`

url location 
https://crew.deltavirtual.xyz/smartcars/api/phpvms7/

**Comment by turbofandude** [comment]
@GenericNerd This may be one for you to look into.

Edit: Maybe related to the PIREP ID type issue.

**Comment by turbofandude** [comment]
We need to implement an aircraft selection option for flights of this nature. We will do so for the next update.

**Comment by turbofandude** [comment]
This is fixed in 0.9 now.

**Comment by turbofandude** [comment]
Further to the above: it will require a web script (API) update as well.

**Comment by DeltaVirtualOrg** [comment]
this still is an issue with the latest api update

**Comment by GenericNerd** [comment]
@StevenP1999 No update has been released yet. Please wait until the update is released to try again
