### ISSUE TITLE
[FEATURE] - Elapsed Flight Time Variable

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#159]
### Is your feature request related to a problem? Please describe.

No, it is not related to a problem.

### Describe the solution you'd like

Can we make {elapsedFlightTime} available to flight tracking? I'd like to provide this in the log entry.

4/29/2023 3:25:24 PM | Deboarding with a total flight time of {elapsedFlightTime}

### Describe alternatives you've considered

None.

### Additional context

N/A

**Comment by turbofandude** [comment]
We will consider adding this but for the time being, that particular variable is only for internal use.

**Comment by turbofandude** [comment]
I wanted to follow this up - we are adding the simulation time (i.e. the clock time in the sim at the time of the log item) to the log items in the next update. This will allow log items/post-flight reviews to show data/log events in context of the sim itself.

**Comment by walkerairtrans** [comment]
> I wanted to follow this up - we are adding the simulation time (i.e. the clock time in the sim at the time of the log item) to the log items in the next update. This will allow log items/post-flight reviews to show data/log events in context of the sim itself.

Understood. I just liked the little line at the end that said your flight time was X. It helps when people think we cheated them. 😂
