### ISSUE TITLE
[BUG] - Landing Rate Accuracy in Log item versus POST data

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#162]
### Describe the bug

Landing rate came in through the POST as:

"landingRate":"55.364175"

Log shows:

{"eventId":"x6BFTWDuSRyYXYw3","eventElapsedTime":"0.6665094444444561","eventTimestamp":"2023-05-01T18:39:49.807Z","eventCondition":"{phase} equals {str:0}","message":"**Touched down at 69 fpm**, 1.0g, 98 kts, true heading 066, 2 degrees pitch, 0 degrees bank, wind 080 at 3 kts, fuel remaining 1709"}

### How do you reproduce this bug?

1. Unsure how to reproduce.

### Expected behavior

Log rate should match raw data coming in.

### Screenshots

N/A

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by walkerairtrans** [comment]
Had another incident.

"landingRate":"-17.685778125"

{"eventId":"SGJGMUy8W6TAcgkZ","eventElapsedTime":"0.7016680555555416","eventTimestamp":"2023-05-02T14:51:58.565Z","eventCondition":"{phase} equals {str:0}","message":"**Touched down at -2 fpm**, 1.0g, 92 kts, true heading 025, 1 degrees pitch, 1 degrees bank, wind 008 at 8 kts, fuel remaining 1877"}

-------------

"landingRate":"-34.602609375"

{"eventId":"yKRhU9OzoXY0YzVw","eventElapsedTime":"2.9012638888889453","eventTimestamp":"2023-05-02T14:46:02.723Z","eventCondition":"{phase} equals {str:0}","message":"Touched down at -359 fpm, 1.4g, 131 kts, true heading 181, 3 degrees pitch, -3 degrees bank, wind 260 at 14 kts, fuel remaining 9709"}

**Comment by turbofandude** [comment]
This has been resolved in 0.8.2.
