### ISSUE TITLE
[BUG] - "End Flight" button works when engines are running

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#163]
### Is your feature request related to a problem? Please describe.

You can submit a PIREP with the engines running. This can lead to inadvertently submitting while in-flight. In my case, I look at things like engine shutdown/etc to run times. If they can submit without shutting down then it defeats checks I have in place.

### Describe the solution you'd like

Block 'End Flight' if the engines are running like in SC2.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by turbofandude** [comment]
Resolved in 0.8.2

**Comment by walkerairtrans** [comment]
Just started a flight for a bid that was deleted from the website. It started and is currently spamming DATA.

![image](https://user-images.githubusercontent.com/127605985/236071018-39b2726b-9bc3-4f05-96f9-181e5b4045ca.png)
