### ISSUE TITLE
[BUG] - Flying Online Selection "Offline" Broken phpVMS 5 API

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#166]
### Describe the bug

phpVMS 5 API is broken -- the $_POST['network'] is sent blank for 'Offline' instead of 'Offline' resulting in a 400 return.

I got around it by doing this at the top of update.php

if ($_POST['network'] == '') { $_POST['network'] = 'Offline'; }

### How do you reproduce this bug?

1. Start a flight with a phpVMS 5 API server
2. You get 400 return code

### Expected behavior

Should not cause a 400 error.

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/236073275-a793ef24-3db5-44cf-a733-ad536acd633d.png)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
@bgiorgio0506 This isn’t my issue. You should be sending offline to the API, not blank

**Comment by bgiorgio0506** [comment]
will be fixed next update

**Comment by turbofandude** [comment]
Fixed in 0.8.3+
