### ISSUE TITLE
[BUG] - Map is missing all VA traffic currently flying

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#167]
### Describe the bug

I'm currently flying outside Chicago and I'm not on the map nor anyone else.

### How do you reproduce this bug?

1. Start a flight
2. Open map

### Expected behavior

Should see pilots flying.

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/236077253-d36bc5e4-1832-488d-85fe-696928ad0d2c.png)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by bgiorgio0506** [comment]
@walkerairtrans I cannot reproduce your bug ( as I see my self on production)  make sure you are signed in also with the tfdi account

**Comment by turbofandude** [comment]
Let's also get the log files in here, if possible, please

**Comment by walkerairtrans** [comment]
@bgiorgio0506 @turbofandude it appears we now see planes on the map. Next time it happens I'll grab the logs and open this. I'm seeing other VA now and my own.

**Comment by walkerairtrans** [comment]
Ok, so this is still a problem.

I have (3) pilots currently flying and only 1 of them is visible on the map.

**Logs as requested**
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11423965/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11423966/error.log)

![smartcars3_Yi0OpF69ts](https://user-images.githubusercontent.com/127605985/236901030-956b6084-b391-4a52-8c54-fed5bd4b599f.png)

Active SC3 Sessions Currently
![image](https://user-images.githubusercontent.com/127605985/236901380-7134e941-cd58-400f-8b4a-9bc1729fa107.png)

Here is the flight data details I see in your console--all of them are cruise right now and only WAT426 is shown.

`{
        "callsign": "WAT426",
        "network": "SC3NET",
        "flightplan": {
            "departure": "KDCA",
            "arrival": "PANC",
            "alternate": "",
            "aircraft": "B739",
            "flightRules": "",
            "cruiseAltitude": "",
            "cruiseSpeed": "",
            "enrouteTime": "",
            "depTime": ""
        },
        "lastReport": {
            "altitude": 36799,
            "longitude": -137.802,
            "latitude": 60.7121,
            "groundspeed": 445,
            "heading": 269.67,
            "transponder": 0
        },
        "connectionTime": 0,
        "login": "",
        "pilot": "Colin Mannes",
        "pilotID": 2582,
        "group": 14
    }
    
    `

**Comment by turbofandude** [comment]
As we said, previously, users must be logged into a TFDi Design account to appear on the map. This is a change from previous versions, however, the account we’re referring to is free. You do not need to have a Premium subscription.

**Comment by walkerairtrans** [comment]
> 

I completely missed that. Thanks!
