### ISSUE TITLE
[BUG] - My Flights is accessible when tracking a flight and can start the flight over

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#169]
### Describe the bug

When you are in a flight, my flights is accessible and the Fly! button is clickable. This results in overwriting your file and causing problems.

### How do you reproduce this bug?

1. Start a flight
2. Go to My Flights and click Fly again

### Expected behavior

My Flights fly button should not be clickable if you are in an active flight.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
Found and fixed in 0.8.3+.
