### ISSUE TITLE
[BUG] - Flight can be started for a bid that was deleted 

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#172]
### Describe the bug

Please reference https://github.com/invernyx/smartcars-3-bugs/issues/119 as the problem still persists.

You can still click on Fly! on a bid that was deleted through the website.

### How do you reproduce this bug?

1. Bid a flight
2. Go to flight center
3. Go back to website and delete your bid (not through the ACARS)
4. Go back to ACARS (you are on the flight center already and the old bid is visible) and click fly
5. It says the flight is now started and shows flight tracking

### Expected behavior

In the early alpha tests we had this would not happen. It would error out with a red toast and keep you on the flight center. I hadn't tested this in awhile until just now and it's not doing what it should before.

### Screenshots

Please reference https://github.com/invernyx/smartcars-3-bugs/issues/119

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
Future versions willl reverify the bids list and ensure the flight you're starting still exists.
