### ISSUE TITLE
[FEATURE] - Online Network not passed in complete.php

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#173]
### Describe the bug

The online network value is not being passed in the complete.php when submitting a flight. It is only visible in the update.php file -- checked the $_POST variable coming in and there's no mention of "online" or "network".

`{"bidID":"264173","remainingLoad":"1000.9299999999998","fuelUsed":"58","landingRate":"-49.2126","flightLog":["2023-05-06T23:56:29.153Z - Flying Black Square A36 Bonanza Turbo WAT Black Red","2023-05-06T23:56:29.153Z - Now boarding","2023-05-06T23:57:52.855Z - Engine 1 On","2023-05-06T23:58:59.725Z - Paused","2023-05-06T23:59:16.188Z - Unpaused","2023-05-06T23:59:34.167Z - Pushing back with 224 lb of fuel","2023-05-06T23:59:48.110Z - Taxiing out","2023-05-07T00:01:19.059Z - Taking off","2023-05-07T00:01:34.584Z - Climbing at 101 kts, 7 degrees pitch, 0 degrees bank","2023-05-07T00:01:40.742Z - Gear lever raised","2023-05-07T00:09:17.325Z - Cruising at 7000 ft","2023-05-07T00:23:49.392Z - Descending with 22 nm to go","2023-05-07T00:23:50.420Z - Approach started at 6469 ft AGL with 22 nm to go","2023-05-07T00:27:51.360Z - On final at 3276 ft with 14 nm to go at 161 kts, -2 degrees pitch, -0 degrees bank","2023-05-07T00:32:24.807Z - Gear lever lowered","2023-05-07T00:32:36.673Z - Flaps set to 50%","2023-05-07T00:37:44.334Z - Touched down at -49 fpm, 1.2g, 70 kts, true heading 166, 2 degrees pitch, -0 degrees bank, wind 160 at 16 kts, fuel remaining 166 lb","2023-05-07T00:37:53.582Z - Flaps set to 0%","2023-05-07T00:37:54.097Z - Taxiing to gate, landed in 620 ft","2023-05-07T00:38:57.765Z - Engine 1 Off","2023-05-07T00:38:58.795Z - Deboarding"],"flightData":[{"eventId":"H7upkkMQyKopSKA1","eventElapsedTime":"0.0005666666666666667","eventTimestamp":"2023-05-06T23:56:29.153Z","eventCondition":"{aircraftType} changed or {aircraftType} not_equals {str:0}","message":"Flying Black Square A36 Bonanza Turbo WAT Black Red"},{"eventId":"gSNpbs3R4VVjNaVR","eventElapsedTime":"0.0005666666666666667","eventTimestamp":"2023-05-06T23:56:29.153Z","eventCondition":"{phase} equals {str:0}","message":"Now boarding"},{"eventId":"c8lVJuqXlOzHlRtY","eventElapsedTime":"0.023817222222222052","eventTimestamp":"2023-05-06T23:57:52.855Z","eventCondition":"{engine1Firing} not_equals false","message":"Engine 1 On"},{"eventId":"aVWaV8eqZ9kbLLOh","eventElapsedTime":"0.0422544444444444","eventTimestamp":"2023-05-06T23:58:59.725Z","eventCondition":"{pauseFlag} equals true","message":"Paused"},{"eventId":"s9Mwgh0BsZFVVCcb","eventElapsedTime":"0.042403611111111066","eventTimestamp":"2023-05-06T23:59:16.188Z","eventCondition":"{pauseFlag} not_equals true","message":"Unpaused"},{"eventId":"INXABiLnySfQWM8i","eventElapsedTime":"0.04739777777777787","eventTimestamp":"2023-05-06T23:59:34.167Z","eventCondition":"{phase} equals {str:0}","message":"Pushing back with 224 lb of fuel"},{"eventId":"U0sXhCPb9rUqhYhV","eventElapsedTime":"0.05127083333333353","eventTimestamp":"2023-05-06T23:59:48.110Z","eventCondition":"{phase} equals {str:0}","message":"Taxiing out"},{"eventId":"DGiwyUAZEPKHmb3M","eventElapsedTime":"0.0765341666666675","eventTimestamp":"2023-05-07T00:01:19.059Z","eventCondition":"{phase} equals {str:0}","message":"Taking off"},{"eventId":"Ss2Rrk2VHW3IVfMA","eventElapsedTime":"0.0808466666666676","eventTimestamp":"2023-05-07T00:01:34.584Z","eventCondition":"{phase} equals {str:0}","message":"Climbing at 101 kts, 7 degrees pitch, 0 degrees bank"},{"eventId":"OqX34tt65lsig3sw","eventElapsedTime":"0.08255722222222321","eventTimestamp":"2023-05-07T00:01:40.742Z","eventCondition":"{gearControl} equals 0","message":"Gear lever raised"},{"eventId":"66drH4EqQqiA4ejy","eventElapsedTime":"0.20938611111111377","eventTimestamp":"2023-05-07T00:09:17.325Z","eventCondition":"{phase} equals {str:0}","message":"Cruising at 7000 ft"},{"eventId":"0aF0vPgz3ioX8T6E","eventElapsedTime":"0.45162694444444734","eventTimestamp":"2023-05-07T00:23:49.392Z","eventCondition":"{phase} equals {str:0}","message":"Descending with 22 nm to go"},{"eventId":"6ECHSQAdpySFp8b2","eventElapsedTime":"0.4519125000000029","eventTimestamp":"2023-05-07T00:23:50.420Z","eventCondition":"{phase} equals {str:0}","message":"Approach started at 6469 ft AGL with 22 nm to go"},{"eventId":"679Wc2YuFO83ushw","eventElapsedTime":"0.518840277777784","eventTimestamp":"2023-05-07T00:27:51.360Z","eventCondition":"{phase} equals {str:0}","message":"On final at 3276 ft with 14 nm to go at 161 kts, -2 degrees pitch, -0 degrees bank"},{"eventId":"y2NxI5HZ5jqPwc5U","eventElapsedTime":"0.5947975000000233","eventTimestamp":"2023-05-07T00:32:24.807Z","eventCondition":"{gearControl} not_equals 0","message":"Gear lever lowered"},{"eventId":"Yj6Cg7lQAv6tF3i3","eventElapsedTime":"0.5980938888889128","eventTimestamp":"2023-05-07T00:32:36.673Z","eventCondition":"{flapsControl} changed","message":"Flaps set to 50%"},{"eventId":"cxjWow1SJGUsOtIt","eventElapsedTime":"0.6835552777778207","eventTimestamp":"2023-05-07T00:37:44.334Z","eventCondition":"{phase} equals {str:0}","message":"Touched down at -49 fpm, 1.2g, 70 kts, true heading 166, 2 degrees pitch, -0 degrees bank, wind 160 at 16 kts, fuel remaining 166 lb"},{"eventId":"cQAK1IUQwHsT9nLH","eventElapsedTime":"0.6861241666667103","eventTimestamp":"2023-05-07T00:37:53.582Z","eventCondition":"{flapsControl} changed","message":"Flaps set to 0%"},{"eventId":"t79MUOSKgDXoKxZF","eventElapsedTime":"0.6862672222222659","eventTimestamp":"2023-05-07T00:37:54.097Z","eventCondition":"{phase} equals {str:0}","message":"Taxiing to gate, landed in 620 ft"},{"eventId":"WrYH51mIXeBdWo5q","eventElapsedTime":"0.7039527777778257","eventTimestamp":"2023-05-07T00:38:57.765Z","eventCondition":"{engine1Firing} equals false","message":"Engine 1 Off"},{"eventId":"ljrfRZzPlD2F6p9r","eventElapsedTime":"0.7042388888889369","eventTimestamp":"2023-05-07T00:38:58.795Z","eventCondition":"{phase} equals {str:0}","message":"Deboarding"}],"comments":"","aircraft":"106","flightTime":"0.6027119444444669","route":["KGRK","CONRA2","CLL","DCT","KCLL"]}
`

### How do you reproduce this bug?

1. Pick an online network
2. Complete a flight
3. Submit it and review the POST data

### Expected behavior

Online should be passed through just like it is with update.php function.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by Thien42** [comment]
I can see the network being saved [here](https://github.com/invernyx/smartcars-3-public-api/blob/bc37b916eeb0502e341ed2e75f152dcfadb86023/0.3.2/handlers/phpvms5/flights/update.php#L46)
Did you update to the latest public API ?

**Comment by walkerairtrans** [comment]
> I can see the network being saved [here](https://github.com/invernyx/smartcars-3-public-api/blob/bc37b916eeb0502e341ed2e75f152dcfadb86023/0.3.2/handlers/phpvms5/flights/update.php#L46)
> Did you update to the latest public API ?

That’s the update function, not the complete (submit pirep). I need the value pushed when they submit their pirep so we can mark their logbook as having been on a network. At the moment the only place this shows up is in update function.

**Comment by bgiorgio0506** [comment]
this is gonna be included in the next version
