### ISSUE TITLE
[FEATURE] - Make simulator used variable available in POST

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#175]
### Is your feature request related to a problem? Please describe.

I would like the simulator used variable to be available in the POST payload. I have plans to modify the complete process and add that to a column in my database. I'd rather not parse the log to find it.

### Describe the solution you'd like

Just provide a "simulator" variable in the POST message like we do "source" and others.

### Describe alternatives you've considered

Parsing the log but I prefer not to do that.

### Additional context

This is in reference to closed request https://github.com/invernyx/smartcars-3-bugs/issues/152

**Comment by bgiorgio0506** [comment]
this feature is gonna be included in the RC1
