### ISSUE TITLE
[BUG] - PIREP report missing route

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#176]
### Describe the bug

Route field in the View a PIREP is not populating.

### How do you reproduce this bug?

1. Go to Logbook and open a PIREP

### Expected behavior

Route should populate?

### Screenshots

![image](https://user-images.githubusercontent.com/127605985/236899668-139d841d-1264-4518-948b-4fd35ce7591f.png)

![image](https://user-images.githubusercontent.com/127605985/236899719-cbcde65f-9f77-4c5d-8b9f-c3c30f56329b.png)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
Fixed in 0.9. Thank you!
