### ISSUE TITLE
[BUG] - SC3 Issues on our VA Group Flight Today

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#177]
### Describe the bug

We had 3 guys using SC3 and we all had the same issues with the current SC3 app.  First after logging in through our TFDi accounts we could not see our aircraft or our fellow VA pilots on the map even though we did see other pilots around the globe.  

When it came time to file the pirep it went normally with the green banner saying the pirep was filed but then within a 5-15 seconds a red banner came up and said it could not be filed.  When we checked our admin section of phpVMS the pireps had indeed been filed.   To go further in the SC3 app the flight was also included in our log as it normally would be.  

We did 2 flights back to back so once we had shut down the aircraft, filed the pirep and then tried to start the next flight SC3 said we had an improper scenario so could not start the next flight from our bid.   Once we shut down SC3 and restarted it then the bid worked and we could continue the second flight.

I don't have the exact wording for the notices but hopefully this info will help anyway.

### How do you reproduce this bug?

We all started SC3 using TFDi accounts, then choose Mirage
Started bid and flight normally.

### Expected behavior

I don't expect we should get conflicting reports from SC3 when pirep is filed.

As for the second issue we can do back to back flights in SC2 without issue or restarting required.

### Operating system

Win10

### Community airline

Mirage Executive Charters

### smartCARS Version

0.8.1.2

### Plugins installed

Flight center, Flight tracking, Logbook, Map, Chat

### Additional context

All 3 of us testing SC3 today had the same issues.

**Comment by turbofandude** [comment]
Can you send us your combined.log file from %localappdata%\TFDi Design\smartCARS\logs?

**Comment by PatLeclerc** [comment]
I was also part of that flight and encountered the same issues. I will include my combined.log
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11436933/combined.log)

-could not see our aircraft or our fellow VA pilots on the map
-green banner saying the pirep was filed but then within a 5-15 seconds a red banner came up and said it could not be filed
-improper scenario for the second flight in our bids

**Comment by turbofandude** [comment]
@GenericNerd I believe the problem originates here:
`info: Could not create TFDi Design flight with error code: 400 and message: Invalid type for departure (expected `airport` [Raw Type: `string`]) {"code":400,"name":"HttpClientError","response":{"message":"Invalid type for departure (expected `airport` [Raw Type: `string`])"},"sourceUri":"https://smartcars.tfdidesign.com/v3/api/flight/create","timestamp":"2023-05-09T16:32:16.872Z"}`

The "expected airport, got string" portion of it tells me that we may have a data issue. This explains some of the PIREP filing issues and also the map issues.

**Comment by HondaJet** [comment]
Sorry, I was AFK for the rest of the day.  My combined.log file is attached.
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11442167/combined.log)

**Comment by turbofandude** [comment]
What airport(s) were you flying to in this flight?

**Comment by HondaJet** [comment]
The first flight was 6WI4 to 9WI9; second flight was 9WI9 to KBFW.

**Comment by turbofandude** [comment]
Fixed in the API - this is indeed an API bug. Thank you! (Linked issue: https://github.com/invernyx/smartcars-3-public-api/issues/49)
