### ISSUE TITLE
[FEATURE] - Cancel Flight Confirmation

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#178]
### Is your feature request related to a problem? Please describe.

Would be good to add a confirmation "Do you want to cancel this flight?"

People are people and we'll likely have folks clicking the wrong button and losing their flight all together.

### Describe the solution you'd like

Just put a confirmation up when canceling flight to confirm.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by turbofandude** [comment]
Agreed and added as of 0.9.
