### ISSUE TITLE
[BUG] - Error while connecting to chat server

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#18]
**Describe the bug**
When clicking the chat icon, it returns a `An error occurred while connecting to the chat server.`

**To Reproduce**
1. Login to VA
2. Click chat icon
3. Observe error
4. Clicking retry also fails

**Expected behavior**
Display the chat plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/224796121-1ffe510f-eb7f-4f6f-acb1-1033416641c5.png)
![image](https://user-images.githubusercontent.com/67948773/224796310-9e395b52-8f83-47c2-a401-054e9cb75aff.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: 33
 - Version latest (0.2.3)
 - Plugins used: standard ones on install I think (chat, flight-center, flight-tracking)

**Additional context**
No errors exist within the console (only within web socket message)

**Comment by GenericNerd** [comment]
I'm able to access the chat myself. I'm assigning @turbofandude so that he can ask you any questions he needs to for debugging purposes.

**Comment by GenericNerd** [comment]
With 0.5.6 releasing today, are you able to recheck this to verify whether it is still an issue?

**Comment by jordanhavard** [comment]
> With 0.5.6 releasing today, are you able to recheck this to verify whether it is still an issue?

Confirming I can connect to chat and send messages
