### ISSUE TITLE
[BUG] - Users in Chat who are not

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#181]
### Describe the bug

My testing team is currently offline and not able to access the app for now. It's been 24-hours as I work to implement the API changes. However, I can log in and noticed that 2 people are showing up in Chat for the VA. Looks like you might have a bug that has users sticking to the "online" list who actually are not online.

I verified with both of these they are not connected and the app is closed. They don't even have sessions on my table (I have all sessions revoked and only I can log in.)

### How do you reproduce this bug?

1. Log in and check your VA in chat and see who is online.

### Expected behavior

If a user isn't connected to the app--they should disappear after a time period.

### Screenshots

![smartcars3_AJta2wBoXP](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/0e301072-1f8c-4430-986c-b9c6ab30af30)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
I am not denying that this happens, but I cannot for the life of me recreate it. I've tested connecting from multiple locations, dropped/hung connections (timeout), etc. and it disconnects and removes me as it should. Please let me know if/when it happens again.

**Comment by GenericNerd** [comment]
We have found and reproduced the bug. We're working on a rewrite for the chat server to combat this

**Comment by GenericNerd** [comment]
This will be fixed in 0.9.1
