### ISSUE TITLE
[BUG] - Notifications don't appear on profile page until refreshed

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#182]
### Describe the bug

New notifications aren't shown on the profile page until refreshed

### How do you reproduce this bug?

Get a notification while on the profile page

### Expected behavior

Notifications appear immediately while on the profile page

### Operating system

Windows 11

### Community airline

Dev center

### smartCARS Version

0.9.0

### Plugins installed

all

**Comment by turbofandude** [comment]
Fixed in 0.9.1.
