### ISSUE TITLE
[BUG] - Open news links in system browser

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#183]
### Is your feature request related to a problem? Please describe.

Is it possible to make hyperlinks in the app use the system browser and not your in-window browser? This can be problematic when we're providing links to things specific on our VA website/CrewOps.

### Describe the solution you'd like

Links from SC3 should open using the users system browser.

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by turbofandude** [comment]
We do have this feature - where are you seeing the internal browser behavior?

**Comment by walkerairtrans** [comment]
> We do have this feature - where are you seeing the internal browser behavior?

When I click links in the news area -- looks like links in chat are fine.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/982bb425-55e6-499f-b099-b786e2f61806)

Just curious; are you adding any specific target to the hyperlink in chat that I need to carry to my news?

**Comment by walkerairtrans** [comment]
Just to add; updated to latest release just now and it still happens on hyperlinks in the news section.

**Comment by GenericNerd** [comment]
This will be implemented in 0.9.1
