### ISSUE TITLE
[BUG] - Mirage VA Live Map Not Showing SC3 Details Properly

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#184]
### Describe the bug

This are not a high priority bugs but perhaps they could be corrected before SC3 goes live.  When we look at our Pilot data on our website Live Map the Registration and Aircraft Type are not showing correctly.  I have attached a screenshot of it below.  In this shot MEC0003 is flying SC2 and MEC 0001 & 0184 are flying SC3 beta.  

Another thing we have noticed is every pirep filed with SC3 has the landing rate with digits to the right of decimal.  Here is an example -- Landing Rate: -216.074.   SC2 always shows up with no digits to the right.

If these are things we need to change in our phpVMS please let us know how to do that.
Thanks, Jerry

![image](https://github.com/invernyx/smartcars-3-bugs/assets/131472261/285b9154-fa82-47e4-bbce-e78b9df20ec2)

### How do you reproduce this bug?

When running SC3 our website Live Map is missing Registration and Aircraft Type data as shown in the screenshot.
It happens every time one of our pilots is flying with SC3 instead of SC2.

### Expected behavior

We expect the data to appear in SC3 as it does in SC2.

### Screenshots

![SC3   MEC Live Map](https://github.com/invernyx/smartcars-3-bugs/assets/131472261/da5424e9-19da-4d9b-9d51-2115547d995a)

### Operating system

Win10

### Community airline

Mirage Executive Charters

### smartCARS Version

0.8.1.2

### Plugins installed

Flight center, Flight tracking, Logbook, Map, Chat

**Comment by walkerairtrans** [comment]
SC2 sends the aircraft as the _registration_, SC3 sends the aircraft as the _ID_ in the database. TFDi said they will not change this and many of us agree. The ID of the aircraft as it relates to the database row ID is a better solution going forward.

You will have to modify your maps to use both. The easiest way to do this is to update the function that pulls your data and populates it to your live map. Depending on the code, you can do a simple OR statement to look for registration or ID.

Landing rate is super easy to fix. Just open up the complete.php file in your specific API handler and change the landing rate line to this.

It will round the landingrate to match what the log says and send you a whole number instead of a decimal.

`'landingrate' => round($_POST['landingRate'])`

**Comment by turbofandude** [comment]
@GenericNerd should we consider rounding the landing rate before reporting? I'd prefer to round in the web scripts so the incoming data is full accuracy.

**Comment by turbofandude** [comment]
@HondaJet Yes, @walkerairtrans is correct - we have changed the format for this slightly. That said, I wonder if the default phpVMS live map is expecting registration. If it is, @GenericNerd we'll need to pull the registration from the DB ID and insert it in the web scripts.

**Comment by HondaJet** [comment]
@walkerairtrans Thank you for your comments earlier.  I was able to stumble around in phpVMS and found the complete.php file.  After making the edit you recommended our landing rates with SC3 are now showing up without the digits right of the decimal.

**Comment by HondaJet** [comment]
Unfortunately, last August we lost our webmaster (phpVMS expert too) to Covid and we have no one to help us with our web site and phpVMS.   So we have no clue how to make the needed changes for the Live Map for aircraft info.  :(

If anyone is willing to help we can follow instructions if you point us to what to change.

**Comment by walkerairtrans** [comment]
> Unfortunately, last August we lost our webmaster (phpVMS expert too) to Covid and we have no one to help us with our web site and phpVMS. So we have no clue how to make the needed changes for the Live Map for aircraft info. :(
> 
> If anyone is willing to help we can follow instructions if you point us to what to change.

Hopefully this works and your previous dev didn't do anything crazy.

Open up ACARSData.class.php in your core/common folder.

Find the function "public static function GetACARSData($cutofftime = '')"

Change this:

> $sql = 'SELECT a.*, c.name as aircraftname, c.registration,
> 					p.code, p.pilotid as pilotid, p.firstname, p.lastname,
> 					dep.name as depname, dep.lat AS deplat, dep.lng AS deplng,
> 					arr.name as arrname, arr.lat AS arrlat, arr.lng AS arrlng
> 				FROM ' . TABLE_PREFIX . 'acarsdata a
> 				LEFT JOIN ' . TABLE_PREFIX . 'aircraft c ON a.`aircraft`= c.`registration`
> 				LEFT JOIN ' . TABLE_PREFIX . 'pilots p ON a.`pilotid`= p.`pilotid`
> 				LEFT JOIN ' . TABLE_PREFIX . 'airports AS dep ON dep.icao = a.depicao
> 				LEFT JOIN ' . TABLE_PREFIX . 'airports AS arr ON arr.icao = a.arricao ';

To this:

> $sql = 'SELECT a.*, c.name as aircraftname, c.registration,
> 					p.code, p.pilotid as pilotid, p.firstname, p.lastname,
> 					dep.name as depname, dep.lat AS deplat, dep.lng AS deplng,
> 					arr.name as arrname, arr.lat AS arrlat, arr.lng AS arrlng
> 				FROM ' . TABLE_PREFIX . 'acarsdata a
> 				LEFT JOIN ' . TABLE_PREFIX . 'aircraft c ON a.`aircraft`= c.`registration` OR a.`aircraft` = c.`id`
> 				LEFT JOIN ' . TABLE_PREFIX . 'pilots p ON a.`pilotid`= p.`pilotid`
> 				LEFT JOIN ' . TABLE_PREFIX . 'airports AS dep ON dep.icao = a.depicao
> 				LEFT JOIN ' . TABLE_PREFIX . 'airports AS arr ON arr.icao = a.arricao ';

**Comment by GenericNerd** [comment]
> @GenericNerd should we consider rounding the landing rate before reporting? I'd prefer to round in the web scripts so the incoming data is full accuracy.

We can certainly have a setting in the web scripts which handles the rounding so that we can allow more technically minded communities to get the most precise landing rate they can, while by default, having rounding so that it's the best display for **most** communities

> @HondaJet Yes, @walkerairtrans is correct - we have changed the format for this slightly. That said, I wonder if the default phpVMS live map is expecting registration. If it is, @GenericNerd we'll need to pull the registration from the DB ID and insert it in the web scripts.

phpVMS 5 just displays the `aircraft` column, so again, we could have a default of providing the aircraft registration and provide configuration for more technically minded communities to get the ID alone.
It is worth noting that this is not behaviour we have to worry about in phpVMS 7, since there is no aircraft column to my knowledge.

**Comment by HondaJet** [comment]
Whatever you decide to do go with what works for the majority of your customers.  Since Mirage no longer has our webmaster we are complete newbies to phpVMS.  Fortunately our friend at walkerairtrans (Thanks man) gave us enough that I could get the appropriate files edited.  Right now the landing rate works for us without the extra digits to the right of decimal.   I just have to find our next SC3 pilot flight to test the aircraft column for phpVMS v5

**Comment by HondaJet** [comment]
@walkerairtrans got our Live Map working correctly now.  Thank you man.
Turned out this was not a bug but was a change from what SC2 was using for the live map feed.

**Comment by walkerairtrans** [comment]
I think this can be closed. We should keep the data being the aircraft ID and not the registration number. If VA’s need help converting I am willing to lend a hand. The code to change is minimal and not difficult to do.

**Comment by GenericNerd** [comment]
We will change the API to insert the registration to the `phpvms_acars` table instead of just the aircraft ID for ease of use

**Comment by walkerairtrans** [comment]
> We will change the API to insert the registration to the `phpvms_acars` table instead of just the aircraft ID for ease of use

Will the aircraft ID still be available to us who do not want to use the registration?

**Comment by BossOfGames** [comment]
> > We will change the API to insert the registration to the `phpvms_acars` table instead of just the aircraft ID for ease of use
> 
> Will the aircraft ID still be available to us who do not want to use the registration?

For my use case, I will require aircraft id, or else that'll cause serious issues with my system. We have legacy tail numbers for disabled aircraft in our fleet so the logbooks work, and they conflict with new aircraft using the old registrations.

**Comment by dylanw2014** [comment]
I was wondering if there was a way to get the decimals removed from the data from SC3?

**Comment by GenericNerd** [comment]
> Will the aircraft ID still be available to us who do not want to use the registration?

You will have to modify the API files in your case

**Comment by GenericNerd** [comment]
> I was wondering if there was a way to get the decimals removed from the data from SC3?

We can certainly round the decimals

**Comment by walkerairtrans** [comment]
> > Will the aircraft ID still be available to us who do not want to use the registration?
> 
> You will have to modify the API files in your case

Perfect. I'll keep an eye out for the change and variable to use. Thank you for keeping the ID for us who truly need it. :)

**Comment by GenericNerd** [comment]
Will be fixed in the next API version

**Comment by Osviel02** [comment]
> 

What files are the ones that must be modified so that the registration and the icao of the plane that is being used appears

**Comment by DeltaVirtualOrg** [comment]
@Osviel02 

> > Unfortunately, last August we lost our webmaster (phpVMS expert too) to Covid and we have no one to help us with our web site and phpVMS. So we have no clue how to make the needed changes for the Live Map for aircraft info. :(
> > If anyone is willing to help we can follow instructions if you point us to what to change.
> 
> Hopefully this works and your previous dev didn't do anything crazy.
> 
> Open up ACARSData.class.php in your core/common folder.
> 
> Find the function "public static function GetACARSData($cutofftime = '')"
> 
> Change this:
> 
> > $sql = 'SELECT a.*, c.name as aircraftname, c.registration,
> > p.code, p.pilotid as pilotid, p.firstname, p.lastname,
> > dep.name as depname, dep.lat AS deplat, dep.lng AS deplng,
> > arr.name as arrname, arr.lat AS arrlat, arr.lng AS arrlng
> > FROM ' . TABLE_PREFIX . 'acarsdata a
> > LEFT JOIN ' . TABLE_PREFIX . 'aircraft c ON a.`aircraft`= c.`registration`
> > LEFT JOIN ' . TABLE_PREFIX . 'pilots p ON a.`pilotid`= p.`pilotid`
> > LEFT JOIN ' . TABLE_PREFIX . 'airports AS dep ON dep.icao = a.depicao
> > LEFT JOIN ' . TABLE_PREFIX . 'airports AS arr ON arr.icao = a.arricao ';
> 
> To this:
> 
> > $sql = 'SELECT a.*, c.name as aircraftname, c.registration,
> > p.code, p.pilotid as pilotid, p.firstname, p.lastname,
> > dep.name as depname, dep.lat AS deplat, dep.lng AS deplng,
> > arr.name as arrname, arr.lat AS arrlat, arr.lng AS arrlng
> > FROM ' . TABLE_PREFIX . 'acarsdata a
> > LEFT JOIN ' . TABLE_PREFIX . 'aircraft c ON a.`aircraft`= c.`registration` OR a.`aircraft` = c.`id`
> > LEFT JOIN ' . TABLE_PREFIX . 'pilots p ON a.`pilotid`= p.`pilotid`
> > LEFT JOIN ' . TABLE_PREFIX . 'airports AS dep ON dep.icao = a.depicao
> > LEFT JOIN ' . TABLE_PREFIX . 'airports AS arr ON arr.icao = a.arricao ';
