### ISSUE TITLE
[BUG] - Engine logs are inaccurate in XP11

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#187]
### Describe the bug

I'm opening this up on behalf of my VA and another who posted in Discord.

I've started getting reports from my testers that in XP11 they are seeing situations where single engine planes say all 4 engines started, or a twin engine says that engines 3/4 started, or in weird case spawning in engines 3/4 are on, but then 1/2 show up in the log when starting the real engines.

It seems to only happen in smartCARS 3. They've tested the same aircrafts (at my request) in smartCARS 2 and these behaviors do not happen.

See screenshots I've collected below.

### How do you reproduce this bug?

1. I'm not sure how to really replicate this but to simply load with planes and start a flight to review the behavior.

### Expected behavior

It should show the right engines.

### Screenshots

Image from the Discord thread.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/55fcc3cf-cd95-4a8a-a82c-df9daf31c01d)

Images from my team.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/b0032e33-e032-4848-a827-c58ea457a9d5)

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/a5e373ed-57b1-49d3-b756-463e08ff1298)

This one my pilot loaded in cold and dark. He then started engines 1/2 like normal.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/86ecc0b3-e4c3-4113-b749-79ebff2b5e1e)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
@walkerairtrans Can you try edit the engine part of your config as follows and see if it still causes the issue?

```json
{
      "condition": "{engine1Firing} not_equals false",
      "message": "Engine 1 On"
    },
    {
      "condition": "{engine1Firing} equals false",
      "message": "Engine 1 Off",
      "initialValue": true
    },
    {
      "condition": "{engine2Firing} not_equals false and {enginesCount} > 1",
      "message": "Engine 2 On"
    },
    {
      "condition": "{engine2Firing} equals false and {enginesCount} > 1",
      "message": "Engine 2 Off",
      "initialValue": true
    },
    {
      "condition": "{engine3Firing} not_equals false and {enginesCount} > 2",
      "message": "Engine 3 On"
    },
    {
      "condition": "{engine3Firing} equals false and {enginesCount} > 2",
      "message": "Engine 3 Off",
      "initialValue": true
    },
    {
      "condition": "{engine4Firing} not_equals false and {enginesCount} > 3",
      "message": "Engine 4 On"
    },
    {
      "condition": "{engine4Firing} equals false and {enginesCount} > 3",
      "message": "Engine 4 Off",
      "initialValue": true
    }

**Comment by turbofandude** [comment]
@walkerairtrans Scratch the above, I made a mistake - let's try this one:

```json
{
      "condition": "{engine1Firing} not_equals false",
      "message": "Engine 1 On"
    },
    {
      "condition": "{engine1Firing} equals false",
      "message": "Engine 1 Off",
      "initialValue": true
    },
    {
      "condition": "{engine2Firing} not_equals false and {enginesCount} greater_than 1",
      "message": "Engine 2 On"
    },
    {
      "condition": "{engine2Firing} equals false and {enginesCount} greater_than 1",
      "message": "Engine 2 Off",
      "initialValue": true
    },
    {
      "condition": "{engine3Firing} not_equals false and {enginesCount} greater_than 2",
      "message": "Engine 3 On"
    },
    {
      "condition": "{engine3Firing} equals false and {enginesCount} greater_than 2",
      "message": "Engine 3 Off",
      "initialValue": true
    },
    {
      "condition": "{engine4Firing} not_equals false and {enginesCount} greater_than 3",
      "message": "Engine 4 On"
    },
    {
      "condition": "{engine4Firing} equals false and {enginesCount} greater_than 3",
      "message": "Engine 4 Off",
      "initialValue": true
    },
```

**Comment by walkerairtrans** [comment]
Roger that. I’ll be home from vacation tomorrow and will give it a try.

**Comment by walkerairtrans** [comment]
> @walkerairtrans Scratch the above, I made a mistake - let's try this one:
> 
> ```json
> {
>       "condition": "{engine1Firing} not_equals false",
>       "message": "Engine 1 On"
>     },
>     {
>       "condition": "{engine1Firing} equals false",
>       "message": "Engine 1 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine2Firing} not_equals false and {enginesCount} greater_than 1",
>       "message": "Engine 2 On"
>     },
>     {
>       "condition": "{engine2Firing} equals false and {enginesCount} greater_than 1",
>       "message": "Engine 2 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine3Firing} not_equals false and {enginesCount} greater_than 2",
>       "message": "Engine 3 On"
>     },
>     {
>       "condition": "{engine3Firing} equals false and {enginesCount} greater_than 2",
>       "message": "Engine 3 Off",
>       "initialValue": true
>     },
>     {
>       "condition": "{engine4Firing} not_equals false and {enginesCount} greater_than 3",
>       "message": "Engine 4 On"
>     },
>     {
>       "condition": "{engine4Firing} equals false and {enginesCount} greater_than 3",
>       "message": "Engine 4 Off",
>       "initialValue": true
>     },
> ```

Looks like this worked!
