### ISSUE TITLE
[FEATURE] - Bid Not Valid

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#188]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Thank you for the check/alert that a bid is not valid. Is it possible to make this automatically refresh My Flights when that error pops up?

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/fbe13d62-93b4-4ef1-9132-0814d3a683e8)

### Describe alternatives you've considered

None, user just has to refresh themselves.

### Additional context

N/A

**Comment by turbofandude** [comment]
Added in 0.9.1.
