### ISSUE TITLE
[FEATURE] - Enhance the Bid Validation

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#189]
### Is your feature request related to a problem? Please describe.

It's specific to us and how we handle aircraft modifications, but could be useful to others...

### Describe the solution you'd like

When you click on Fly -- you execute this code in update.php

> $flightDetails = $database->fetch('SELECT ' . dbPrefix . 'schedules.code, ' . dbPrefix . 'schedules.flightnum, ' . dbPrefix . 'schedules.aircraft, ' . dbPrefix . 'schedules.depicao, ' . dbPrefix . 'schedules.arricao, ' . dbPrefix . 'schedules.deptime, ' . dbPrefix . 'schedules.arrtime FROM ' . dbPrefix . 'schedules INNER JOIN ' . dbPrefix . 'bids ON ' . dbPrefix . 'bids.pilotid = ? AND ' . dbPrefix . 'bids.bidid = ? WHERE ' . dbPrefix . 'schedules.id = ' . dbPrefix . 'bids.routeid', array($pilotID, $_POST['bidID']));
> if($flightDetails === array())
> {
>     error(404, 'There is no flight with the specified bid ID');
> }

The POST data only contains the following:

`{"bidID":"267526","uuid":"FtoM9mRV","latitude":"33.65342778523455","longitude":"-84.41318100195828","heading":"36.19","groundSpeed":"0","altitude":"1021.51","distanceRemaining":"488.816052659","phase":"BOARDING","route":[""],"network":"offline","timeRemaining":"0","simVersion":"X-Plane 8"}`

At the time the only thing you provide in POST is the bidID -- is there anyway you can provide the aircraft ID of the specific bid you are clicking Fly on with this? The reason I ask for this is because then I can run that query to check for a bid that matches the bidID AND the aircraftID that you see in the app.

All I need is the ID added to the POST, I can do the rest. :)

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by BossOfGames** [comment]
@walkerairtrans The Flight Center is now open source, so you can add the functionality you desire on your own. Maybe submit the working code as a pull request? https://github.com/invernyx/smartcars-3-flight-center

**Comment by walkerairtrans** [comment]
Come on @GenericNerd make me the happiest man in the world! All I need is the aircraftID provided with the bid.

PWWWWEASE!

**Comment by walkerairtrans** [comment]
@Thien42 @GenericNerd I see that you added the aircraft ID to the const flight in the plugin. However, I'm not sure why this isn't working?

$_POST sends this:
`{"bidID":"598716","uuid":"t38ojmyz","latitude":"30.48582699987602","longitude":"-81.68208209427496","heading":"280.25","groundSpeed":"0","altitude":"17.17","distanceRemaining":"499.926207891","phase":"BOARDING","route":[""],"network":"offline","timeRemaining":"0","aircraft":"247","simVersion":"X-Plane"}`

I've updated the code in update.php to now look for the schedule that meets the pilotID, bidID, and aircraftID.
The database query works and it responds appropriately.
If I delete the bid entirely, the application blocks and gives a red toast that the flight can't be found.
If I change the aircraft ID so it doesn't match what the application thinks it is, the application let's it go and starts tracking the flight.

```
$flightDetails = $database->fetch('SELECT ' . dbPrefix . 'schedules.code, ' . dbPrefix . 'schedules.flightnum, aircraft.id AS aircraft, ' . dbPrefix . 'schedules.depicao, ' . dbPrefix . 'schedules.arricao, ' . dbPrefix . 'schedules.deptime, ' . dbPrefix . 'schedules.arrtime FROM ' . dbPrefix . 'schedules INNER JOIN ' . dbPrefix . 'bids ON ' . dbPrefix . 'bids.pilotid = ? AND ' . dbPrefix . 'bids.bidid = ? AND ' . dbPrefix . 'bids.aircraftid = ? INNER JOIN ' . dbPrefix . 'aircraft AS aircraft ON phpvms_bids.aircraftid = aircraft.id WHERE ' . dbPrefix . 'schedules.id = ' . dbPrefix . 'bids.routeid', array($pilotID, $_POST['bidID'], $_POST['aircraft']));
if($flightDetails === array())
{
    error(404, 'There is no flight with the specified bid ID');
}
```

It logs to the logfile correctly as well.

`error: could not update flight to va with error code 404 and message: There is no flight with the specified bid ID or aircraft ID {"code":404,"name":"HttpClientError","response":{"message":"There is no flight with the specified bid ID"},"sourceUri":"https://acars.walkerair.us/api/smartcars3/flights/update","timestamp":"2023-08-06T15:37:03.754Z"}`

**Comment by walkerairtrans** [comment]
I think I found it.

Here is what the app shows

bookings?nocache=true
_This was before I went and changed the plane on the website. The app shows me in the Airbus A319ACJ_
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/d901cc59-c6b1-4671-adb8-f48d92530dd4)

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/0302d5e5-b288-44d9-acfc-69cd14fb5bc5)

I went to the website and changed it (this is why I needed the ID sent--we have a different kind of AC booking setup that doesn't work with your app's features.)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/ad019864-6c9a-4303-816d-b45bbb82f543)

When I click on Fly--I am expecting it to be blocked because my aircraftID is 83 not 247 (screenshot above).

However, when I click on Fly--I get another bookings?nocache=true and it updates to the correct bid from the site. Notice the ID = 83 now.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/a47c5ee1-ae4a-473c-abb0-1af021320b79)

However, the app still tells me I'm in the ACJ.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/ad66ad9e-59a8-46e2-b95d-30a709fb1785)

I'm fine with the bookings approach -- as long as it updates the app to show the right AC and it submits the right ACID at the end.

I had this issue in smartCARS 2 before pilots would not click the refresh button. Ever. So, they'd do a flight that was completely wrong and it would go through, and I'd have to go back and fix it all.
