### ISSUE TITLE
[FEATURE] - Pressing the `enter` key should allow login

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#19]
**Is your feature request related to a problem? Please describe.**
Once a user finished typing a password, they have to tab twice or move the mouse to click login. 

**Describe the solution you'd like**
When the password field has focus, pressing enter should submit the login request improving UX

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Thien42** [comment]
Duplicate with https://github.com/invernyx/smartcars-3-bugs/issues/6

**Comment by Thien42** [comment]
This has been done already, but we have not yet published a version with this fix :)

**Comment by jordanhavard** [comment]
Apologies, didn't think to check `closed`
