### ISSUE TITLE
[BUG] - On the ground log entry doesn't exist

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#190]
### Describe the bug

I know this isn't "quite" bug but for us at WAT, this is a serious issue because it breaks our automated diversion system and allows people to bypass checks in modules...

In SC2 whenever you landed at a field that was not the destination, this log entry was posted "On the ground 667 nm from the planned arrival airfield".

Is there any way to reproduce this? Or something I can add to the logging engine? Or can you all please add this?

At this moment I am not expanding the beta to anyone outside my staff because I do not want others cheating our tour systems.

### How do you reproduce this bug?

1. Take off
2. Land at a field that isn't the destination in the bid

### Expected behavior

Log entry that says "On the ground 667 nm from the planned arrival airfield"

### Screenshots

N/A

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by turbofandude** [comment]
This is actually possible with the current config! Please try adding this logger config:

```json
{
      "condition": "{phase} equals 'LANDED' and {milesToGo} greater_than 10",
      "message": "On ground {milesToGo} from planned arrival airport"
    }
```

**Comment by turbofandude** [comment]
Just wanted to follow up - I tested this myself and it does work. This is now standard in the default tracking config.

**Comment by walkerairtrans** [comment]
> Just wanted to follow up - I tested this myself and it does work. This is now standard in the default tracking config.

Worked like a charm!
