### ISSUE TITLE
[FEATURE] - UI Sidebar Menu Scrolling

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#192]
### Describe the bug

The UI sidebar for scrolling with plugins makes both icon containers create scrolls, when I was only expecting the top menu container to be scrollable.

https://cdn.discordapp.com/attachments/1098978689728921670/1108473099260792832/image.png

### How do you reproduce this bug?

Resize the window to create the scrolling.

### Expected behavior

I was only expecting the top container to be scrollable. The bottom container I was expecting both the plugins and settings icons to show at all times. 

### Operating system

Windows 11 Latest

### Community airline

Any

### smartCARS Version

0.9.0

### Plugins installed

all currently available plugins

### Additional context

Use min-height or set the height statically on the bottom container so that the plugins and settings icons are not scrollable like the linked image.

**Comment by BossOfGames** [comment]
**Long Term Suggestion**
Remove the plugins menu outright and combine it with the Settings window. Then, make a Discord inspired settings system with a tree view, with Plugins and Application settings at the top of the tree, then each plugin that needs settings a tree item.

**Comment by turbofandude** [comment]
We have changed this so that the bottom icons no longer scroll. Thank you for the suggestion!
