### ISSUE TITLE
[BUG] - Settings page causes primary content to scroll

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#193]
### Describe the bug

When the window is too small, the settings page causes the primary content (including JSR player) to scroll.

### How do you reproduce this bug?

Navigate to settings page, reduce size of window

### Operating system

Windows 11

### Community airline

SCDC

### smartCARS Version

0.9.1.2

### Plugins installed

n/a

**Comment by GenericNerd** [comment]
This will be fixed on 0.10.0
