### ISSUE TITLE
[FEATURE] - fly button becomes 'in flight'

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#194]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Is it possible to make the fly button say “in flight” for the active bid tracking. And can the other remaining bids (if they exist) are disabled/greyed out?

Just a QOL thing. 

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by Thien42** [comment]
Will be added in the next release
