### ISSUE TITLE
[FEATURE] - Add Website URL and Support URL to plugin.json

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#195]
### Is your feature request related to a problem? Please describe.

I feel that the Organization value is very limiting when it comes to the implementation within the plugin.json file, after seeing the rest of the UI in action with custom authored plugins.

### Describe the solution you'd like

Change the plugin.json schema to the following.
```json
{
    "id": "com.example.pluginname",
    "name": "Plugin Name",
    "organization": {
        "name": "Organization Name",
        "website_url": "https://myorgwebsite.com",
        "support_url": "https://github.com/myorg/plugin/issues"
    },
    "allowedCommunities": []
    "version": "0.0.1",
    "type": "user",
    "description": "An example plugin",
    "availableSettings": {
        "some_setting": {
            "name": "Enable some feature?",
            "description": "Do you want to have this feature do its tasks?",
            "type": "boolean",
            "default": false
        }
    }
}
```
Make the `support_url` optional. Fallback to `website_url` for uses in UI if undefined.

### Describe alternatives you've considered

I not considered additional ways to implement this.

### Additional context

When Viewing the "Have a problem with this plugin?" modal. I realized that the line at the top regarding technical trouble, there's no information to direct the user to that org's specific support portal. This can cause issues with users trying to reach out for support for 3rd party plugins, where they might contact TFDi first, before they're redirected to the right spot.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/992bdf6c-59e4-4401-9f25-18df37c73f16)

In addition, I feel that there should be a "Author Website" link, in the UI next to the plugin.

**Comment by GenericNerd** [comment]
I really like this suggestion! I think you're right that people may contact TFDi Design first before the plugin creator.

We will slightly modify the configuration of `organization` to the following:
```javascript
"organization": {
    "name": "TFDi Design",
    "website": "https://tfdidesign.com/",
    "help": "https://support.tfdidesign.com/"
}
```

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
