### ISSUE TITLE
[FEATURE] - Flying X-Plane 8

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#196]
### Is your feature request related to a problem? Please describe.

Yes, it appears that LR is reporting both XP11 and XP12 as X-Plane 8 in their dataref's (no idea why....) When you fire up the ACARS it says "Using X-Plane 8"

### Describe the solution you'd like

Can you just remove the 8 and let it simply say "Using X-Plane"? It would cut down on the tickets/noise VA's get when their pilots see that.

### Describe alternatives you've considered

I thought about making a log event for each simulator, and the one for X-Plane just saying "If it equals X-Plane 8, just write X-Plane" but then I figure you all can do it quicker/cleaner maybe? And then people could just have 1 line for "simulator used".

### Additional context

N/A

**Comment by walkerairtrans** [comment]
Here's a quick and dirty fix for now if people don't want X-Plane 8 or Prepar3D (x64) showing. :)

> {
	  "condition": "{simulatorVersion} equals 'X-Plane 8'",
	  "message": "Using X-Plane"
	},
	{
	  "condition": "{simulatorVersion} equals 'Microsoft Flight Simulator'",
	  "message": "Using Microsoft Flight Simulator"
	},
	{
	  "condition": "{simulatorVersion} equals 'Prepar3D (x64)'",
	  "message": "Using Prepar3D"
	}

**Comment by bgiorgio0506** [comment]
Fixed in 0.10.0
