### ISSUE TITLE
[BUG] - VA User Chat Filter Broken?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#197]
### Describe the bug

It appears the user list is wiped when clicking on the VA chat group.

### How do you reproduce this bug?

1. Log in
2. See your pilots in global chat
3. Click on VA chat, user list empties.

### Expected behavior

Users shown online for the VA?

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/80c62407-6849-49b4-aba4-7dfebeb4c2d0)

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/ed1e194f-0649-483b-ad38-a4df7edbe712)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Fixed in 0.10.0
