### ISSUE TITLE
[BUG] - simBrief Settings not added when enabled

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#198]
### Describe the bug

Enabling the simBrief plugin did not immediately add the setting options to the app.

### How do you reproduce this bug?

1. Open the app
2. Install plugin
3. Go to settings and verify no simBrief setting options
4. Close app
5. Re-launch and verify they are there

### Expected behavior

If enabling a plugin with settings, make the settings appear in the settings area.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/8e41545a-a096-4753-8e9a-2dc77eb06959)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Fixed in 0.10.0
