### ISSUE TITLE
[BUG] - Generating a simBrief OFP opens a dialog regarding MS Store app

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#199]
### Describe the bug

When planning a flight with the plugin, the following pops up.

### How do you reproduce this bug?

1. Plan a flight.

### Expected behavior

Perhaps try using the system browser?

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/8d9191cd-42d7-41c9-8b83-6221d7af8827)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Opening in the system browser isn't an option due to the data needing to be passed back to smartCARS, but this certainly shouldn't be happening

**Comment by GenericNerd** [comment]
Fixed in 0.10.0
