### ISSUE TITLE
[FEATURE] - Provide feedback to user when pending request is fired

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#20]
**Is your feature request related to a problem? Please describe.**
The user has no visual representation of pending requests

**Describe the solution you'd like**
When clicking the refresh button, make the refresh icon spin.

**Describe alternatives you've considered**

**Additional context**
Screenshot for reference
![image](https://user-images.githubusercontent.com/67948773/224846626-d94cb427-9b3a-4cb8-aeda-c0387140b60e.png)

**Comment by turbofandude** [comment]
Fixed in 0.5.7
