### ISSUE TITLE
[FEATURE] - Changing Online Network while in Flight

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#201]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

You mentioned adding the ability to change/modify your online network when in active flight tracking--doesn't appear that was implemented when it was enabled on the bidding screen. Can we get that? Sometimes people forget....

### Describe alternatives you've considered

None.

### Additional context

N/A

**Comment by GenericNerd** [comment]
Related to #216

**Comment by Thien42** [comment]
Will be added in the next release
