### ISSUE TITLE
[BUG] - Stuck in REJECT_TAKE_OFF entire flight

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#202]
### Describe the bug

Had a rejected take off, taxi back around, and then took off.
The phase got stuck in "REJECT_TAKE_OFF" and never indicated take off, climb, cruise, descent, approach, final, or landing.
As a result, the end flight button never appeared.

**Here is the CSV of the position reports.**
[acars_position.csv](https://github.com/invernyx/smartcars-3-bugs/files/11530336/acars_position.csv)

**Here is the log from the ACARS.**
> 5/21/2023 7:16:29 PM    Using Microsoft Flight Simulator
5/21/2023 7:16:29 PM    Flying PMDG 737-700BBJ McLaren Formula 1 Team
5/21/2023 7:16:29 PM    Now boarding
5/21/2023 7:44:08 PM    Paused
5/21/2023 7:45:57 PM    Unpaused
5/21/2023 7:46:02 PM    Flaps set to 0%
5/21/2023 7:49:12 PM    Engine 2 On
5/21/2023 7:49:31 PM    Engine 1 On
5/21/2023 7:49:36 PM    Flaps set to 38%
5/21/2023 7:49:38 PM    Flaps set to 0%
5/21/2023 7:49:42 PM    Flaps set to 13%
5/21/2023 7:49:50 PM    Flaps set to 25%
5/21/2023 7:49:54 PM    Flaps set to 38%
5/21/2023 7:50:41 PM    Pushing back
5/21/2023 7:50:47 PM    Taxiing out
5/21/2023 7:53:39 PM    Taking off with 16909 lbs of fuel
5/21/2023 7:56:02 PM    Gear lever raised
5/21/2023 7:57:16 PM    Flaps set to 25%
5/21/2023 7:57:19 PM    Flaps set to 13%
5/21/2023 7:57:27 PM    Flaps set to 0%
5/21/2023 9:31:25 PM    Paused
5/21/2023 9:31:51 PM    Unpaused
5/21/2023 9:35:20 PM    Paused
5/21/2023 9:35:31 PM    Unpaused
5/21/2023 9:39:14 PM    Flaps set to 13%
5/21/2023 9:42:53 PM    Gear lever lowered
5/21/2023 9:51:51 PM    Engine 1 Off
5/21/2023 9:51:52 PM    Engine 2 Of

**Here is the additional logs from the app.**
[logs.zip](https://github.com/invernyx/smartcars-3-bugs/files/11530339/logs.zip)

### How do you reproduce this bug?

1. Attempt to take off, then cancel the take off and reject the takeoff.
2. Attempt to take off again after taxiing back.
3. Phase never leaves REJECT_TAKE_OFF

### Expected behavior

Should return to clean state to continue the flight.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.9.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Fixed in 0.10.0
