### ISSUE TITLE
[FEATURE] - Multiple TFDi Users Editing Permissions for a single VA in Central

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#204]
### Is your feature request related to a problem? Please describe.

In many communities, the tech person is not the smartCARS license holder. Therefore, when the tech person needs to make a any changes for the infrastructure, either the tech person has to jump on a screen sharing call with the account holder, or, the account holder's credentials are shared to the tech person, which is obviously super bad practice.

### Describe the solution you'd like

Allow the License holder to designate TFDi accounts, within Central, as managers of the VA, so they can have full control over the VA's parameters (except adding and removing managers, or transferring a license)

### Describe alternatives you've considered

I don't think there's a separate, easier way, than adding a system like above.

### Additional context

This can hypothetically be combined with #203, as it would have the same requirement for multiple TFDi accounts to be associated with a VA. Just this time, you can add standard users, or managers.

**Comment by GenericNerd** [comment]
We are going to be Central to allow a user to add a user by Client ID (this will require a template change on the main website to display their Client ID under "Your Information" in the Client Area)

This will be a simple "on/off" system for sharing the configuration for a VA.

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
