### ISSUE TITLE
[BUG] - https://smartcars.tfdidesign.com/ Returns 403

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#205]
### Describe the bug

When navigating to https://smartcars.tfdidesign.com/, the web server returns 403.

### How do you reproduce this bug?

1. Navigate to https://smartcars.tfdidesign.com/

### Expected behavior

Redirect to https://smartcars.tfdidesign.com/central

### Operating system

N/A

### Community airline

N/A

### smartCARS Version

N/A

### Plugins installed

N/A

**Comment by turbofandude** [comment]
Fixed - thank you!
