### ISSUE TITLE
[BUG] - Charters Not Flyable & Aircraft Not Assigned to Route is Not Flyable (phpVMS 7)

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#206]
### Describe the bug

When a bid is created for a scheduled flight without an aircraft, no aircraft is selectable in the flight center. Therefore, the route is completely unflyable, even for charter flights.

### How do you reproduce this bug?

1. Create a route in phpVMS 7 without aircraft assigned.
2. Bid on the route, either in phpVMS or smartCARS 3.
3. View that the route cannot be flown because of no aircraft assigned.

For Charters
1. Create a charter flight with a assigned aircraft
2. Same result as shown from above.

### Expected behavior

When there's no aircraft available to be flown, there should be an option to allow for the client to make available all the available aircraft in the system to be selectable in the dropdown as a fallback.

This is the default functionality in phpVMS 7 when flights don't have subfleets assigned.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/040dc9d8-0b4d-447a-bea9-c2aa9c696a9e)

Settings used for charter flight.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/9173e91e-e36f-4a13-91f0-ab1d2c48ecb3)

### Operating system

Windows 11

### Community airline

Spark Virtual Airlines

### smartCARS Version

0.10.0

### Plugins installed

chat, map, flight-center, flight-tracker, logbook

### Additional context

This might be a issue that could be solved on the smartCARS API. However, I want to leave it here as this should be a UI fallback on the client as well as fixed on the API. The UI fallback should also have a boolean added to smartCARS Central for enabling fleetwide substitution, just like smartCARS 2.

**Comment by Thien42** [comment]
Will be added in the next release. This will only be a UI fallback for now, as we don't have an easy way to check if the setting is  enabled from the public API

**Comment by BossOfGames** [comment]
> Will be added in the next release. This will only be a UI fallback for now, as we don't have an easy way to check if the setting is enabled from the public API

Wouldn't this be something that can be implemented to check check from the Central API to see if the VA has the setting enabled? Like how you can enable and disable bidding and charters?

**Comment by GenericNerd** [comment]
This is fixed in the next version of the flight center plugin.
