### ISSUE TITLE
[BUG] - Chat Error

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#207]
### Describe the bug

With the latest update 5/22 I get this error when trying to use Chat function - An error occurred while connecting to the chat server.   I did not have problems with the chat before this.

### How do you reproduce this bug?

I get the error every time I try to open the chat now.

### Operating system

Win10

### Community airline

Mirage Executive Charters

### smartCARS Version

current version

### Plugins installed

Flight center, Flight tracking, Logbook, Map, Chat

**Comment by Jishwaah** [comment]
Hi @HondaJet - are you using IPv6? If you type in "What is my IP" into Google, which of the following formats do you see?
![image](https://github.com/invernyx/smartcars-3-bugs/assets/7196643/6998c952-4b98-40f0-82aa-7d3bbfda7197)

**Comment by HondaJet** [comment]
I am on IPv4 Joshua

**Comment by PatLeclerc** [comment]
I also have the same issue with the chat but I'm on IPv6

**Comment by GenericNerd** [comment]
> I also have the same issue with the chat but I'm on IPv6

We currently have an issue with chat in IPv6 - you can track it here: https://status.invernyx.com/

**Comment by jordanhavard** [comment]
@GenericNerd I can see in other VA's the chat seems to work and the status message is gone from  https://status.invernyx.com/ however still not operational when logged into QV, any ideas ? Error logs empty apart from generic start up info

**Comment by GenericNerd** [comment]
> @GenericNerd I can see in other VA's the chat seems to work and the status message is gone from https://status.invernyx.com/ however still not operational when logged into QV, any ideas ? Error logs empty apart from generic start up info

What error message do you see? Have you flushed your DNS?

**Comment by jordanhavard** [comment]
![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/7cf638ea-b0b1-478e-a3ac-574ced672d75)


> I can see in other VA's the chat seems to work. 

I'm able to login to another VA and confirm I can see the chat work for them but if I login to QV, I get the above error

**Comment by GenericNerd** [comment]
Do you have a /pilot/verify endpoint implemented?

**Comment by jordanhavard** [comment]
> 

I do not, assuming this is the issue. Let me check your API and implement and get back to you

**Comment by GenericNerd** [comment]
> I do not, assuming this is the issue. Let me check your API and implement and get back to you

Setting this issue as invalid for now, if adding the verify endpoint doesn't resolve the issue, please mention me and we'll look into this further with you!
