### ISSUE TITLE
[BUG] - Smartcars3 error when opening.

### ISSUE THREAD

**Issue by infinity1233** [invernyx/smartcars-3-bugs#208]
### Describe the bug

After installing/reinstalling, Smartcars gives an error. Saying that it cannot be run with an administrator. This happens when you open it with administrator and also happens when you just double-click it.
![smartcars3_UbgXARS3M8](https://github.com/invernyx/smartcars-3-bugs/assets/54815257/d61829d4-51f5-4d91-97e2-0178ad307184)

### How do you reproduce this bug?

Install smartcars 3

And after it is finnish, click on run.

Then the error shows up.

### Expected behavior

I expected it to run the application.

### Screenshots

![smartcars3_UbgXARS3M8](https://github.com/invernyx/smartcars-3-bugs/assets/54815257/dc0444f5-8445-42b3-8562-66bc35a1b549)

### Operating system

Windows 11

### Community airline

Virtual Cargo International

### smartCARS Version

0.10.0.2

### Plugins installed

none

**Comment by BossOfGames** [comment]
smartCARS shouldn't require the need to be run with Administrator/root permissions. Did you try running the application without Administrator/Root and encountered a issue?

**Comment by infinity1233** [comment]
Yes, even not running with administrator. I get the same error

**Comment by GenericNerd** [comment]
It is likely that you have checked "Run as administrator" - or it is checked for you. You can disable it here: 
https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-stop-a-program-from-running-as/c81b0dd0-956d-4133-aade-076b28adf539

**Comment by infinity1233** [comment]
I checked that. and it wasn't checked. It was already disabled.

**Comment by GenericNerd** [comment]
Can you send us a video of you opening your smartCARS?

**Comment by infinity1233** [comment]
https://github.com/invernyx/smartcars-3-bugs/assets/54815257/1431bbcf-efa8-4acd-95bc-b6c87b81d5b0

**Comment by GenericNerd** [comment]
Do you have UAC (User Account Control) disabled?

**Comment by infinity1233** [comment]
yes

**Comment by GenericNerd** [comment]
If you re-enable UAC, does this issue still happens?

**Comment by infinity1233** [comment]
Does that require a restart?

**Comment by BossOfGames** [comment]
> Does that require a restart?

IT should not require a restart. That being said, restarting the computer isn't a bad idea to do when you make certain changes.

**Comment by BossOfGames** [comment]
Did you change the default installation directory by any chance?
