### ISSUE TITLE
[BUG] - Light Mode Logo used on Dark Mode Loading Screen

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#209]
### Describe the bug

When Dark mode is enabled, the light mode logo is used on the loading screen after the VA login, instead of the dark mode variation.

### How do you reproduce this bug?

Login to a VA with dark mode enabled

### Expected behavior

Use the light mode logo. In the picture provided below, the logo should be the all white version that was uploaded to Central.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/974130f0-f337-40c0-9d69-cc018e99755c)

### Operating system

Windows 11

### Community airline

Spark Virtual Airlines

### smartCARS Version

0.10.0

### Plugins installed

N/A

**Comment by GenericNerd** [comment]
Fixed in 0.10.1.2
