### ISSUE TITLE
[FEATURE] - Prevent multiple request from being fired for API calls

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#21]
**Describe the suggestion**
When clicking `refresh` under `My Flights`, a user can click the refresh button multiple times even with pending requests.

**To Reproduce**
1. Login in to VA
2. Click `My Flights` (1st plane icon)
3. Press the `Refresh` button in quick succession
4. With dev tools open, you can see the multiple request being lined up 

**Expected behavior**
Disable the `Refresh` button until the request fulfills

**Screenshots**
Screenshot of multiple request being lined up
![image](https://user-images.githubusercontent.com/67948773/224847063-1e27c740-43eb-4048-b3d0-2bfb3773fe3b.png)

**Comment by Thien42** [comment]
Fixed in 0.5.8
