### ISSUE TITLE
[BUG] - Flight time counts up even when not moving.

### ISSUE THREAD

**Issue by nintendojezz** [invernyx/smartcars-3-bugs#211]
### Describe the bug

When seleting a bid, there is no log and the Flight time under the Departure Airport Code begins to count up insanely. 
At the end of a 1hr.30min flight, the flight time was something of 29000hrs.

### How do you reproduce this bug?

Select a booking
Press Fly
Wait a couple of seconds

### Expected behavior

The Log should show the aircraft and have a 'Boarding' State.
The flight time should not be counting till wheels are off the ground.

### Screenshots

![Screenshot_38](https://github.com/invernyx/smartcars-3-bugs/assets/19849603/6d6de82d-976b-4f8c-8aed-4f12444ac04b)

### Operating system

Windows 10 22h2

### Community airline

QVirtual

### smartCARS Version

0.10.0

### Plugins installed

Chat, Map, Flight Center, Fligh Tracking, Logbook, Map, Simbrief

**Comment by nintendojezz** [comment]
![image](https://github.com/invernyx/smartcars-3-bugs/assets/19849603/4bd78ba1-341c-47a7-b973-32a16c813eac)

What it looks like in the backend

**Comment by nintendojezz** [comment]
Additional information:
'Time to ARR'does not count down
'NM to go' counts as expected

**Comment by jordanhavard** [comment]
Looks like this is caused by malformed flight logger information. I've fixed it up and it seems to be working now. Potentially some validation on community side is required

**Comment by GenericNerd** [comment]
> Looks like this is caused by malformed flight logger information. I've fixed it up and it seems to be working now. Potentially some validation on community side is required

I'm a little bit confused on what is meant by this. Was this caused by a custom configuration or the default configuration?

**Comment by jordanhavard** [comment]
I copied across @turbofandude suggestion for the engine count fix however copied across the first suggestion where it was "engine count > 1" instead of "engine count greater_than 1" and so while the JSON was a valid JSON, the content of that was incorrect.

**Comment by GenericNerd** [comment]
> > Looks like this is caused by malformed flight logger information. I've fixed it up and it seems to be working now. Potentially some validation on community side is required
> 
> I'm a little bit confused on what is meant by this. Was this caused by a custom configuration or the default configuration?

Ah okay, that makes sense. I wonder if there's something that we can do about that in the backend. Thanks for letting us know though!
