### ISSUE TITLE
[BUG] - Updates still happen when 500 to TFDi but 200 to VA

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#212]
### Describe the bug

When submitting a flight, if submission to the VA was successful but failed to TFDi. The update post request is still made to the VA.

### How do you reproduce this bug?

1. Login with TFDi Design account
2. Login to VA
3. Fly and file flight
4. VA submission files correctly but fails the TFDi submission

### Expected behavior

If VA submission was successful, don't continue submitting POST update requests if TFDI fails

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/6556e63f-7a77-429c-b9ee-e3e040e817c5)

Specific error log relating to this error is
```
"message":"Request failed with status code 500","name":"AxiosError","stack":"AxiosError: Request failed with status code 500\n    at http://localhost:7172/plugins/com.tfdidesign.flight-tracking/static/js/main.a4e1568b.js:2:243683\n    at XMLHttpRequest.d (http://localhost:7172/plugins/com.tfdidesign.flight-tracking/static/js/main.a4e1568b.js:2:243831
```

### Operating system

Windows 10 Pro latest

### Community airline

QVirtual

### smartCARS Version

0.10

### Plugins installed

all except simbreif

### Additional context

Maybe one for the API too if posting a flight update, first check for the BID and if its active before continuing

**Comment by walkerairtrans** [comment]
I'll add on to this that my pilots are seeing increased TFDi submit errors.

Here are logs from one of my pilots. Flight was submitted to us just fine but indicates TFDi error in the toast/log.

[sclogs-230525.zip](https://github.com/invernyx/smartcars-3-bugs/files/11576183/sclogs-230525.zip)

**Comment by GenericNerd** [comment]
Man that 500 is incredibly helpful (/s)! I'll try my best to debug it. Can you provide some more specifics of the flight, or does it happen with any flight you are aware of?

**Comment by jordanhavard** [comment]
To the best of my knowledge, it's happening to any sort of flight where someone is logged into TFDi

**Comment by GenericNerd** [comment]
This has been resolved by the latest flight tracking
