### ISSUE TITLE
[BUG] - CTD, no indicator from ACARS, no further logging or resume

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#213]
### Describe the bug

It appears that there are no notifications if the simulator connection is lost, and no way to resume. I don't think this is going to part of the premium feature as it was standard in the non-premium SC2? I've had pilots test CTD scenarios and FSUIPC shutdown's -- tests in XP11, 12, and MSFS yielded an ACARS that no longer worked.

Logs
[msfs.zip](https://github.com/invernyx/smartcars-3-bugs/files/11576209/msfs.zip)

[xp.zip](https://github.com/invernyx/smartcars-3-bugs/files/11576210/xp.zip)

### How do you reproduce this bug?

1. Start a flight.
2. Start logging.
3. CTD the simulator or shutdown FSUIPC
4. Reconnect everything
5. Try to resume your flight

### Expected behavior

It should notify the user that the simulator has disconnected and provide a way to resume like it did in SC2.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.10.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Closing the app will cause you to lose flight progress (except with smartCARS Premium when that feature becomes available). If you close FSUIPC, you should see a reconnection prompt to retry the connection. What do you see instead of this?

**Comment by walkerairtrans** [comment]
> Closing the app will cause you to lose flight progress (except with smartCARS Premium when that feature becomes available). If you close FSUIPC, you should see a reconnection prompt to retry the connection. What do you see instead of this?

I’m talking about the simulators. As of right now there is no warning. It just sits on flight tracking and continues tracking non-existent data. 

SC2 used to alert you and then it would allow you to reconnect the app if you recovered your simulator.

**Comment by GenericNerd** [comment]
> > Closing the app will cause you to lose flight progress (except with smartCARS Premium when that feature becomes available). If you close FSUIPC, you should see a reconnection prompt to retry the connection. What do you see instead of this?
> 
> I’m talking about the simulators. As of right now there is no warning. It just sits on flight tracking and continues tracking non-existent data.
> 
> SC2 used to alert you and then it would allow you to reconnect the app if you recovered your simulator.

I thought by app you meant smartCARS 3, not the flight simulator you were using.

**Comment by GenericNerd** [comment]
@bgiorgio0506 I'd like you to look into this as a matter of priority.

**Comment by walkerairtrans** [comment]
> > > Closing the app will cause you to lose flight progress (except with smartCARS Premium when that feature becomes available). If you close FSUIPC, you should see a reconnection prompt to retry the connection. What do you see instead of this?
> > 
> > 
> > I’m talking about the simulators. As of right now there is no warning. It just sits on flight tracking and continues tracking non-existent data.
> > SC2 used to alert you and then it would allow you to reconnect the app if you recovered your simulator.
> 
> I thought by app you meant smartCARS 3, not the flight simulator you were using.

Yep. I realized that after I looked at the original bug. I changed the wording to call out the simulator specifically.

**Comment by walkerairtrans** [comment]
Also, one of my pilots who reported this behavior also just said this; "When you cancel a flight after a CTD smartCARS3 doesn't recover and has to be restarted to start the flight over."

**Comment by GenericNerd** [comment]
This will be resolved with the next flight-tracking plugin update.

**Comment by walkerairtrans** [comment]
> 

Will this also resolve this? Just got it in and I can open another ticket if needed.

"User closed his sim after finishing his flight. Forgot to submit the PIREP so he went to the ACARS to do that and it wouldn't go through. App went nuts, stopped working, etc."

This seems very close to what we see when the sim CTD happens. I'm wondering if it's basically all the same--the simulator disconnects and the APP freaks out not knowing what to do.

**Comment by bgiorgio0506** [comment]
yes once the current issue with FSUIPC is fixed this should be resolved
