### ISSUE TITLE
[BUG] - version request spams the network tab

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#214]
### Describe the bug

When viewing dev tools, the `version` request seems to be on an infinite loop of requests. 

### How do you reproduce this bug?

open dev tools on any screen

### Expected behavior

unsure but it doesn't seem right

### Operating system

win 10 latest

### Community airline

any

### smartCARS Version

0.10

### Plugins installed

all except SB

### Additional context

Makes debugging very hard to do

**Comment by GenericNerd** [comment]
This is already fixed in 0.10.1 - thanks for reporting though :)
