### ISSUE TITLE
[BUG] - UI scrolls when width is too small

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#215]
### Describe the bug

A vertical scrollbar appears (as well as a horizontal one) when the UI width is reduced too much.

### How do you reproduce this bug?

- Open the application
- Reduce width

### Expected behavior

Not scroll

### Operating system

Windows 11

### Community airline

SCDC

### smartCARS Version

0.10.0

### Plugins installed

n/a - affects all

**Comment by GenericNerd** [comment]
Fixed in 0.10.1.2
