### ISSUE TITLE
[BUG] - Selecting Flying network not working correctly

### ISSUE THREAD

**Issue by PBCool1** [invernyx/smartcars-3-bugs#216]
### Describe the bug

Sc2 has the option to select what network a pilot is flying on. 
![233864072-897ac85f-c34f-4f71-b6d3-1ac4689d0862](https://github.com/invernyx/smartcars-3-bugs/assets/49513067/c138eb70-024d-4599-9d12-8f196723a359)

It has been added to SC3 also...but it is not noticeable to click on. I found out by discovery that you have to click in the flight information area in order to get the drop down area in order to make the selection. This needs to updated so that looking for the drop down isn't hidden...an obvious click spot is needed. Just like in Sc2...after making a network selection the network should be viewable so that we know it has been selected and working.
![Screenshot_1](https://github.com/invernyx/smartcars-3-bugs/assets/49513067/8615e958-295e-4499-99bd-2e64bacf5ff1)
<img width="1142" alt="Screenshot_5" src="https://github.com/invernyx/smartcars-3-bugs/assets/49513067/370ddbd2-8a46-4b08-8502-adc19c5166e8">

When a network is selected in Sc2 it reports this to my site...ref pic. I would like Sc3 to do the same thing.
![Screenshot_3](https://github.com/invernyx/smartcars-3-bugs/assets/49513067/ce11e3ae-93e4-494a-b2ed-c6f79c281ad7)

### How do you reproduce this bug?

See info above

### Expected behavior

Not having this option hidden. After the selection has been made it needs to be in constant view in either area that I have circled on the tracking page.
![Screenshot_4](https://github.com/invernyx/smartcars-3-bugs/assets/49513067/6a6d518e-8994-4227-ba77-c51fdde9ae80)

### Screenshots

None

### Operating system

Windows 10

### Community airline

UPSVAC

### smartCARS Version

0.10.0

### Plugins installed

Standard plus Simbrief

### Additional context

None

**Comment by GenericNerd** [comment]
Does it always show the incorrect network? Even in the database?

**Comment by GenericNerd** [comment]
Received no reply. Closing this issue for now.
