### ISSUE TITLE
[FEATURE] - Change Flightplan format

### ISSUE THREAD

**Issue by megdun** [invernyx/smartcars-3-bugs#217]
### Is your feature request related to a problem? Please describe.

Allow users to set a default or change Flightplan format

### Describe the solution you'd like

Allow users to change the Simbrief flightplan output to options available on website, perhaps have it default to the VA format if available. IE QFA for QVirtual

### Describe alternatives you've considered

Going to Simbrief or VA Site

### Additional context

.

**Comment by GenericNerd** [comment]
Is this regarding the simBrief plugin? If so, we recommend setting the default flight plan format you'd like to use there. I'm not even entirely sure whether we can control what format the flight plan is generated with

**Comment by megdun** [comment]
Default is already set to zQFA in simbrief but it comes as LIDO in SC3

Sent from my iPhone

On 31 May 2023, at 01:59, GenericNerd ***@***.***> wrote:

﻿

Is this regarding the simBrief plugin? If so, we recommend setting the default flight plan format you'd like to use there. I'm not even entirely sure whether we can control what format the flight plan is generated with

**Comment by BossOfGames** [comment]
> Is this regarding the simBrief plugin? If so, we recommend setting the default flight plan format you'd like to use there. I'm not even entirely sure whether we can control what format the flight plan is generated with

Yes, it's entirely possible to control the OFP format. You need to use the `planformat` field in your request to SimBrief. See: https://developers.navigraph.com/docs/simbrief/using-the-api

**Comment by BossOfGames** [comment]
This would be a perfect use case for settings in both Central and the Client. The VA can determine the OFP settings for all pilots to use in Central, or make it pilot choice. Then the client has the local settings for the user account like it does currently.

**Comment by megdun** [comment]
Unfortunately there is no option to planformat field available
***@***.***

**Comment by BossOfGames** [comment]
@megdun Yes, it's not available in the plugin for you to use. My reply was directed towards @GenericNerd so he, or another developer, can implement it in the plugin.

**Comment by Thien42** [comment]
This will be implemented in the next release
