### ISSUE TITLE
[FEATURE] - Download of Simbrief Plan Data

### ISSUE THREAD

**Issue by megdun** [invernyx/smartcars-3-bugs#218]
### Is your feature request related to a problem? Please describe.

Download of Plan Data from Simbrief

### Describe the solution you'd like

Allow users to download data for different sims/aircraft and pdf as available on simbrief website

### Describe alternatives you've considered

Going to VA or simbrief site

### Additional context

.

**Comment by BossOfGames** [comment]
SimBrief already implements the SimBrief downloader (https://www.simbrief.com/home/index.php?page=fms-downloader). Whenever the FMS Downloader is open, and a SimBrief OFP is created from smartCARS, it should automatically download everything to the right folders for you, even when using smartCARS. Why not use a first-party solution?

If there isn't a link button already, maybe adding a link to view the OFP on https://dispatch.simbrief.com/ might be a solution here.

**Comment by Thien42** [comment]
For different sims and aircraft the Simbrief downloader is definitely the better way to do it, as it is pretty much seamless, but I can add a button to open the PDF that Simbrief generates

**Comment by Thien42** [comment]
Button to open the simbrief plan PDF was added in 0.12.1
