### ISSUE TITLE
[BUG] - Excessive Speed Time Entry and Exit not recorded.

### ISSUE THREAD

**Issue by megdun** [invernyx/smartcars-3-bugs#219]
### Describe the bug

Excessive Speed Time Entry and Exit not recorded when overspeeding below 10,000ft

### How do you reproduce this bug?

Fly >250kts below 10000 ft. 
No Entry or Exit of overspeed recorded

### Expected behavior

Some VA's have criteria where you can't overspeed >3 minutes in duration. This was previously recorded in SC2

### Screenshots

![OS record from SC2](https://github.com/invernyx/smartcars-3-bugs/assets/134753715/88f091c7-d867-4400-bdcc-248903c5de73)
![Screenshot 2023-05-27 125746](https://github.com/invernyx/smartcars-3-bugs/assets/134753715/fc0525a4-8d12-49c7-baca-dda0d552c3a7)

### Operating system

Windows 11

### Community airline

QVirtual

### smartCARS Version

0.10.0

### Plugins installed

Simbrief, Chat, Flight Centre, Flight Tracking, Logbook, MAP

### Additional context

.

**Comment by GenericNerd** [comment]
This is not a bug but specified behaviour by the Virtual Airline configuration of the flight tracking plugin. You can do this by modifying the conditions and output of your flight tracking plugin. You can ask for help in Discord, but this is not a bug.

**Comment by jordanhavard** [comment]
Have posted in discord here https://discord.com/channels/589851727373795331/1110279984074993725/1113338622104567888
