### ISSUE TITLE
[FEATURE] - Display aircraft registration for booking

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#22]
**Is your feature request related to a problem? Please describe.**
Not a problem but more of a nice to have. A user will often confirm they have "booked the correct aircraft" by confirming the aircraft registration in the `My Flights` / `Bookings` screen

**Describe the solution you'd like**
Having the aircraft registration displayed in brackets next to the aircraft type
e.g. `Boeing 737-800 (VH-QFA)`

**Describe alternatives you've considered**
n/a

**Additional context**
SC2 displaying the aircraft registration
![image](https://user-images.githubusercontent.com/67948773/224848013-ff80d464-c184-4e40-bc19-daf1e667d983.png)
SC3 table view not showing registration
![image](https://user-images.githubusercontent.com/67948773/224848047-dd13ec57-a675-43bb-a328-54db3a3cb2e2.png)
When clicking the booking, registration is also not present
![image](https://user-images.githubusercontent.com/67948773/224848097-1217566b-8065-4e77-9225-6aeba707bb2e.png)

**Comment by turbofandude** [comment]
Agreed and resolved in 0.5.7
