### ISSUE TITLE
[BUG] - SC3 not connecting to MSFS. 

### ISSUE THREAD

**Issue by rsh2155** [invernyx/smartcars-3-bugs#221]
### Describe the bug

I have a scenario that has appeared twice. Where SC3 reports it's unable to connect to MSFS. 
FSUIPC is running and connected. 
I can successfully connect SC2. 

When I check the log - it has the following entry: warn: Connecting to FSUIPC failed {"code":16,"name":"FSUIPCError","timestamp":"2023-05-29T00:09:07.026Z"}

I then rebooted. See below - did a single program step by step start. 

### How do you reproduce this bug?

I do start multiple flight related apps at once. Typically - MSFS, SC3, navigraph, volanta, if I'm online vpilot, vatspy. 

I did a controlled start up - loaded MSFS, loaded Fenix A320 at YPPH and when it was started - started SC3 and it did connect straight up. 

Yesterday, I did have to update C++ - but everything this morning using winget upgrade is showing as ok. 

### Expected behavior

Should be able to muti-program start and connect. 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/655de5eb-0050-4f21-b2df-c398c5a0df91)

### Operating system

Win10 Home 22H2. 

### Community airline

QVirtual 

### smartCARS Version

0.10.0

### Plugins installed

chat, Flight Centre, Flight Tracking, Logbook, Map

### Additional context

I will continue to try to prove this theory of one program start v multi.

**Comment by rsh2155** [comment]
OK,. fresh start this morning - started all programs in quick sequence. MSFS last.  Cannot connect. Will reboot and do the one at a time method. 

![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/03015845-fd5f-473e-bf17-567d436d2d90)

**Comment by rsh2155** [comment]
OK, even one program at a time is a problem today. I have cleaned out the text in the common log file. Started SC3 and here is the test - hope this helps the research. 

info: Socket disconnected {"handler":"disconnect","socketId":"bwp-7OI-i7K3EabSAAAB","source":"realTimeAPI","timestamp":"2023-05-30T02:14:24.550Z"}
info: Stopping plugins {"timestamp":"2023-05-30T02:14:24.556Z"}
info: No core update required {"source":"main","timestamp":"2023-05-30T02:14:28.869Z"}
info: Express server running on http://localhost:7172 {"source":"main","timestamp":"2023-05-30T02:14:28.966Z"}
info: Setting current plugin {"handler":"set-current-plugin","plugin":null,"source":"realTimeAPI","timestamp":"2023-05-30T02:14:29.143Z"}
info: Identity updated {"handler":"identity-updated","source":"realTimeAPI","timestamp":"2023-05-30T02:14:33.407Z"}
info: Loading plugins {"timestamp":"2023-05-30T02:14:33.407Z"}
info: Plugin list retrieved from TFDi Design {"timestamp":"2023-05-30T02:14:34.105Z"}
info: Resolving required plugins {"timestamp":"2023-05-30T02:14:34.105Z"}
info: Starting plugins {"timestamp":"2023-05-30T02:14:34.113Z"}
info: Starting com.tfdidesign.chat {"timestamp":"2023-05-30T02:14:34.114Z"}
info: Starting background of com.tfdidesign.chat from C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.chat\background\index.js {"timestamp":"2023-05-30T02:14:34.114Z"}
info: Background of com.tfdidesign.chat at C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.chat\background\index.js loaded {"timestamp":"2023-05-30T02:14:34.164Z"}
info: Starting com.tfdidesign.flight-center {"timestamp":"2023-05-30T02:14:34.168Z"}
info: Starting background of com.tfdidesign.flight-center from C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.flight-center\background\index.js {"timestamp":"2023-05-30T02:14:34.168Z"}
info: Background of com.tfdidesign.flight-center at C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.flight-center\background\index.js loaded {"timestamp":"2023-05-30T02:14:34.189Z"}
info: Starting com.tfdidesign.flight-tracking {"timestamp":"2023-05-30T02:14:34.189Z"}
info: Starting background of com.tfdidesign.flight-tracking from C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.flight-tracking\background\index.js {"timestamp":"2023-05-30T02:14:34.189Z"}
info: Background of com.tfdidesign.flight-tracking at C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.flight-tracking\background\index.js loaded {"timestamp":"2023-05-30T02:14:34.456Z"}
info: Starting com.tfdidesign.logbook {"timestamp":"2023-05-30T02:14:34.460Z"}
info: Starting com.tfdidesign.map {"timestamp":"2023-05-30T02:14:34.460Z"}
info: Starting background of com.tfdidesign.map from C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.map\background\index.js {"timestamp":"2023-05-30T02:14:34.460Z"}
info: Background of com.tfdidesign.map at C:\Users\hutch\AppData\Local\TFDi Design\smartCARS\resources\app\dist\plugins\com.tfdidesign.map\background\index.js loaded {"timestamp":"2023-05-30T02:14:34.474Z"}
info: Chat data bus running on http://localhost:8881 {"timestamp":"2023-05-30T02:14:34.481Z"}
info: Plugins ready {"timestamp":"2023-05-30T02:14:34.485Z"}
info: Setting current plugin {"handler":"set-current-plugin","plugin":"com.tfdidesign.flight-center","source":"realTimeAPI","timestamp":"2023-05-30T02:14:36.337Z"}
warn: Connecting to FSUIPC failed {"code":16,"name":"FSUIPCError","timestamp":"2023-05-30T02:14:40.106Z"}

**Comment by rsh2155** [comment]
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11595103/combined.log)

**Comment by GenericNerd** [comment]
Did you run your simulator or FSUIPC as an administrator? If so, smartCARS will not be able to connect.

**Comment by rsh2155** [comment]
Yes. 
I have tried a variation of both - trying to troubleshoot. SC3 alerts you. 
However there is no end user warning on MSFS as admin. 

So, armed with your feedback, I've connected multiple times this morning. 

Consider a SC3/UX warning on MSFS being not run as Admin when it failed perhaps? 

appreciate the feedback.

**Comment by jordanhavard** [comment]
> Did you run your simulator or FSUIPC as an administrator? If so, smartCARS will not be able to connect.

Maybe the error message can be update to include this as @rsh2155 metioned

**Comment by GenericNerd** [comment]
> > Did you run your simulator or FSUIPC as an administrator? If so, smartCARS will not be able to connect.
> 
> Maybe the error message can be update to include this as @rsh2155 metioned

This has been added in the latest flight tracking
