### ISSUE TITLE
[BUG] - XP UDP Configuration in Central?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#225]
### Describe the bug

I don't believe this should be here?

### How do you reproduce this bug?

Logged into Central and opened up Flight Tracking plugin.

### Expected behavior

N/A

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/7507d037-2170-4c3d-98e2-a1a2a5e62840)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.10.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by BossOfGames** [comment]
I see the same thing.


I suggested a solution for this in a separate issue, in relation to the SimBrief plugin. (https://github.com/invernyx/smartcars-3-bugs/issues/217#issuecomment-1571566601). Long term, I suggest adding a field to the options in the plugin.json file that helps define if the setting is community, user, or both (community default, but can be changed by user).

> This would be a perfect use case for settings in both Central and the Client. The VA can determine the OFP settings for all pilots to use in Central, or make it pilot choice. Then the client has the local settings for the user account like it does currently.

**Comment by Thien42** [comment]
> I see the same thing.
> 
> I suggested a solution for this in a separate issue, in relation to the SimBrief plugin. ([#217 (comment)](https://github.com/invernyx/smartcars-3-bugs/issues/217#issuecomment-1571566601)). Long term, I suggest adding a field to the options in the plugin.json file that helps define if the setting is community, user, or both (community default, but can be changed by user).
> 
> > This would be a perfect use case for settings in both Central and the Client. The VA can determine the OFP settings for all pilots to use in Central, or make it pilot choice. Then the client has the local settings for the user account like it does currently.

We already have this feature, I believe we simply forgot to update central for our latest release

**Comment by GenericNerd** [comment]
Fixed
