### ISSUE TITLE
[BUG] - News panel is missing

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#226]
### Describe the bug

News panel no longer shows on main page. Don't see any errors.

### How do you reproduce this bug?

1. Updated SC3
2. Launch it

### Expected behavior

News panel should show

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/8069a709-859a-49d8-ac6e-83e74b3ae116)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.10.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
This only happens if your news endpoint is not returning valid data. 

What does your /data/news endpoint return?

**Comment by walkerairtrans** [comment]
It returns the news. I didn't realize my SS cut it off.

Did you guys implement any date cut off or anything? Before this version that new entry showed every time.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/a7644c51-26a1-471b-bc1c-13d7159cff98)

**Comment by GenericNerd** [comment]
It seems like the title and postedBy are empty, along with the date being all 0's. Can you provide example data on these fields and let me know if this changes the panel state at all?

**Comment by walkerairtrans** [comment]
> It seems like the title and postedBy are empty, along with the date being all 0's. Can you provide example data on these fields and let me know if this changes the panel state at all?

None of that existed the entire alpha/beta cycle--so whatever update you all did last night you must of enforced those fields.

Once I faked the fields the news block reappeared.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/6fcd9306-80d4-41d0-89c9-fa918b4b213c)

Also, FYI;

> postedAt,
> postedBy,
> title

is not a valid column in phpVMS 5.

Anyone with phpVMS 5 and using this will need to create/rename columns in the DB for this.

Default install behavior for phpVMS 5.
> CREATE TABLE `phpvms_news` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `subject` varchar(30) NOT NULL DEFAULT '',
>   `body` text NOT NULL,
>   `postdate` datetime NOT NULL DEFAULT '1970-01-01 01:01:01',
>   `postedby` varchar(50) NOT NULL DEFAULT '',
>   PRIMARY KEY (`id`)

**Comment by walkerairtrans** [comment]
Closing per comment above.
