### ISSUE TITLE
[BUG] - Cannot Specify Number of Passengers/Actual Aircraft for Flight

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#228]
### Describe the bug

You are not able to specify the number of passengers on board a passenger flight.  You are also not able to specify the actual aircraft flown.  When the flight report is filed it appears that the payload (weight) is used.  This is not correct.

### How do you reproduce this bug?

1.  Bid on a flight.
2.  Fly the flight.
3.  File a flight report.

### Expected behavior

Before beginning the flight, there should be fields available for selecting the actual aircraft being flown and the number of passengers on board.  Should behave similar to SC2, so that the number of passengers cannot exceed the maximum allowed for the actual aircraft.

This will allow flight reports to be accurate and make sense.  It will also correctly calculate the revenue for the flight.

### Screenshots

![SC3-pirep-notes](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/d6744a5e-a884-44a5-afc4-824dd8a97f71)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.10.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map

**Comment by GenericNerd** [comment]
Is this a bug or more of a feature request?

**Comment by bryan737dfw** [comment]
I considered this a bug rather than a feature request, since these were items that you could specify in SC2.

1. Our VA allows you to use any suitable aircraft on any scheduled flight.  So, for example, if a scheduled aircraft for a flight was a A319, a user might use an A320, B737-800, etc. for the actual flight.
2. Being able to specify the actual aircraft being flown reduces the number of "charter" flights pilots create just based on an aircraft difference.
3. The actual aircraft drives the maximum number of passengers that can be on board the flight.
4. The number of passengers drives the revenue earned for the flight (passenger load * ticket price).
5. The number currently used/sent by SC3 looks to be some weight which is not the passenger load for the flight.
6. On the flight map, it shows the aircraft the user is "flying".  This is incorrect when the actual aircraft type is different than the scheduled.  For example, my last flight showed I was flying an E175 when I was really flying a 737-700.

**Comment by Osviel02** [comment]
I am getting this same error any suggestions

**Comment by GenericNerd** [comment]
This will be fixed in the next version of the API
