### ISSUE TITLE
[BUG] - Flight Time is Logged Rather Than Block Time

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#229]
### Describe the bug

When filing a flight report the logged time represents the flight (air) time rather than the block (gate to gate) time.  This causes pilots to not receive proper credit for all hours in command of the flight.

### How do you reproduce this bug?

1. Fly a flight.
2. File report.

### Expected behavior

The block time (gate to gate/out to in) should be logged.  Or there should be a configurable option for which time to log.

### Screenshots

This shows the OOOI times for the flight:
![SC3-block-times](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/2c00f26a-86c7-41a3-bf0a-3dd3fcdd24a2)

Can see that the flight time was logged:
![SC3-pirep-notes](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/1fe2fa02-9dd1-40ea-a55d-108fc8bdf637)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.10.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map

**Comment by dcherrie** [comment]
I would say that **AIR TIME** should be what is displayed in smartCARS same as SC2 and counts up, not block time. Pilots get paid for being on the ground, but its the air time that goes in their log.

15:15 flight was actually an air time of 14:53 which is confusing cause I use that time to compare to simbrief flight duration and realised the 22 minute different because I started the clock on-board.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/22925698/4e440e59-b135-4569-bae8-f58b0ea55377)

**Comment by Thien42** [comment]
The behavior is intentional, because otherwise as @dcherrie mentioned the time spent on the ground would be counted towards the pilots stats which is also not right

**Comment by dcherrie** [comment]
> The behavior is intentional, because otherwise as @dcherrie mentioned the time spent on the ground would be counted towards the pilots stats which is also not right

@Thien42 is it intentional for this to count upwards from when the application and started tracking rather than from pushback or takeoff?

<img width="358" alt="image" src="https://github.com/invernyx/smartcars-3-bugs/assets/22925698/7e9b0483-3612-4332-b2dd-8ebfe69710b8">

**Comment by Thien42** [comment]
> > The behavior is intentional, because otherwise as @dcherrie mentioned the time spent on the ground would be counted towards the pilots stats which is also not right
> 
> @Thien42 is it intentional for this to count upwards from when the application and started tracking rather than from pushback or takeoff?
> 
> <img alt="image" width="358" src="https://user-images.githubusercontent.com/22925698/242853748-7e9b0483-3612-4332-b2dd-8ebfe69710b8.png">

Yes

**Comment by dcherrie** [comment]
> > > The behavior is intentional, because otherwise as @dcherrie mentioned the time spent on the ground would be counted towards the pilots stats which is also not right
> > 
> > 
> > @Thien42 is it intentional for this to count upwards from when the application and started tracking rather than from pushback or takeoff?
> > <img alt="image" width="358" src="https://user-images.githubusercontent.com/22925698/242853748-7e9b0483-3612-4332-b2dd-8ebfe69710b8.png">
> 
> Yes

So for example, I've started my tracker earlier in my turn-around and it currently says 25 minutes before I've even pushed back and when my actual off-block time from simbrief is still 15 minutes away. 

This count isn't really relevant if it doesn't show air time or pushback time but only shows when you started the tracker. A few of our VA pilots have already complained that their flight time in our system isn't what smartCARS says and thinks we are short changing them.

**Comment by jordanhavard** [comment]
Perhaps this can be an option in Central that will allow VAs to display it as 
- Application start to flight end (what it currently is)
- Pushback to end of flight (what I would consider appropiate for 9/10 VAs)
- take off to landing (would be ideal for us)

**Comment by bryan737dfw** [comment]
Our VA (and I believe many other VAs) credit block time (off the gate to on the gate) for pilot flight reports.  

I was specifically thinking of what was on the filed report, but agree with others that in SC3 the elapsed time should also reflect the block time... I think that is what it does in SC2.  (I'll pay more attention to what I see within the SC3 client during my next flight)

Maybe capture all four OOOI times and then have an option for the VA to specify if they wish to log "out" to "in" (block) -or- "off" to "on" (air) on the filed PIREP.

**Comment by dcherrie** [comment]
> Our VA (and I believe many other VAs) credit block time (off the gate to on the gate) for pilot flight reports.
> 
> I was specifically thinking of what was on the filed report, but agree with others that in SC3 the elapsed time should also reflect the block time... I think that is what it does in SC2. (I'll pay more attention to what I see within the SC3 client during my next flight)
> 
> Maybe capture all four OOOI times and then have an option for the VA to specify if they wish to log "out" to "in" (block) -or- "off" to "on" (air) on the filed PIREP.

Current SC2 timer shows air time.

**Comment by bryan737dfw** [comment]
In relation to what gets logged when **filing** the flight report...

SC2 Log (PIREP):
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/8ad31b26-fd7f-4ef5-8ed0-0c456c943d9f)

External logging program:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/c8955cdd-a0fa-415d-9f02-11ec32668305)

SC2 is logging the block time for the PIREP.  Although technically, in SC2 it logged from start of pushback until the aircraft ground speed got to 0 or 1kts after landing.

**Comment by dcherrie** [comment]
> In relation to what gets logged when **filing** the flight report...
> 
> SC2 Log (PIREP): ![image](https://user-images.githubusercontent.com/74014089/242933074-8ad31b26-fd7f-4ef5-8ed0-0c456c943d9f.png)
> 
> External logging program: ![image](https://user-images.githubusercontent.com/74014089/242932609-c8955cdd-a0fa-415d-9f02-11ec32668305.png)
> 
> SC2 is logging the block time for the PIREP. Although technically, in SC2 it logged from start of pushback until the aircraft ground speed got to 0 or 1kts after landing.

Ahh, sorry. You have taxi time to be included in your VA SC2. We don't have that option enabled in our VA.

**Comment by FartherBranch55** [comment]
Just for clarification, I am the holder of a commercial pilot license in Australia and we always log time when the aircraft is started and moving, including run up and taxi time, because as soon as you start moving you are commanding the aircraft and so is logged as flight time. So for me to have the option in flight center to use block time would be welcome.

**Comment by GenericNerd** [comment]
This is a tough one because per phpVMS, the input is "Flight Time" as indicated in the original issue. This to us means air time, from takeoff to touchdown. If phpVMS indicated "Block Time" I'd immediately agree. As this is not the case, I do not believe this is a bug, but instead intentional behaviour.

I think @jordanhavard may have the best approach to this issue and we may want to look into providing a setting as part of the flight tracking plugin. For the sake of keeping this issue scoped, we recommend that someone creates a suggestion for this feature.

**Comment by bryan737dfw** [comment]
I am very disappointed that this was the decision, but do hope that this is given high consideration to be added a "feature".  

These are the definitions of block, flight, and air time of which I am aware:

Flight time or block time is an aviation term referring to the total amount of time spent piloting aircraft, and serves as the primary measure of a pilot's experience.  Flight time is defined by ICAO as "the total time from the moment an airplane first moves for the purpose of taking off until the moment it finally comes to rest at the end of the flight", and thus includes time spent taxiing and performing pre-flight checks on the ground, provided the engine is running.  In commercial aviation, this means the time from pushing back at the departure gate to arriving at the destination gate.

Air time is defined as "the time from the moment an aircraft leaves the surface until it comes into contact with the surface at the next point of landing".

**Comment by GenericNerd** [comment]
> Flight time or block time is an aviation term referring to the total amount of time spent piloting aircraft, and serves as the primary measure of a pilot's experience. Flight time is defined by ICAO as "the total time from the moment an airplane first moves for the purpose of taking off until the moment it finally comes to rest at the end of the flight", and thus includes time spent taxiing and performing pre-flight checks on the ground, provided the engine is running. In commercial aviation, this means the time from pushing back at the departure gate to arriving at the destination gate.
> 
> Air time is defined as "the time from the moment an aircraft leaves the surface until it comes into contact with the surface at the next point of landing".

I agree with your definition of block time and air time, but flight time isn't a term that is grouped under "Flight Time" per what I could find. A quick Google search shows that there are conflicting responses between air time and block time. For this reason, my original response still stands, but there is now #251 which should hopefully address this in the future.
