### ISSUE TITLE
[BUG] - Accent colours set via SC3 Central don't translate to app

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#23]
**Describe the bug**
The accent colours don't appear to be coming down to the app

**To Reproduce**
1. Login to VA 
2. observe default blue colours

**Expected behavior**
Colours reflect that set in the SC3 central

**Screenshots**
SC3
![image](https://user-images.githubusercontent.com/67948773/224848633-61ed05ff-f2c2-4194-a10d-cc71aa550359.png)
Central
![image](https://user-images.githubusercontent.com/67948773/224848670-3724a8cc-2968-4749-bff0-ab0368adfd50.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: (assume all)
 - Version closed alpha
 - Plugins used: any

**Additional context**

**Comment by GenericNerd** [comment]
We do intend to go to acknowledge the accent colour in a later update

**Comment by turbofandude** [comment]
Agreed and fixed - the colors will be respected as of 0.5.7
