### ISSUE TITLE
[FEATURE] - Settings page declutter

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#234]
### Is your feature request related to a problem? Please describe.

It can be quite hard for context when looking at the settings page (and I imagine this would be multiplied when users start all additional plugins)

### Describe the solution you'd like

I'm no UI/UX designer but maybe accordions or a tabbed system for `Core` settings and then plugin settings could be their own 🤷 

### Describe alternatives you've considered

n/a

### Additional context

screenshot for reference 
![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/8caa707f-d7fd-41e5-9203-a0d5dab112dc)

**Comment by walkerairtrans** [comment]
Or horizontal line separating sections. I was thinking about this last night too.

**Comment by GenericNerd** [comment]
The page is a bit cluttered compared to before as we keep expanding the settings, and the spacing between settings feels very random. I believe the accordion system may be a bit too much for this page, let me explain why:

Typically, settings pages are only accessed a couple of times if the application is designed correctly. I believe we have accomplished an application where you do not need to access the settings page every week or even more. Therefore, I do not think an accordion-type system is appropriate for this case.

**However**, I have gone ahead and applied a little bit of my UI touch to the settings page, which will look like this:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/45597752/80d7c62e-10de-448b-8c95-589ac34f6725)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/45597752/b03a29a5-716b-43e7-bcf8-48bbc51d7e31)

Hopefully, that looks cleaner and easier to use!

**Comment by GenericNerd** [comment]
Will be in the next version
