### ISSUE TITLE
[FEATURE] - WYSIWYG editor for community message

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#236]
### Is your feature request related to a problem? Please describe.

It would be cool to provide a WYSIWYG editor for the `community message` in SC3 Central that would allow ease of editing for end users

### Describe the solution you'd like

Add a WYSIWYG editor 

### Describe alternatives you've considered

n/a

### Additional context

screenshot for reference
![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/4a6e36ba-054b-4257-8508-a8c2c0350633)

**Comment by GenericNerd** [comment]
The welcome message doesn't actually allow any formatting, so the message field is already a WYSIWYG editor in a way. Did you mean something else I'm perhaps not understanding?

**Comment by jordanhavard** [comment]
> so the message field is already a WYSIWYG editor in a way. 

☝️ I see what you did there 👏 

Could the welcome message potentially be changed (down the road sometime) to accept formatting with a WYSIWYG editor attached for the non technical users ?
