### ISSUE TITLE
[BUG] - Can't select an online network after pulling flight from Simbrief

### ISSUE THREAD

**Issue by BluesmanEP** [invernyx/smartcars-3-bugs#237]
### Describe the bug

Using the Simbrief plugin, after clicking the "Retrieve my latest Simbrief Flight Plan" button, the option to select an online network is not available.  There's no way to choose VATSIM, PE etc. after you pull the flight from Simbrief. 

### How do you reproduce this bug?

Click on a flight in the My Flights list.

Click the "Plan with Simbrief" button.

Click the "Retrieve my latest Simbrief Flight Plan" button.

After loading the only options are to click a pre-file button, or to fly.  There's no option to select an online client to report back to the VA.

### Expected behavior

Should be able to choose an online client after Simbrief import, just as you can when clicking on a non-Simbrief flight.

### Operating system

Windows 11

### Community airline

Virtual Cargo International

### smartCARS Version

0.10.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, Simbrief

**Comment by GenericNerd** [comment]
@Thien42 Is there anything we can do about this?

**Comment by Thien42** [comment]
Sorry for the long delay, this issue will be fixed in the next release
