### ISSUE TITLE
[BUG] - User plugins do not show author or last updated

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#238]
### Describe the bug

User plugins do not show the author or last updated in the plugins screen when installed.

### How do you reproduce this bug?

1. Download a user plugin (like simBrief)
2. View your current plugins

### Expected behavior

The author and last updated time should be available.

### Operating system

EndeavourOS Linux x86_64

### Community airline

smartCARS Development Center

### smartCARS Version

0.10.1.2

### Plugins installed

simbrief

**Comment by Thien42** [comment]
This only happens when running with `--local` since we are not making requests to central and can't check the plugin author.
We could add an author field in the plugin.json to fix this issue but I'm not sure if it's worth the effort

**Comment by GenericNerd** [comment]
Not reproducible in original conditions
