### ISSUE TITLE
[FEATURE] - Request for Flight Center plugin option to allow selection of aircraft

### ISSUE THREAD

**Issue by FlyUVA-CEO** [invernyx/smartcars-3-bugs#239]
### Is your feature request related to a problem? Please describe.

Yes and no - Our VA currently has no aircraft ranking restrictions and we allow pilots to bid any flight and fly that flight with any aircraft that's capable and legal to fly it, so they are able to sub out the aircraft after bidding any flight.  In SC2, they were able to change their aircraft before starting the flight.  In SC3, it selects the aircraft type for you and only allows you to change it "if there is no aircraft available in your fleet" with the new update that was just posted.

### Describe the solution you'd like

We would like an option for pilots to be able to select their own aircraft from our fleet list.  Currently, it appears that SC3 auto selects their aircraft for them and there is no option to disable this to my knowledge.  We would like there to be an option to either disable auto selection of aircraft or allow all pilots to select their own aircraft from our fleet list as they were able to do with SC2.  Thank you!!

### Describe alternatives you've considered

None that we can think of that would make sense.  The only think I was thinking is if we played around with the database to trick SC3 into thinking there were no available aircraft so all pilots would be able to select their own aircraft, however, this will break our SC2 aircraft selection we believe.  I cant think of anything else that would work to make this work with both SC2 and SC3 atm unless we made a hard switch over to SC3.  (which we plan to do in the future, after full market release version is available).

### Additional context

![image](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/4353b15e-f86b-452f-882b-1b3db1389b98)
![image2](https://github.com/invernyx/smartcars-3-bugs/assets/135364884/dec07d0b-35b4-4f62-9c77-fa715b710217)

**Comment by GenericNerd** [comment]
Are you using phpVMS 5 or 7?

**Comment by FlyUVA-CEO** [comment]
> Are you using phpVMS 5 or 7?

Hey!  We are using v5 for now.

**Comment by Thien42** [comment]
This will be implemented in the next release
