### ISSUE TITLE
[BUG] - Duplicate icon for `Flight Tracking` and `My Flights`

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#24]
**Is your feature request related to a problem? Please describe.**
As a user, its hard to visually identify where these pages would take you

**Describe the solution you'd like**
A different icon that represents the pages

**Describe alternatives you've considered**

**Additional context**
Screenshot for context
Top plane icon is `My Flights`
Bottom icon is `Flight Tracking`
![image](https://user-images.githubusercontent.com/67948773/224849143-ee49cb1d-660d-448f-867f-d6efb6d0cd12.png)

**Comment by GenericNerd** [comment]
Known bug, we are working on it :)

**Comment by GenericNerd** [comment]
Fixed in the next release
