### ISSUE TITLE
[BUG] - Xplane 11 crash on client connect

### ISSUE THREAD

**Issue by JamesF0790** [invernyx/smartcars-3-bugs#240]
### Describe the bug

After the new update my sim is crashing immediately upon trying to connect SC3 to it. I hit fly and the game crashes with the error message "You requested a data inet output that is greater than the max!" This wasn't a problem before the new update.

### How do you reproduce this bug?

1. Start a flight
2. Go to the "My Flights" section
3. Select "Fly" on flight.

### Expected behavior

It should be connecting to the sim and not crashing.

### Operating system

Windows 10

### Community airline

QVirtual

### smartCARS Version

0.10.1

### Plugins installed

chat, flight center, logbook, flight tracking, map, simbrief

**Comment by Thien42** [comment]
I assume you are using the x-plane tracking with UDP and not xpuipc ?

**Comment by JamesF0790** [comment]
I hadn't changed it from XPUIPC but cycling it between the two seems to have solved it and I've verified that when trying to connect set on "X-Plane" for the UDP it does repeat the same crash message.

**Comment by GenericNerd** [comment]
Can you provide your combined.log for this issue? You can find it at %localappdata%\TFDi Design\smartCARS\logs.

**Comment by Thien42** [comment]
I managed to find and fix the problem, will be fixed in the next update
