### ISSUE TITLE
[BUG] - Unable to Fetch Errors

### ISSUE THREAD

**Issue by 3791eidde** [invernyx/smartcars-3-bugs#242]
### Describe the bug

There are several bugs. 
Front page - Could not fetch pilots statistics. My name, rank, pilot ID do show. Missing Hours, flights, and landing rate, they show up as 0 for each. Avatar is also not showing correctly from my phpVMS. v7
My Flights tab. Failed to get bid flights, Failed to fetch airports, failed to fetch aircraft
Logbook tab. Failed to search PIREPS.

Per the ? button I am on Version 0.10.1

### How do you reproduce this bug?

1. Navigate to each of the tabs as I described above.

### Screenshots

![sc3-c](https://github.com/invernyx/smartcars-3-bugs/assets/51146693/f3a5b541-3e3b-4042-85d8-baa41db4110a)

![SM3](https://github.com/invernyx/smartcars-3-bugs/assets/51146693/45a58e9c-6f36-47e8-b6e8-adf3e7701dc0)

### Operating system

Windows 11

### Community airline

Alaska Adventures

### smartCARS Version

Version 0.10.1

### Plugins installed

chat, map, flight center, logbook

### Additional context

I had this issue from the beginning. I made a ticket, was told that this is a known issue and the next update will fix the issue. Installed update. The update didn't fix the issue. Only halfway fixed the home page. It was blank before. Now it shows with errors described above.

**Comment by GenericNerd** [comment]
This is **not** a smartCARS issue. This is an issue with the API, and it seems like your API is not respecting your Authorization header. You can read more about this here: https://support.tfdidesign.com/a/solutions/articles/62000228997

**Comment by 3791eidde** [comment]
Hello,I have that enabled. # httpd -M|grep authauth_basic_module (shared)authn_core_module (shared)authn_anon_module (shared)authn_file_module (shared)authn_socache_module (shared)authz_core_module (shared)authz_groupfile_module (shared)authz_host_module (shared)authz_user_module (shared) What else can the issue be. Attached are smartCARS 3 logs. Sent from Mail for Windows From: GenericNerdSent: Monday, June 5, 2023 9:45 AMTo: invernyx/smartcars-3-bugsCc: 3791eidde; AuthorSubject: Re: [invernyx/smartcars-3-bugs] [BUG] - Unable to Fetch Errors (Issue #242) This is not a smartCARS issue. This is an issue with the API, and it seems like your API is not respecting your Authorization header. You can read more about this here: https://support.tfdidesign.com/a/solutions/articles/62000228997—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
