### ISSUE TITLE
[BUG] - Pause button and Pause at TOD no longer works

### ISSUE THREAD

**Issue by nintendojezz** [invernyx/smartcars-3-bugs#243]
### Describe the bug

Selecting the Pause at TOD switch at the bottom of the log no longer pauses the sim. We have several pilots reporting the same issue.
Also the Pause button does not pause the sim anymore.

### How do you reproduce this bug?

Start a flight, Click Pause at TOD switch. Find your aircraft in the ocean when you sleep.
or
Start flight, click pause, notice sim is not paused.

### Expected behavior

The sim should be paused and the unpause button should unpause the sim.

### Operating system

Windows 10 22h2

### Community airline

QVirtual

### smartCARS Version

0.10.1

### Plugins installed

Chat, Map, Flight Center, Fligh Tracking, Logbook, Map, Simbrief

**Comment by dCarnage** [comment]
+1

**Comment by walkerairtrans** [comment]
Confirmed as well. I let Fabio and team know in Discord immediately after the app release. They're working hard to restore that functionality.

**Comment by FartherBranch55** [comment]
I can confirm that pause button and pause on TOPD does not work, tried on 2 flights with same flights XP12 did not pause.

**Comment by GenericNerd** [comment]
This will be fixed in the next flight tracking update.
