### ISSUE TITLE
[BUG] - MSFS Plane Crash is not reported in SC3. 

### ISSUE THREAD

**Issue by rsh2155** [invernyx/smartcars-3-bugs#244]
### Describe the bug

When GSX pushback, went a little haywire and pushed me into the Terminal Building, MSFS reported a "collided with an object and caused critical damage to the aircraft". 

SC3 did not report this and simply said "paused". 

### How do you reproduce this bug?

cause a collision. 
observe the MSFS offering to restart or menu. 
observe the SC3 ACARS log. 

### Expected behavior

SC3 should report a "crashed" based scenario. 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/76758389/e3774276-be53-469c-984d-c3ae5b5a143d)

### Operating system

win 10 2h23.

### Community airline

QVirtual

### smartCARS Version

0.10.1

### Plugins installed

chat, flight centre, flight tracking, logbook, map. 

### Additional context

Nil.

**Comment by GenericNerd** [comment]
This isn't a problem we're worried about. Typically, if you've crashed, chances are you aren't at your destination airport, don't have your engines off and are in the deboarding state. This means that you will not be able to submit your PIREP.

In any case, you will need to cancel the flight as you are unable to proceed. For this reason, we won't be fixing or implementing any fixes for this issue.
