### ISSUE TITLE
[FEATURE] - Flight Attendant announcements

### ISSUE THREAD

**Issue by VitoJackson** [invernyx/smartcars-3-bugs#246]
### Is your feature request related to a problem? Please describe.

I miss the possibility of flight attendant announcements from smartCARS 2 (sound packages) in smartCARS3. smartCARS3 is not what it could be and makes it bad with no announcements.

### Describe the solution you'd like

Implementation of the possibility to add individual soundpacks for flight attendant announcements like in smartCARS2.

### Describe alternatives you've considered

There is no alternative smartCARS3 will not be the same without the flight attendant announcements and the program loses functionality

### Additional context

I would be very happy if the option like in smartCARS2 is available again in smartCARS3. With this and the new functions you have a mature product that is fun and enjoyable to work with

**Comment by GenericNerd** [comment]
We will not be including flight attendants or GPWS announcements. We already have our product ([PACX](https://tfdidesign.com/pacx.php)) that provides the desired pilot experience in terms of verbal announcements.

This does not mean that no one can make a plugin that includes this. A developer is free to do this at their discretion, but we will not be including it natively.
