### ISSUE TITLE
[BUG] - Flight Tracking Logger Configuration Won't Save

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#248]
### Describe the bug

Cannot do anything to the logger configuration. Errors out in central when trying to save.

### How do you reproduce this bug?

1. Go to central
2. Make change to flight tracking logger configuration
3. Hit save

### Expected behavior

Should save; started with the latest release.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/66e50644-e148-45af-8325-b81a17ceb2ab)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by jordanhavard** [comment]
Can confirm also having this issue

**Comment by GenericNerd** [comment]
Can you both send us the exact configuration that you're trying to use?

**Comment by walkerairtrans** [comment]
> Can you both send us the exact configuration that you're trying to use?

Sure. I attached a video showing me moving to just 1 simple configuration item and the error. It doesn't matter what is in there. You can add a single letter to a random word on the current config and it'll just error out.

[loggerconfig.txt](https://github.com/invernyx/smartcars-3-bugs/files/11667445/loggerconfig.txt)

https://github.com/invernyx/smartcars-3-bugs/assets/127605985/44a0f4e8-4e5c-4791-87d8-5c11d7567bf3

**Comment by GenericNerd** [comment]
We've found the issue and it is now resolved.
