### ISSUE TITLE
[FEATURE] - Show date in chat timestamps

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#25]
**Describe the suggestion reason**
The timestamps look weird on first glace. Not sure if these are UTC or local format. I sent the message after Colin however the times don't necessarily look accurate.

**Expected behavior**
Potentially display the date or convert the times to the local users timezone or even better something like `4 hours ago`  and when you hover over it displays a tooltip with the exact date time

**Screenshots**
chat for reference
![image](https://user-images.githubusercontent.com/67948773/224849559-158ccaf5-a8e4-432a-abad-aff7d148f126.png)

**Comment by turbofandude** [comment]
Fixed in 0.5.7
