### ISSUE TITLE
[FEATURE] - Capturing of `OOOI` values

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#252]
### Is your feature request related to a problem? Please describe.

It would be cool to capture these values so VAs could use them in either the flight logger configuration or when submitting the flight. 

### Describe the solution you'd like

Have SC3 natively capture the following times
- Off block
- Out Block
- On Block
- In Block

### Describe alternatives you've considered

You could capture these values by looking when the flight pushes back or lands etc however would be a good addition to native parameters. 

### Additional context

More information can be found here [What Does OOOI Mean In Aviation?](https://www.aviationmatters.co/oooi-aviation-meaning/)

**Comment by GenericNerd** [comment]
This is already implemented and just needs to be configured to capture these events. Here are some ideas on how you could capture them:

- Off Block
  - Check when the phase is `PUSH_BACK`
- Out Block
  - Check when the phase is `TAKE_OFF`
- On Block
  - Check when the phase is `LANDED`
- In Block
  - You could check when the phase is `DEBOARDING`, but it may also be preferential to check when all engines 1-4 are off.

You can find out more information for customizing the flight tracking configuration [here](https://docs.invernyx.com/en/smartcars3/flight-tracking-customization)
