### ISSUE TITLE
[BUG] - Logbook Sends POST request, instead of GET Request

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#254]
### Describe the bug

According to the API Documentation, the `/pireps/search` and `/data/airports` are supposed to be accessed by a `GET` request.

Peeking into my server logs, I found that smartCARS was sending `POST` requests to those endpoints instead, which is invalid per the official API documentation.

### How do you reproduce this bug?

Load the logbook and see the `access.log` file on a server.

### Expected behavior

Logbook plugin should be using `GET` requests, per the documentation.

### Screenshots

<img width="1037" alt="Screenshot 2023-06-06 at 21 45 58" src="https://github.com/invernyx/smartcars-3-bugs/assets/2882332/fecfbd2b-7975-4ee7-89a5-f00ce6ce5369">

### Operating system

macOS 13.3.1

### Community airline

Cardinal Horizon Dev

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight-center, flight-tracker, logbook

**Comment by GenericNerd** [comment]
Although this causes no issues in the default API, this will be resolved in the next version of the logbook.
