### ISSUE TITLE
[BUG] - X-Plane 12 CTD took SC3 with it

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#255]
### Describe the bug

XP 12 crashed, followed by SC3.
Using XPUIPC, not UDP.

Log Files
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11678111/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11678115/error.log)

### How do you reproduce this bug?

1. Unsure how to replicate.

### Expected behavior

Would hope that SC3 not go with it -- lot of times we can use autosave features in a plane and/or get the plane back to the last point it was and recover.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/7e4c6867-1c69-4d36-9540-8a847fc27c61)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
This does not seem like a smartCARS 3 specific issue. It is possible that whatever killed X-Plane 12 took smartCARS 3 with it, and according to [this article](https://answers.microsoft.com/en-us/windows/forum/all/error-0xe0000008/b9b63b1b-f5e6-45d6-8f4f-ea492e3eee90), it may be outdated drivers or firmware versions.

For now, I am going to close this issue. If you have taken all those steps and the issue occurs again, do let us know, but if it is not known how to reproduce this issue, we do not know where we can even begin.
