### ISSUE TITLE
[BUG] - Linux/Mac/PC Log Issues with UDP

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#259]
### Describe the bug

All 3 clients are not logging the livery folder name in UDP.

[MAC]
8.6.2023 22:58:52	Flying E-Jets Family E190

[LINUX]
6/8/2023 5:29:58 PM    Flying Diamond DA50 RG by Aerobask

[PC]
6/8/2023 9:08:10 PM | Flying Cessna Skyhawk

Additionally, several planes are just spamming the logs with the following;

> 6/8/2023 9:08:10 PM	Flying Cessna Skyhawk
6/8/2023 9:08:10 PM	Now boarding
6/8/2023 9:08:15 PM	Stalling
6/8/2023 9:08:17 PM	Stall recovered
6/8/2023 9:08:25 PM	Stalling
6/8/2023 9:08:28 PM	Stall recovered
6/8/2023 9:08:33 PM	Stalling
6/8/2023 9:08:35 PM	Stall recovered
6/8/2023 9:08:44 PM	Stalling
6/8/2023 9:08:46 PM	Stall recovered
6/8/2023 9:08:51 PM	Stalling
6/8/2023 9:08:53 PM	Stall recovered
6/8/2023 9:09:02 PM	Stalling
6/8/2023 9:09:04 PM	Stall recovered
6/8/2023 9:09:09 PM	Stalling
6/8/2023 9:09:12 PM	Stall recovered
6/8/2023 9:09:20 PM	Stalling
6/8/2023 9:09:22 PM	Stall recovered
6/8/2023 9:09:27 PM	Stalling
6/8/2023 9:09:30 PM	Stall recovered
6/8/2023 9:09:35 PM	Stalling
6/8/2023 9:09:37 PM	Stall recovered
6/8/2023 9:09:45 PM	Stalling
6/8/2023 9:09:47 PM	Stall recovered
6/8/2023 9:09:53 PM	Stalling
6/8/2023 9:09:55 PM	Stall recovered

------------------

At WAT this is a major issue -- we enforce livery requirements and not having that data logged means our internal checkers for unique ID's fail and reject pilots. This leads me to having to block Linux and MAC users as I do not have the time to reconfigure our automated systems to bypass these users.

I would appreciate if this could be looked a little higher than low?

Thanks all!

### How do you reproduce this bug?

1. Use any client set to UDP

### Expected behavior

The livery name needs to be part of the logged item.

### Screenshots

N/A

### Operating system

Linux and MAC

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by walkerairtrans** [comment]
Just want to provide some additional information that this appears to not be a SIM issue but something with your app. I have been running UDP validations and also testing with another MAC client -- myself and a couple others have been unable to reproduce the missing livery name with clients that are not smartCARS 3. It seems to be something wonky in your client UDP options right now.

Due to this I've had to cancel all Linux and MAC testing, as well as using UDP option in Windows.

Like I said before, we have a livery requirement process and to circumvent it would require a much bigger rewrite. I'd rather you guys fix the problem fully then to go alter all my code.

Thanks!

**Comment by walkerairtrans** [comment]
_Additional information._

Further testing has reproduced "stalling spam" by windmilling on props with wind at the location. This behavior doesn't replicate in PC with XPUIPC, however it does in UDP.

**Comment by Thien42** [comment]
Will be fixed in the next release.
