### ISSUE TITLE
[FEATURE] - Append the airline name in global chat only

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#26]
**Is your feature request related to a problem? Please describe.**
The potential for mass users to be talking in the global chat can make it hard to identify users and what airlines they are from. To help maintain a safe and accountable environment, the users airline name should be appended to the chatname

**Describe the solution you'd like**
Something like `Jordan H. - QVirtual (2066)`

**Describe alternatives you've considered**

**Additional context**
Screenshot for reference
![image](https://user-images.githubusercontent.com/67948773/224850249-be24940b-2334-4620-9da0-852d3a0650ba.png)

**Comment by turbofandude** [comment]
This behavior is achieved by showing the airline/pilot 'code' in chat - I.e. TFDI1, SWA250, WAT100, etc. Your implementation of the API does not seem to be giving the system a pilot code, hence the number only.
