### ISSUE TITLE
[BUG] - Premature Landing when Taking Off

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#260]
### Describe the bug

Premature landing when taking off seems to still occur even though bounce detection was improved.

> [19:51:44] Using Microsoft Flight Simulator
> [19:51:44] Flying Cessna Skyhawk 172Sp G1000 Kenmore Livery
> [19:51:44] Aircraft changed to Cessna Skyhawk 172Sp G1000 Kenmore Livery
> [19:51:44] Engine 1 On
> [19:51:44] Gear lever raised
> [19:51:44] Now boarding
> [19:51:45] Flaps set to 33%
> [19:55:22] Paused
> [19:55:43] Unpaused
> [19:58:13] Pushing back
> [19:58:23] Taxiing out
> [19:58:36] Taking off with 75 kgs of fuel
> [19:58:48] Climbing at 61 kts, 0 degrees pitch, -0 degrees bank, with 75 kgs of fuel
> [19:58:49] Touched down at 0 fpm, 0.9g, 62 kts, true heading 236, -0 degrees pitch, 1 degrees bank, wind 082 at 11 kts, fuel remaining 75 kgs
> [19:58:49] On the ground 100 nm from the planned arrival airfield

FSUIPC7 v7.3.20

### How do you reproduce this bug?

N/A

### Expected behavior

Is there anything we can do to improve and cut out any false landings like this?

### Screenshots

N/A

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Does this happen due to the wheels bouncing? No reproduction steps have been provided.

**Comment by GenericNerd** [comment]
I'm marking this issue as stale for now. Let me know if you find reproducible steps

**Comment by jordanhavard** [comment]
Had a pilot report this. 
They were on a sloped runway 100 in the upwards direction if that helps (maybe they didn't pull back hard enough)
