### ISSUE TITLE
[FEATURE] - Give Plugin Devs Total Count the Communities the plugin is added to

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#263]
### Is your feature request related to a problem? Please describe.

I love metrics. Right now, we do have access to see the download metrics, but I am more curious in a metric to know how many VAs are using the plugin. Right now, the downloads itself doesn't give me the best idea of knowing if a airline plugin is used across many small communities, or a few large communities.

### Describe the solution you'd like

Another table column in the smartCARS Central developer menu to show how many communities the plugin was added to.

### Describe alternatives you've considered

N/A

### Additional context

None

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
