### ISSUE TITLE
[BUG] - Nose up detected as nose down

### ISSUE THREAD

**Issue by cyrus-thedeltavirtual** [invernyx/smartcars-3-bugs#264]
### Describe the bug

SC seems to be incorrectly capturing nose down when you're actually climbing up, and Up when you're descending. This is on Linux and xplane 11.

### How do you reproduce this bug?

1. Launch SC3, 
2. start a flight
3. taxi out and begin climb
4. take a steep angle up 
5. note the log in sc3 - shows nose down
6. now dive deep
7. note the log in sc3 
8. let it crash to end flight just for fun :-) 

### Expected behavior

Should show up if you're pointing up and +ve value for pitch, and -'ve when you're diving 

### Screenshots

6/13/2023 2:38:38 AM Climbing at 74 kts, -8 degrees pitch, -16 degrees bank
6/13/2023 2:38:40 AM Pitch exceeded 10 degrees nose down

### Operating system

Ubuntu

### Community airline

The Delta Virtual

### smartCARS Version

Version 0.11.0

### Plugins installed

chat, track, flight cntr, logbook, map

### Additional context

I was just flying a c172 for a test ride

6/13/2023 3:19:58 AM | Taxiing out
-- | --
6/13/2023 3:19:59 AM | Stall recovered
6/13/2023 3:20:00 AM | Pitch exceeded 10 degrees nose down
6/13/2023 3:20:06 AM | Stalling
6/13/2023 3:20:07 AM | Pitch exceeded 10 degrees nose down
6/13/2023 3:20:07 AM | Climbing at 51 kts, -15 degrees pitch, -3 degrees bank
6/13/2023 3:20:15 AM | Stall recovered

**Comment by walkerairtrans** [comment]
This is likely associated with bug https://github.com/invernyx/smartcars-3-bugs/issues/259 and logger issues.

**Comment by Thien42** [comment]
Will be fixed in the next release
