### ISSUE TITLE
[FEATURE] - Plugin Display Name Specific for Navigation Bar

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#266]
### Is your feature request related to a problem? Please describe.

In the navigation bar on the left hand side, the plugin name currently pulls from the `name` attribute in the `plugin.json`. However, for some plugins, like my series of plugins, I want to use names that would hypothetically conflict with the existing first party plugins. For example, I want my flight center to show up as "Flight Center" on the left navigation panel.

### Describe the solution you'd like

Create a additional attribute in the plugin.json file to allow for a "navigation name" in the navigation menu, so that I could use the name  "Flight Center", instead of "phpVMS 7 Native Flight Center". The real plugin name can be used in the plugins menu and on smartCARS Central, so that it's easier for people to brand their plugins and for VAs to install them properly.

### Describe alternatives you've considered

This does pose a security risk. I would mention that only verified plugins should be able to take on restricted display names in the navigation menu in smartCARS.

If multiple plugins of the same navigation name are installed, then they will revert back to the normal name currently used.

### Additional context

N/A

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
