### ISSUE TITLE
[FEATURE] - Plugin Release Channels

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#267]
### Is your feature request related to a problem? Please describe.

Currently, my plugin has a single stable release channel for the VAs using my plugin to use.

Eventually, once my plugin is stable, I will want to have a beta channel to distribute my plugin through, for if I need to test out a new feature to the API I'm developing, or other reasons for having a beta channel.

### Describe the solution you'd like

Create a channel system in smartCARS Central to allow for separate release channels for separate versions of a plugin.

### Describe alternatives you've considered

I have alternatively thought about uploading a separate plugin with my code change, however that solution becomes very untenable.

Doing so requires different plugin ids. When considering the plugin UI's base URLs all need to be updated, this is the equivalent of forking a entire project into effectively its own plugin, which is very undesirable.

I have considered implementing code within my plugin to allow for "beta features" and have a config option to "enable beta features", however, coding that into the main release adds complexity and increases the chances of bugs coming up, simply by programming around that solution.

### Additional context

My plugins rely on APIs that I may update or release beta versions for, which may not support plugins on the current release channel. This functionality ensures that I can deploy updates to new users on a beta channel, without having to give away private source code, if the plugin isn't open source.

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
