### ISSUE TITLE
[FEATURE] - Plugin Presets in Central

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#268]
### Is your feature request related to a problem? Please describe.

As more commercial off-the-shelf (COTS) web systems like, VAOS, phpVMS, vAMSYS, create plugins to drive the core experience and functionality for smartCARS to work on their system, I have noticed that there's no simple way of telling new license holders of smartCARS which plugins they need to install for their VA system to work best with smartCARS 3.

### Describe the solution you'd like

When a user in smartCARS Central opens up their community editor for the first time, create a first-user workflow to select plugin sets for verified plugins, designated by the creators of the COTS systems, to speed up the first-time setup process and reduce support inquiries.

This could also not be limited for first-time install. I think plugin sets are good when a community intends to migrate between systems, and would like a fresh start.

### Describe alternatives you've considered

User instructions on the docs website of the respective system, however, there's been cases in the real world with my "phpVMS 7 Flight Center", where the VA didn't uninstall the default flight center, thereby causing an issue with pilots, as they forgot to remove the stock flight center.

### Additional context

Maybe force the first-time setup when a community doesn't have any plugins added to their install.

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
