### ISSUE TITLE
[FEATURE] - Plugin Installation Dependencies Pop-Up

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#269]
### Is your feature request related to a problem? Please describe.

When community owners or pilots are browsing plugins, and would like to install a plugin, there's no good method to notify the user that the plugin requires certain dependencies to properly run (eg. install certain web scripts, sign up for a account, etc).

### Describe the solution you'd like

When a plugin states that it has pre-requisite dependencies before installing, a modal should be displayed notifying the user before installing the plugin.

We should be able to define the plugin requirements string via the `plugin.json` file.

### Describe alternatives you've considered

I have considered using the plugin description for this, however, I have a strong feeling that they'll be less inclined to read the description of the plugin for that information.

### Additional context

N/A

**Comment by GenericNerd** [comment]
This is not something we're considering. You as the plugin developer should check whether the plugin you're looking for is installed for your dependency, and if it isn't, you should show an error.
