### ISSUE TITLE
[BUG] - No way to close/remove private conversation

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#27]
**Describe the bug**
When someone clicks `Send user private message` there is no way for that user to then either clear or remove that private conversation from the side panel

**To Reproduce**
1. Login in to VA
2. open chat
3. click Colin
4. Click `Send private message`
5. observe no place to close or remove conversation from side bar

**Expected behavior**
Have some `X` displayed to allow users to remove conversations from side panels. I would assume history would remain if that user was to then open up another chat

**Screenshots**
No `X` button anywhere 
![image](https://user-images.githubusercontent.com/67948773/224850694-8886f413-eafb-4cf9-ab0a-8d984b960be8.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: assumed all
 - Version closed alpha
 - Plugins used: chat

**Additional context**

**Comment by turbofandude** [comment]
Fixed in 0.5.7
