### ISSUE TITLE
[BUG] - My Flights // Bid Data Not Refreshing

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#271]
### Describe the bug

This is an extension of my other reported issue on the refresh button here: https://github.com/invernyx/smartcars-3-bugs/issues/249. There appears to be more problems with My Flights.

Here is my current bookings...
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/7ad4800e-7822-4c6d-b578-66372799f92e)

I accidently clicked on the tour leg flight WAE8182 when I wanted WAX8122. I get "incorrect simulator scenario" because I am not at KHOU, I am at KBOS.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/83873890-3fb4-4a98-a4b0-af80cba45d5c)

My flightplan shows the flight I misclicked--WAE8182.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/47b15bce-455f-4088-b10e-b9bf0b8c059a)

I now return to My Flights to click the RIGHT button, WAX8122. Immediately get "incorrect simulator scenario."
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/8c99f098-8547-46a5-9447-63ee09b88074)

My flightplan is still showing the old flight I misclicked--WAE8182.
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/898d3dc7-a0e0-4acb-9618-83e133953b42)

The only way to get out of this loop is to shut down smartCARS 3 and relaunch, and make sure "I" click the right flight the first time.

Additionally, I tried this for giggles -- I clicked on the WAX8122 KBOS flight and started it. I immediately stopped it and went back to My Flights and clicked on WAE8182 that should be starting from KHOU. I was able to start that flight and this is what update.php was sending to my server. The bidID is the same as WAX8122 but I actually clicked on WAE8182 Fly button.

{"bidID":"581606","uuid":"xRDlw1a5","latitude":"42.358821868896484","longitude":"-71.02159881591797","heading":"210.28961181640625","groundSpeed":"0","altitude":"86","distanceRemaining":"877.6131704229999","phase":"BOARDING","route":[""],"network":"offline","timeRemaining":"0","simVersion":"X-Plane"}

### How do you reproduce this bug?

1. Book two flights (yes, pilots can have _multiple_ bids.)
2. Click the wrong flight, get the incorrect scenario message
3. Go back to My Flights
4. Click the right flight, get the incorrect scenario message
5. Monitor the flightplan fetch and notice it's the the same _wrong_ flight you clicked earlier

### Expected behavior

You need to refresh flightplan with the correct bid object when clicking "Fly".
As I said in my other bug report, you need to also clear it with the refresh button.

### Screenshots

See them above.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by bgiorgio0506** [comment]
this will be fixed in the next update

**Comment by walkerairtrans** [comment]
This has been fixed.
Thank you!!!
