### ISSUE TITLE
[FEATURE] - Launch Actions via URLs

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#272]
### Is your feature request related to a problem? Please describe.

In the phpVMS Code, there are links to vmsACARS which allows for flights to be started/loaded directly from the website.

<img width="880" alt="Screenshot 2023-06-18 at 16 43 19" src="https://github.com/invernyx/smartcars-3-bugs/assets/2882332/32f85d6e-0012-4c32-aded-72423b2ce1ca">

### Describe the solution you'd like

Similarly, I'd like for the ability for smartCARS 3 to parse a URL, like start a flight with flight tracking via `sc3:{communityid}/com.tfdidesign.flight-tracking/startflight?{flightparams}`. This way, we can drive people to the client, from the website.

### Describe alternatives you've considered

I don't think there's alternatives to this type of functionality.

### Additional context

Ideally, I would like to see if this could work on a "cold start" (application closed).

**Comment by GenericNerd** [comment]
We have actually considered this in the past. The problem that I have yet to figure out is:

1. How do we actually go about implementing this?

> _I have done some research on this previously, and I was not able to find what I wanted, which was a system-agnostic solution. I did find some answers for a [Windows specific solution](https://stackoverflow.com/a/38205984), but this does not apply to MacOS or Linux._

> _Upon further research, there is an option for `app.setAsDefaultProtocolClient` which we would likely use._

2. How would we handle a case where the plugin you are linking to does not exist on the user system, e.g. a user plugin?

> _We could present a "plugin not found" error, or something similar, but do we perhaps want to direct the user to download said plugin?_

**Comment by Thien42** [comment]
Closing this for now, we might consider it again in the future
