### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by FartherBranch55** [invernyx/smartcars-3-bugs#273]
### Describe the bug

After latest update simbrief option no longer available in Flight Center

### How do you reproduce this bug?

1. open app
2. go to flight center
3. book a flight
4. simbrief button gone
5. simbrief username not available on setting page in app

### Expected behavior

In "My Flights" page expect to see a simbrief button but it is gone after latest update.

### Screenshots

![Screenshot 2023-06-21 133027](https://github.com/invernyx/smartcars-3-bugs/assets/73376842/e8f50ce4-3e91-4598-8887-c727859ac79b)

### Operating system

Windows 11, 22H2 build 22621.1848

### Community airline

Noble Air

### smartCARS Version

24.4.1

### Plugins installed

chat, map, logbook, flight tracking. flight center

### Additional context

can this be brought back as it is a very useful feature!

**Comment by BossOfGames** [comment]
I am unable to reproduce this bug.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/8949bcb5-e404-4f85-acac-f728e73f9e68)

What flight center version are you running? I'm currently running 0.10.1 to see this behavior.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/c2cbb1bb-c18c-4d94-8df5-996bbd74fc9c)
