### ISSUE TITLE
[BUG] -  Linux - XP12 - Latest Update CTD Random Time, Consistent

### ISSUE THREAD

**Issue by Rastuasi** [invernyx/smartcars-3-bugs#274]
### Describe the bug

X-Plane 12, latest client (0.12.0), at random points throughout flight, I get a CTD via a sim freeze. Doesn't matter location, plane, or such, just take off with a bid and at some point it will CTD. Same flight can then be done without starting Smartcars3 and it will not have issues.

### How do you reproduce this bug?

1. Create bid
2. Load flight
3. Fly
4. CTD

### Expected behavior

Flight would complete without a CTD

### Screenshots

[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11828482/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11828483/error.log)

### Operating system

Manjaro Arch Linux

### Community airline

Walker Air

### smartCARS Version

0.12.0

### Plugins installed

whatever is stock

### Additional context

Using the Aerobask Lancair Legacy, but has been consistent regardless of plane chosen.

**Comment by Rastuasi** [comment]
There have been 2 times now where I was able to land and not get a sim CTD, but then the client never contacted the server upon filing PIREP.  Just sits and spins. Here's additional logs of this happening with the Diamond DA50 from Aerobask.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/17036015/2f26f58d-d9d9-4506-b60b-dd135bd6552f)


[combined_diamond.log](https://github.com/invernyx/smartcars-3-bugs/files/11828564/combined_diamond.log)
[error_diamond.log](https://github.com/invernyx/smartcars-3-bugs/files/11828565/error_diamond.log)

**Comment by Rastuasi** [comment]
In addition, I ran smartcars3 through gdb, this is the output of the diamond flight, but repeated a second time.
[gdb_output_0_12_0_20230621.txt](https://github.com/invernyx/smartcars-3-bugs/files/11828723/gdb_output_0_12_0_20230621.txt)

**Comment by walkerairtrans** [comment]
_For TFDi_
I validated server logs and I see all of his update position reports, but never a packet for complete.
All other pilots are submitting flights in SC3 without issue using the PC client.

**Comment by Rastuasi** [comment]
Did a fresh download of plugin, just to see, but now it won't even let me log in due to the error:

`error: Failed to login to VA {"data":"Invalid type for username (expected `string` [Raw Type: `boolean`])","timestamp":"2023-06-29T03:15:23.081Z"}
error: Failed to login to VA {"data":"Invalid type for username (expected `string` [Raw Type: `boolean`])","timestamp":"2023-06-29T03:15:37.194Z"}`

Seems like the Linux client has some major issues around type casting based on these and the previous logs.

[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11901698/combined.log)
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11901699/error.log)

**Comment by Thien42** [comment]
I can't reproduce the login error. @walkerairtrans can you confirm that you are using the latest public API scripts?
I will try to see if I can reproduce the crashes

**Comment by GenericNerd** [comment]
I've got a couple of questions regarding your setup. Are you running this through Wine (or some other compatibility layer) with a different version or are you running the Linux version (through `./smartcars3`)?

If you're running Linux, the crashes are likely not related to smartCARS 3. Are you running an Nvidia GPU? If so, have you recently updated the graphics drivers? Nvidea is known to have some... questionable stability on Linux from my last experience (especially on Manjaro which can have some outdated drivers and updates at times).

Furthermore, I have never seen the API send boolean values to login, and I was the developer in charge of the API. This indicates something extremely strange is occuring with your specific install. If you could elaborate on your install and other things that you have done with your Linux install, we can dig a bit deeper and see what we can do.-

**Comment by walkerairtrans** [comment]
> I can't reproduce the login error. @walkerairtrans can you confirm that you are using the latest public API scripts? I will try to see if I can reproduce the crashes

I cleared his log-in issue by wiping his sessions -- though the error about his username string is still present int he log.

**Comment by Rastuasi** [comment]
The connection issue was corrected per @walkerairtrans .

But the weird output in the logs persists.

`I've got a couple of questions regarding your setup. Are you running this through Wine (or some other compatibility layer) with a different version or are you running the Linux version (through ./smartcars3)?`

Running the linux version, but if you call ./smartcars3, you will not get a working application. I have to run it as: ./"smartCARS 3"

`If you're running Linux, the crashes are likely not related to smartCARS 3. Are you running an Nvidia GPU? If so, have you recently updated the graphics drivers? Nvidea is known to have some... questionable stability on Linux from my last experience (especially on Manjaro which can have some outdated drivers and updates at times).`

Yes Nvidia 3070, but another system has AMD, latest drivers, issue persists across Manjaro, Debian and my self created kernel. So issues are unrelated to GPU, OS or setup. Also, your statement on Nvidia is historically incorrect. AMD has caused more issues since the 90s than Nvidia has. Nvidia rarely causes me any issues, but AMD has constant texture issues within various API logic and they rarely fix them.
 
`Furthermore, I have never seen the API send boolean values to login, and I was the developer in charge of the API. This indicates something extremely strange is occuring with your specific install. If you could elaborate on your install and other things that you have done with your Linux install, we can dig a bit deeper and see what we can do.-`

See above, happens cross distro, hardware, and setup, so unrelated. All I did was download the latest package and run directly from that unpacked zip.

**Comment by Thien42** [comment]
@Rastuasi are you able to tell me if your machine is little endian or big endian?

You can try running: `lscpu | grep Endian`

**Comment by Rastuasi** [comment]
> @Rastuasi are you able to tell me if your machine is little endian or big endian?
> 
> You can try running: `lscpu | grep Endian`

It is little endian

**Comment by GenericNerd** [comment]
We are going to need more information about how to reproduce this bug. We have tried the instructions you have provided and we have been unsuccessful. We are able to load into the simulator and complete a flight in X-Plane 12 and Linux.

**Comment by GenericNerd** [comment]
Detailed reproduction steps were not given within a week, so I'll mark this issue as stale at the moment.

**Comment by Rastuasi** [comment]
Wow okay, not stale but dealing with medical emergency and subsequent death in family so not been able to test latest update. No where does it state a week required regardless of situation

**Comment by GenericNerd** [comment]
> Wow okay, not stale but dealing with medical emergency and subsequent death in family so not been able to test latest update. No where does it state a week required regardless of situation

I'm incredibly sorry to hear that! We didn't mean to close this as a personal attack, but to keep the repository organised. Whenever your personal matters are resolved, feel free to re-open the issue and we'll investigate further.

**Comment by Rastuasi** [comment]
As for repo steps, I didn't do anything except install OS, install sim, install this on my Manjaro box, ofc after making sure OS is fully updated. But I know via discord, there's an update to the plugin, so was going to test that version to see if it happened to be corrected via other indirect fixes.
