### ISSUE TITLE
[BUG] - ATC Coverage radius not to scale

### ISSUE THREAD

**Issue by cyrus-thedeltavirtual** [invernyx/smartcars-3-bugs#275]
### Describe the bug

The ATC coverage rings are not realistic. Some of them are even larger than entire continents!
May the radius needs to take zoom level into consideration.

### How do you reproduce this bug?

Enable ATC layer on the map.
Zoom all out. 
Observe coverage area of any active tower.
Zoom in,
Radius remains the same effectively altering the area of coverage. 

### Expected behavior

Radius should reduce as you zoom out so that the actual area covered remains consistent 

### Operating system

Win 10

### Community airline

The Delta Virtual

### smartCARS Version

Version 0.12.0

### Plugins installed

all default plugins

**Comment by Thien42** [comment]
Will be solved in the next release
