### ISSUE TITLE
[BUG] - `{fuelUsed}` rounding

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#276]
### Describe the bug

We're using this variable in our flight logger to display how much fuel was used when landing happens and its returning a result like the below
`6678.6886079999995`

### How do you reproduce this bug?

1. Add `{fuelUsed}` to flight logger for landing
2. fly a normal flight
3. observe logbook

### Expected behavior

This number could do with some rounding. Alternatively if it needs to be specific, can a new variable be created like `{fuelUsedRounded}` or something

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/2434efa3-0ca4-40d9-81e9-e6699a8db2af)

### Operating system

Win 11 latest

### Community airline

QVirtual

### smartCARS Version

0.12

### Plugins installed

all except simbrief

**Comment by bgiorgio0506** [comment]
this bug will be fixed fuelUsed will now be rounded
