### ISSUE TITLE
[FEATURE] - Flight Center - Add Departure/Arrival Times to Result List

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#279]
### Is your feature request related to a problem? Please describe.

When looking for flights in the Flight Center, the flight departure and arrival times are not in the result list.  So if looking for a flight departing or arriving at a particular time of day, you must click on each flight to see the departure and arrival times.

### Describe the solution you'd like

Add departure and arrival times to the result list in Flight Center, so they can be seen without having to explicitly click on each flight to see this information.  This would also allow the results to be sorted by theses fields.

### Describe alternatives you've considered

Aside from clicking each individual flight there is no alternative.

### Additional context

Today have to click on a flight to see the scheduled departure and arrival times.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/15804044-2d8f-46f5-bdfb-766a286490a7)

**Comment by Thien42** [comment]
This was added in a previous release but forgot to close the issue, closing it now.
