### ISSUE TITLE
[BUG] - Several "old" instances of SC3 Running at Once

### ISSUE THREAD

**Issue by CaptainMac2336** [invernyx/smartcars-3-bugs#28]
**Describe the bug**
When I close smartCARS 3, the instance continues to run in the background. When I start a new instance, the first remains active. Eventually, I have several instances of the program running. The only problem it has caused is when I try to run the repair function, or the remove function using the installer. The installer tells me there are several instances running and asks if I would like them shut down automatically. If I select yes, the program fails to shut them down. If I shut them down using task manager, the program will repair or remove without issue.

**To Reproduce**
1. Start SC3 and shut it down
2. Repeat step 1 two or three times
3. View task manager activities
4. See smartCARS running in the background

**Expected behavior**
When I shut down SC3, it should not continue to run in the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/45597752/225404846-95559823-8afd-40a9-8621-017c75201207.png)

**System Information (please complete the following information):**
 - OS: Windows 10 Version 10.0.19045 Build 19045
 - Community ID: Any
 - Version 0.5.6
 - Plugins used: None

**Additional context**

**Comment by GenericNerd** [comment]
*Edit*:
Moved photo from link to image

**Comment by turbofandude** [comment]
Fixed in 0.5.8
