### ISSUE TITLE
[BUG] - File Pirep button gives error, does not send the pirep

### ISSUE THREAD

**Issue by ariel8407** [invernyx/smartcars-3-bugs#281]
### Describe the bug

When the flight ends clicking on file Pirep gives an error:
We could not file your flight due to an error. Further information can be found in your log.

This error does not allow the pireps to be sent to phpvms5 that I use

### How do you reproduce this bug?

1- click on the File Pirep button

### Expected behavior

I don't know why it happens, but the logs say that it is because of the client's local api

### Screenshots

https://media.discordapp.net/attachments/935945460370243664/1122359916083019837/smartCARS_3_6_24_2023_10_57_14_PM.png?width=1193&height=671

### Operating system

Windows 11

### Community airline

American Virtual Airline

### smartCARS Version

0.12.0

### Plugins installed

all

**Comment by bgiorgio0506** [comment]
@ariel8407 hey can you appload your log ? 
You can found it in %localappdata%/TFDi Design/smartCARS 3/logs

**Comment by ariel8407** [comment]
[error.log](https://github.com/invernyx/smartcars-3-bugs/files/11929789/error.log)

**Comment by bgiorgio0506** [comment]
@ariel8407 can you send me also the combined.log. Is located in the same folder

**Comment by ariel8407** [comment]
[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/11929984/combined.log)

**Comment by bgiorgio0506** [comment]
I cannot find any log entry refering to an attempt to file a pirep

**Comment by ariel8407** [comment]
I understand, but I assure you because there is also the evidence attached here that does not allow sending the pireps and I am not the only one who has reported this, other bugs are also reporting it

**Comment by ariel8407** [comment]
https://media.discordapp.net/attachments/935945460370243664/1122359916083019837/smartCARS_3_6_24_2023_10_57_14_PM.png?width=1193&height=671

In this link is the evidence that the client does not send the pireps

**Comment by bgiorgio0506** [comment]
@ariel8407 sorry for my silence do you have idea of what api version ur VA is using ?

**Comment by ariel8407** [comment]
Yes api 0.3.4

**Comment by GenericNerd** [comment]
This will be fixed in the next update
