### ISSUE TITLE
[BUG] - Cruising 0 ft

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#282]
### Describe the bug

I have 195 pilot flights where 'Cruising at 0ft' is happening.

I've included the log file from smartCARS 3 in the spreadsheet.
[wat_0cruise_log.xlsx](https://github.com/invernyx/smartcars-3-bugs/files/11911592/wat_0cruise_log.xlsx)

Let me know if you need anything else.

It might also be related to #280 
Also have this ticket from couple weeks ago #270 

### How do you reproduce this bug?

1. Start a flight with a small GA plane (seems to be common)
2. Monitor the immediate take off and climbing entries; it tends to happen right at the start.

### Expected behavior

It shouldn't read 0 ft.

### Screenshots

N/A

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.12.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Did this start happening suddenly or after a change on your end?
~~@Thien42 Could this be due to our change at Expo?~~

**Comment by Thien42** [comment]
Is this happening only in MSFS ?

**Comment by walkerairtrans** [comment]
@GenericNerd @Thien42

The dates of each occurrence are in the spreadsheet attached to the ticket--you should be able to gauge how sudden it onset.

I see it from 4/10 through 6/29.

I do see in all 195 PIREP's they appear to all be MSFS.

**Comment by walkerairtrans** [comment]
Just to add on, I'm starting to see the same thing with "Cruise > Descent > Approaching" -- it seems to transition "Cruise > Approaching". Looks like it might be MSFS (or in some form anything using FSUIPC.

I'm starting to see this because I'm enabling map markers for these phases and graphs of altitude/groundspeed. When I start investigating I see missing phases.

I hope this helps.

**Comment by bgiorgio0506** [comment]
@walkerairtrans  what version of FSUIPC are you using

**Comment by walkerairtrans** [comment]
> @walkerairtrans what version of FSUIPC are you using

I’m on the latest version—

**Comment by GenericNerd** [comment]
Fixed in the next release
