### ISSUE TITLE
[FEATURE] - Release Notes for SC3

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#283]
### Is your feature request related to a problem? Please describe.

When 0.12.0 was installed it popped up a window with items in the new release, but there is apparently no where to go back and see that list.  So, if a user thought they saw something in that popup as a new feature, and that new feature does not seem to be working, cannot go back to make sure that it really was part of the release.

### Describe the solution you'd like

Please include release notes when new versions of SC are installed.  If possible, would be good to know what changes are in new versions of plugins as well.  Either have as a text file in the SC3 install folder, or list something in Discord in a SC3 release notes channel.

### Describe alternatives you've considered

None.

### Additional context

N/A

**Comment by Thien42** [comment]
Will be added in the next release
