### ISSUE TITLE
[FEATURE] - Formally notify user when Premium pauses flight

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#284]
### Is your feature request related to a problem? Please describe.

My simulator was paused and I did not know, so I began to worry my sim/WASM had died.

### Describe the solution you'd like

When Premium pauses a flight, it should notify the user via the sound and add a persistent notification to the list.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Thien42** [comment]
Will be added in the next release
