### ISSUE TITLE
[FEATURE] - Reduce sensitivity of Premium pitch/bank pause criteria

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#285]
### Is your feature request related to a problem? Please describe.

I experienced a Premium pause that I would consider a false positive; Premium stated it was due to bank angle exceeding 30 degrees, yet I do not know if A: that actually happened or B: if that is the right number.

### Describe the solution you'd like

Reduce sensitivity of bank/pitch pausing. If 30 degrees is the bank limit, we should pause at 40.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Thien42** [comment]
Will be added in the next release
