### ISSUE TITLE
[BUG] - Flight Tracking - Change to "Climb" During Cruise

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#287]
### Describe the bug

This is happened on two different flights.  During cruise the flight phase will change back to "climb".  Once this happened, the phase remained as "climb" until landing.

6/24/2023 1:29:19 PM | Cruising at 35900 ft
6/24/2023 2:20:00 PM | Bank exceeded 30 degrees
6/24/2023 2:20:06 PM | Climbing at 257 kts, 4 degrees pitch, -7 degrees bank

7/2/2023 12:10:16 PM | Cruising at 34100 ft
7/2/2023 2:19:51 PM | Climbing at 265 kts, 3 degrees pitch, -6 degrees bank

Both times that this happened were after a turn (change in heading) and within 30 miles of TOD.  The first time was a fairly large turn, but the second was just 270 to 252.

### How do you reproduce this bug?

Not sure how to recreate as it doesn't happen all of the time.  Will keep an eye on this, but when it did happen it was after a turn during cruise close to TOD.

### Expected behavior

The flight phase should not (seemingly) randomly change from cruise to climb.  The aircraft did not indicate a significant change of altitude (ie: no more than 100 feet) during a turn.

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.12.0

### Plugins installed

Chat 0.11.0, Flight Center 0.10.1, Flight Tracking 0.12.0, Logbook 0.10.1, Map 0.10.0, SimBrief 0.10.1

**Comment by bgiorgio0506** [comment]
this has been handled and will be fixed in the next release
