### ISSUE TITLE
[FEATURE] - Increase Position Frequency

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#288]
### Is your feature request related to a problem? Please describe.

I'd like an option in Central to increase frequency to 15 seconds -- I have the servers and hardware to handle the traffic load. I know we have this in smartCARS 2 and I've had it enabled for few years now. Can we get that same thing in SC3?

### Describe the solution you'd like

Increase position reporting from 30 seconds to 15 seconds.

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by jordanhavard** [comment]
They said no to this already 😢 although hopefully they reconsider [#139](https://github.com/invernyx/smartcars-3-bugs/issues/139)

**Comment by GenericNerd** [comment]
Due to the nature of Premium, increasing the frequency would allow airlines to reconstruct some of the data that Premium users have available.

**Comment by GenericNerd** [comment]
We recently had this come up for a re-review and we found out smartCARS 2 actually did have an option for reporting position every 15 seconds. So we're going to be adding an option to change the frequency reporting with the following options:
- 60 seconds
- 30 seconds
- 15 seconds

**Comment by Thien42** [comment]
Implemented in the latest plugin update
