### ISSUE TITLE
[FEATURE] - Configurable Taxi Trigger or Trigger at Lower Speed

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#289]
### Is your feature request related to a problem? Please describe.

Currently, "taxi" phase does not get triggered until the aircraft reaches a ground speed of 11kts.  The aircraft could be taxiing for a while before 11kts is reached.  In some cases, if the parking area is near the departure end of the runway, the aircraft will only  briefly show "taxi" phase during the takeoff roll.

This is a minor item, but 11kts seems to be quite a high speed for this trigger. Also, if there are any future features that would be tied to the taxi phase (like cabin announcement) then this would cause issue.

### Describe the solution you'd like

Have a configuration setting to control the speed at which "taxi" is triggered.  Or lower the threshold to 7 or 8kts, similar to the trigger in SC2.

### Describe alternatives you've considered

None applicable.

### Additional context

7/4/2023 4:00:53 PM | Pushing back with 19531 lbs of fuel
7/4/2023 4:03:14 PM | Engine 2 On
7/4/2023 4:04:16 PM | Engine 1 On

**Taxi phase only appeared when 11kts was reached during the takeoff roll:**
7/4/2023 4:09:31 PM | Taxiing out
7/4/2023 4:09:38 PM | Taking off

**Comment by GenericNerd** [comment]
The condition we have configured is for the taxi phase to start when the aircraft speed has reached 10 knots. The reason for this is that we have no way of determining whether the aircraft is pushing back or taxiing until higher speeds are reached. We could perhaps reduce the speed to 5 knots, but I am worried that this will cause a false taxi phase during pushback if the pushback reaches this speed.

**Comment by bryan737dfw** [comment]
Understood.  For me, I don't think that I have gone over 3 knots during a pushback.  Your concern was why I suggested possibly using 7 knots as the trigger.  The would equate to about 8 mph.  Since there would typically be wing walkers walking with the aircraft during the push, the push "should" be done close to a walking pace. This is why I was thinking this would be a good compromise for pushback speed?

**Comment by Thien42** [comment]
We will change the taxi speed to 5 knots
