### ISSUE TITLE
[BUG] - Can't Log Flight to TFDi Design Error Message

### ISSUE THREAD

**Issue by HondaJet** [invernyx/smartcars-3-bugs#292]
### Describe the bug

For some time now when I finish a flight with SC3 it logs the flight to Mirage VA and to my Premium in a green banner.  However after that green banner shows there is another banner that opens red and says Could not log your flight with TFDi Design.   See log for more information.   

If it will help I can send you a copy of the log.

### How do you reproduce this bug?

This is consistent with every flight since this pattern started weeks ago.  Sorry I don't remember when it actually began.
The sims used have been MSFS, XP12 & P3Dv5 but mostly MSFS at this time.

### Expected behavior

I assume it is not normal for the flight to not get logged with TFDi.
What am I missing since the flight is not logged with this final part?

### Screenshots

The banner does not stay showing long enough to get a screenshot.

### Operating system

Win10

### Community airline

Mirage Executive Charters

### smartCARS Version

0.12.0

### Plugins installed

Flight center, Flight tracking, Logbook, Map, Chat, Simbrief

**Comment by HondaJet** [comment]
To add a little more info for this issue, today I did a A320 flight in MSFS and used my partner VA Millennium.  Both of these VAs are using phpVMS 5.  I had the same result with SC3 with this flight.  The message says it logs the flight to Millennium VA and to my Premium in a green banner.  However after that green banner shows there is another banner that opens red and says "Could not log your flight with TFDi Design. See log for more information".  What do you think?

**Comment by bgiorgio0506** [comment]
Please send me a copy of the log

**Comment by bgiorgio0506** [comment]
I fixed this error in the next version

**Comment by HondaJet** [comment]
Super, looking forward to it
