### ISSUE TITLE
[BUG] - Application is still tracking after 'End Flight' button is visible and also after submitting.

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#293]
### Describe the bug

I'm having more issues with pilots, fuel, and other checks we do--including the effects of opening MSFS menu prior to submitting.

The application does **not** stop tracking after engines are turned off. It should, as soon as the 'End Flight' button shows up, the transfer data to my server and the app should cease.

I have issues where a pilot will go to the MSFS menu, the fuelTotalQuantityWeight will go to 0 (say they had 5000lbs at the end of their flight), that 5000lbs just got logged in the app as fuel used, and now their PIREP is sent to us with a fuel use 5k lbs more than it should.

End of the flight
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/96e6c8db-8978-4385-8363-3e49a0e1e7c0)

Went to MSFS menu
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/4396f6b8-4e47-4340-9615-a7be88c5592c)

This change now becomes fuel used when the pilot actually submits.

It also does not stop when a user submits their PIREP (see log from my server.)

> Line 1441: IPSCRUBBED - - [09/Jul/2023:08:40:12 +0000] "POST /api/smartcars3/flights/complete HTTP/1.0" 200 725 "-" "axios/1.3.5"
Line 1442: IPSCRUBBED - - [09/Jul/2023:08:40:45 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1444: IPSCRUBBED - - [09/Jul/2023:08:41:00 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1447: IPSCRUBBED - - [09/Jul/2023:08:41:30 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1451: IPSCRUBBED - - [09/Jul/2023:08:42:15 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1455: IPSCRUBBED - - [09/Jul/2023:08:42:45 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1456: IPSCRUBBED - - [09/Jul/2023:08:43:00 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1460: IPSCRUBBED - - [09/Jul/2023:08:43:45 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1463: IPSCRUBBED - - [09/Jul/2023:08:44:00 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1466: IPSCRUBBED - - [09/Jul/2023:08:44:30 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1469: IPSCRUBBED - - [09/Jul/2023:08:45:00 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"
Line 1472: IPSCRUBBED - - [09/Jul/2023:08:45:30 +0000] "POST /api/smartcars3/flights/update HTTP/1.0" 404 772 "-" "axios/1.3.5"

### How do you reproduce this bug?

1. Start a flight
2. Land the flight
3. Get the 'End Flight' button and monitor the app/server (see continuous calls being made.)
4. Monitor FuelTotalQuantityUsed and go to MSFS main menu--you'll see data feed continuning to capture and t

### Expected behavior

Once "End Flight" is visible--all capture/transmit should cease--just like it did in smartCARS 2.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by bgiorgio0506** [comment]
@walkerairtrans I don't agree with your instance here. The End Flight Button is there for this reason tell the tracker when to actually stop looking at the flight. 

If you stop your engine this does not mean you are not burning fuel you could have your APU running until you get your GPU or other VA may have different SOPs, etc .... 

When we show up the End Flight Button we just assume that you arrived to your block position but we are not certain you "ended" the flight so until user clicks end flight we keep looking what you are doing.

**Comment by walkerairtrans** [comment]
> @walkerairtrans I don't agree with your instance here. The End Flight Button is there for this reason tell the tracker when to actually stop looking at the flight.
> 
> If you stop your engine this does not mean you are not burning fuel you could have your APU running until you get your GPU or other VA may have different SOPs, etc ....
> 
> When we show up the End Flight Button we just assume that you arrived to your block position but we are not certain you "ended" the flight so until user clicks end flight we keep looking what you are doing.

That’s fine—you just need to come up with a way to stop allowing fuel quantity total changes to happen if they go into MSFS menu. I see your flagging pause log when the menu opens so perhaps you can lock that field based on that. Right now, going to the menu is affecting the fuel values and it’s giving erroneous results. 

I had someone submit and because of this bug the result from the app was -186789 for fuelused. And I confirmed he hit ESC and then submit.

This obviously wasn’t a problem in SC2 because once end flight shows the app stops recording. 

Secondly, when a flight is submitted (completed shows in the log) the app needs to stop sending data to the server. You have no reason to communicate as the pilot fully submitted the flight. 

If we can resolve these I’d be more inclined to allow the rest of my pilot base to use the app. But right now, I have zero interest in managing a ton of flight rejections because of fuel used values being seriously incorrect.

**Comment by GenericNerd** [comment]
This is one issue and one suggestion. I do not believe this is required regarding the tracking stopping as soon as the "End Flight" button appears. As Giorgio correctly stated, there could still be fuel burning (or even relocations to different stands if you wanted to be at another stand for your next flight) which has to be accounted for. I think it is fair to assume that confirmation is required by the user for the flight tracking to end and stop updating.

In regards to the fuel quantity dropping to 0, that is a bug and we'll look into it.

**Comment by bgiorgio0506** [comment]
the bug part of the issue has been handled. For the suggestion part please open a new issue.
