### ISSUE TITLE
[BUG] - MacOS App does not close with CMD+Q or Menu > Quit

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#294]
### Describe the bug

When trying to close the app on the Mac, it does not respond to CMD-Q or Menu > Quit. I have to right click the app in the dock and click quit.

### How do you reproduce this bug?

1. Launch the app
2. Hit CMD+Q, or Menu > Quit

### Expected behavior

App should close with either default options.

### Operating system

Ventura 13.0

### Community airline

Walker Air Transport

### smartCARS Version

0.11.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
Likely caused by the "Built on Windows" nature - although Linux also responds to Alt+F4. We'll get it resolved as soon as possible.

**Comment by GenericNerd** [comment]
We should hopefully have this resolved next week, as we've obtained a Mac to debug this :)

**Comment by Thien42** [comment]
We're going to solve an issue about quitting the app on Mac OS, however for me the app responds properly to CMD+Q or Menu > Quit.

Please let us know if you are still having this issue
