### ISSUE TITLE
[FEATURE] - Alignment of Grid Data

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#295]
### Is your feature request related to a problem? Please describe.

The data in the various grids should be left aligned with the column header rather than center aligned.  When there is a varying length of the data in a column, it looks sloppy when it is center aligned.  This is especially noticeable with the aircraft column.

Also, on the log book view, there is a great deal of space between the departure, arrow, and arrival columns.  Maybe this could be reduced?  This would allow for the flight time to be displayed in this view as well.  (I can add this as a separate feature request if desired)

### Describe the solution you'd like

Have grid column headers and grid columns left aligned.

### Describe alternatives you've considered

None available.

### Additional context

Flight Search:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/140d8a63-2a8b-4ad9-b55c-409e439b2871)

Bid List:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/f454f2c5-79a6-4efb-a83f-7f2d28e0e067)

Log Book:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/f9f0b504-39ad-4208-9681-93573808f402)

**Comment by Thien42** [comment]
Will be solved in the next release
