### ISSUE TITLE
[BUG] - Time to go to destination not calculating if you fly past your destination

### ISSUE THREAD

**Issue by dCarnage** [invernyx/smartcars-3-bugs#296]
### Describe the bug

When you fly past destination due to forgetting to Pause at TOD , The counter for Time to go is stuck at 0h00m

### How do you reproduce this bug?

Fly past your destination

### Expected behavior

The field should be constantly calculated.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/27756186/22c6dcf0-07a3-4f86-8b0b-459df5825749)

### Operating system

Windows 11

### Community airline

Qvirtual

### smartCARS Version

latest

### Plugins installed

simbrief

**Comment by Thien42** [comment]
This is currently working as intended. In case you are late (for whatever reason) the time to destination will reach 0h00m and the delay will increase instead.

If you would like us to change/improve this behavior please open a feature request detailing how you would like this field to behave.
