### ISSUE TITLE
[BUG] - Fuel Usage

### ISSUE THREAD

**Issue by dCarnage** [invernyx/smartcars-3-bugs#297]
### Describe the bug

If you refuel mid air , it doesnt track fuel used total.
It only compares what you started with vs what you land with.

EG.
I flew YPDN to VHHH , i forgot to pause at TOD
so i added 33% fuel so i could test the smartcars refuel mid air tracking.
When i landed with 5000KG left , it just calculated Push back - Whats left in the tank at the end.

21:51:34 | Using Microsoft Flight Simulator
-- | --
21:51:34 | Flying PMDG 737-800 Qantas (VH-VXM \| 2021 \| Mount Hotham)
21:51:34 | Aircrafts weights: DOW: 41413kgs FOB: 20878kgs ZFW: 42263kgs
21:51:34 | Engine 1 On
21:51:34 | Engine 2 On
21:51:34 | Now boarding
21:52:05 | Pushing back with 20876 kgs of fuel

<REDACTED>

04:51:38 | On final at 814 ft with 3 nm to go at 204 kts, -3 degrees pitch, -4 degrees bank
04:52:37 | Touched down at -271 fpm, 1.4g, 130 kts, 3 degrees pitch, -0 degrees bank, wind 270 at 8 kts with 5229 kgs of fuel (15647.563224kgs in flight)
04:52:37 | Landed approx. 78 min late with a fuel burn on target

### How do you reproduce this bug?

Do a flight , Refuel infinitely.
Calculation is being done on Pushback - remaining , which isnt true if you refuel midair.

### Expected behavior

All fuel increases should be tracked

### Operating system

Windos 11

### Community airline

QVirtual

### smartCARS Version

Latest

### Plugins installed

all + simbrief

**Comment by Thien42** [comment]
This is by design and I don't believe we will change the way we calculate the fuel usage, see: https://github.com/invernyx/smartcars-3-bugs/issues/265

**Comment by jordanhavard** [comment]
@Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?

**Comment by GenericNerd** [comment]
I'm reopening this because I believe it should be something that we should take another look at. We could possibly do this by implementing a "range" or tolerance (of say 50 pounds) before it sends a log. This would of course be customisable for each community.

**Comment by bgiorgio0506** [comment]
> @Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?

Hey in the next update there will be this possibility for example if you want to check for in flight refueling the condition will look` {fuelTotalQuantityWeight} increased_by 1000 and {planeOnground} equals false` the same for` decreased_by`

**Comment by jordanhavard** [comment]
> > @Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?
> 
> Hey in the next update there will be this possibility for example if you want to check for in flight refueling the condition will look` {fuelTotalQuantityWeight} increased_by 1000 and {planeOnground} equals false` the same for` decreased_by`

Thanks @bgiorgio0506 Can `1000` be changed to any positive integer number or is it set to `1000`?
Would the condition `changed` be able to be used instead while still picking up both instances (to prevent me having an `increased_by` and a `decreased_by`) ?

Thanks for looking into this 🙏

**Comment by GenericNerd** [comment]
> > > @Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?
> > 
> > 
> > Hey in the next update there will be this possibility for example if you want to check for in flight refueling the condition will look` {fuelTotalQuantityWeight} increased_by 1000 and {planeOnground} equals false` the same for` decreased_by`
> 
> Thanks @bgiorgio0506 Can `1000` be changed to any positive integer number or is it set to `1000`? Would the condition `changed` be able to be used instead while still picking up both instances (to prevent me having an `increased_by` and a `decreased_by`) ?
> 
> Thanks for looking into this 🙏

It is in fact any integer that you want, and changed is still a word you’ll be able to use :)

**Comment by jordanhavard** [comment]
> > > > @Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?
> > > 
> > > 
> > > Hey in the next update there will be this possibility for example if you want to check for in flight refueling the condition will look` {fuelTotalQuantityWeight} increased_by 1000 and {planeOnground} equals false` the same for` decreased_by`
> > 
> > 
> > Thanks @bgiorgio0506 Can `1000` be changed to any positive integer number or is it set to `1000`? Would the condition `changed` be able to be used instead while still picking up both instances (to prevent me having an `increased_by` and a `decreased_by`) ?
> > Thanks for looking into this 🙏
> 
> It is in fact any integer that you want, and changed is still a word you’ll be able to use :)

Amazing 👍 

If I change my config now will that break or is it best to wait until next release? 
If the latter, what version should I be looking out for ?

**Comment by GenericNerd** [comment]
> > > > > @Thien42 @GenericNerd just to confirm, there is no way to track whether fuel has been increased or decreased and this is by design ?
> > > > 
> > > > 
> > > > Hey in the next update there will be this possibility for example if you want to check for in flight refueling the condition will look` {fuelTotalQuantityWeight} increased_by 1000 and {planeOnground} equals false` the same for` decreased_by`
> > > 
> > > 
> > > Thanks @bgiorgio0506 Can `1000` be changed to any positive integer number or is it set to `1000`? Would the condition `changed` be able to be used instead while still picking up both instances (to prevent me having an `increased_by` and a `decreased_by`) ?
> > > Thanks for looking into this 🙏
> > 
> > 
> > It is in fact any integer that you want, and changed is still a word you’ll be able to use :)
> 
> Amazing 👍
> 
> If I change my config now will that break or is it best to wait until next release? If the latter, what version should I be looking out for ?

You should wait until the next release of the flight tracking plugin. I will let you know on Discord with a ping when this happens.
