### ISSUE TITLE
[BUG] Flight tracking stopped

### ISSUE THREAD

**Issue by SilentDevCoPro** [invernyx/smartcars-3-bugs#298]
### Describe the bug

Flight tracking stopped for my x plane 12 when I changed the graphics settings.

X Plane 12 running in Rosetta, on an M1 Mac.

Tried restarting x plane and then restarting smartcars, no luck.

### How do you reproduce this bug?

1. X plane 12 Settings
2. Change graphics sliders
3. Accept changes, this causes a game loading screen
4. smartcars disconnects
5. Game continues smarcars states "Flight Tracking Connecting, We are connecting to the simulator. Please wait a few seconds."

It never connects.

### Expected behavior

Smartcars reconnects with flight

### Screenshots

<img width="1065" alt="Screenshot 2023-07-17 at 2 11 15 PM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/35481c6e-112b-4b29-8942-ab0399bc23e1">

### Operating system

M1 Mac, Ventura 13.4.1

### Community airline

smartCars  qvirtual

### smartCARS Version

0.12.0

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, Simbrief

**Comment by GenericNerd** [comment]
@Thien42

**Comment by GenericNerd** [comment]
Are you still having this issue? We've updated the flight tracking plugin since this issue was reported, so this might already be fixed.

**Comment by GenericNerd** [comment]
I'm closing this issue as stale for now. If you would like us to keep digging, please reply back if you're still affected by this issue.
