### ISSUE TITLE
[BUG] - SC3 not detecting crash, but then continues to log a further flight - partially.

### ISSUE THREAD

**Issue by rsh2155** [invernyx/smartcars-3-bugs#299]
### Describe the bug

If a pilot crashed a plane in MSFS, then goes back to the menu and starts the flight again...but is not forced too or does not reset SC3, then the flight does continue to log but not fully....

Tried to climb out of SLSU to the NW in a DC6 and didn't have the superchargers on, so mountains 1, Scott 0. 

I'll post the log here, but it's a curious one....

Volanta Link -> https://fly.volanta.app/flights/2499c5cc-315f-4792-ae35-c7f7a8e10ca6

Symptoms - 

because SC3 doesn't' recognise a "crash" like SC2. I went back to the MSFS menu and restarted the flight. 

Curiously, it picked up and confused/overlapped/added the stall/crash, with the restart. 

At 0918, I then kicked off again - wisely climbing to the south, before setting course.  Successful flight! 

SC3 picked up gear up, flaps retraction, then never picked up a cruise or descent. 

It did however later pick up gear deployment and flaps deployment. 

No 2nd (actual / proper) landing detected. 

No on-ground flaps retraction. 

Then engine off is detected. 
[dc6.txt](https://github.com/invernyx/smartcars-3-bugs/files/12065904/dc6.txt)

### How do you reproduce this bug?

1 - start flight.
2 - crash plane. 
3 - start new flight WITHOUT resetting SC3. 

### Expected behavior

SC3 should detect a crash event or not continue to log if a plane crash event is experienced. 

### Operating system

Windows 10 Home 22H2

### Community airline

QVirtual

### smartCARS Version

Version 0.12.0

### Plugins installed

chat, flight centre, flight tracking, logbook, map.

**Comment by GenericNerd** [comment]
We need to implement a method of checking whether the aircraft has crashed and end the flight tracking immediately thereafter. @bgiorgio0506 please take a look into implementing this.

**Comment by bgiorgio0506** [comment]
this has been handled and is gonna be included in the next update
