### ISSUE TITLE
[DEAD LINK] - Public API bugs not accessible

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#3]
When trying to create an API bug, the link comes up with 404 from desktop, however from the mobile GitHub app works fine (probably one for GitHub support)
https://github.com/invernyx/smartcars-3-public-api/issues
![image](https://user-images.githubusercontent.com/67948773/224463407-2904f059-f8b8-4e59-b63b-fafc34b0ad59.png)

**Comment by GenericNerd** [comment]
We’re just preparing that repository for the public, so it’s still privated at the moment. I’m actually surprised you were able to click the link from the mobile app at all. Quite strange. I’ll leave this open until the repository is public
