### ISSUE TITLE
[FEATURE] - Workarounds for engine start/flaps/etc custom code like A2A Comanche for MSFS

### ISSUE THREAD

**Issue by citadelskies** [invernyx/smartcars-3-bugs#301]
### Is your feature request related to a problem? Please describe.

While flying the A2A Comanche for MSFS, SmartCARS wasn't detecting when the engine is running and when the flaps are dropped. After doing some digging on the A2A Forums, it's known that A2A's custom Accu-Sim code for the engine, flaps, and other systems aren't using the datarefs SmartCARS are using (engine1fire, flapsControl, etc.) 

Relevant forum post: https://a2asimulations.com/forum/viewtopic.php?f=151&t=74723

### Describe the solution you'd like

Would like to see TFDi and A2A Simulations discuss a workaround for standalone engine/flap/system simulations. 

### Describe alternatives you've considered

N/A

### Additional context

![Screenshot (481)](https://github.com/invernyx/smartcars-3-bugs/assets/127919355/15cbf0ed-0bb4-477c-86da-673a46e9d41c)
![engine log](https://github.com/invernyx/smartcars-3-bugs/assets/127919355/216b562c-ccf1-48f7-905c-6ca1dfed1377)

**Comment by GenericNerd** [comment]
Unfortunately, if there are aircraft that do not use SimConnect or FSUIPC to transmit the current state, we will not be able to support that aircraft. A majority of aircraft conform to the existing standard and we cannot provide workarounds for custom toolings from other developers.

If someone else was to make a flight tracking plugin, specifically for another product, this is fine, but smartCARS will not be making any changes to support this at this time.
