### ISSUE TITLE
[BUG] - White Screen after Windows 11-Update

### ISSUE THREAD

**Issue by ShadowHunter1394** [invernyx/smartcars-3-bugs#303]
### Describe the bug

After updating my PC to the newest Windows 11-Build, smartCARS3-Client freezes at Start and only showes a White Screen with no loading whatsoever. Even doing a full reinstall with the latest Version didn't help.

### How do you reproduce this bug?

1. Start the App
2. White Screen shows up
3. Nothing happens after that
[error-2023-07-22.log](https://github.com/invernyx/smartcars-3-bugs/files/12138502/error-2023-07-22.log)
[error-2023-07-23.log](https://github.com/invernyx/smartcars-3-bugs/files/12138503/error-2023-07-23.log)
[combined-2023-07-22.log](https://github.com/invernyx/smartcars-3-bugs/files/12138504/combined-2023-07-22.log)
[combined-2023-07-23.log](https://github.com/invernyx/smartcars-3-bugs/files/12138505/combined-2023-07-23.log)

### Expected behavior

The Login-Screen should be showing up after starting the Application.

### Operating system

Windows 11 22H2

### Community airline

The Delta Virtual

### smartCARS Version

0.12.1.2

### Plugins installed

chat, map, flight center, logbook, simbrief

**Comment by Thien42** [comment]
Can you try the following steps:

- Uninstall the app
- Remove the `%appdata%/smartCARS 3` folder
- Reinstall the app

Please let us know if that fixes the issue or not.

**Comment by ShadowHunter1394** [comment]
Will do

Thiên Ân Lacape ***@***.***> schrieb am Mo., 24. Juli 2023,
09:59:

**Comment by GenericNerd** [comment]
Any update on this? Did a reinstall work?

**Comment by ShadowHunter1394** [comment]
The Update you guys rolled out the other day fixed my Problem. So thanks
for that.

GenericNerd ***@***.***> schrieb am Mo., 31. Juli 2023, 21:54:

**Comment by Thien42** [comment]
Thank you for the update!
