### ISSUE TITLE
[BUG] - `distanceRemaining` coming in as `NaN`

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#304]
### Describe the bug

I'm having increased error reports of `distanceRemaining` coming in as `NaN`

### How do you reproduce this bug?

Report only

### Expected behavior

Type checking at application level

### Screenshots

![CleanShot 2023-07-24 at 19 50 25](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/2b1184ec-0c95-48d1-b9fd-b4ce3ef9f56e)

### Operating system

n/a

### Community airline

QVirtual

### smartCARS Version

Latest

### Plugins installed

n/a

### Additional context

I've added type checking to my endpoints however though it worth sharing with your team

**Comment by jordanhavard** [comment]
Looks like its also happening for timeRemaining
![CleanShot 2023-07-24 at 19 58 24](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/ab777b73-a116-4405-9c0c-7f70e466c63d)

**Comment by Thien42** [comment]
Do you happen to know if this flight was using the Simbrief plugin as well?

**Comment by jordanhavard** [comment]
Unsure sorry, That information isn't passed to the API

**Comment by GenericNerd** [comment]
Can you send us some more POST logs for the flights you have affected by this issue?

**Comment by bgiorgio0506** [comment]
@jordanhavard  Is still happening? can you provide the information that Fabio asked ?

**Comment by jordanhavard** [comment]
I've since implemented a NaN check on my API, I'd assume its still an issue however doesn't impact us anymore

**Comment by GenericNerd** [comment]
Alright, we'll close this issue out for now, but if it crops back up or you're able to provide more information, please do let us know! We're unable to repro for now

<3
