### ISSUE TITLE
[BUG] - Passengers count is weird

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#308]
### Describe the bug

so we have deployed both smartcarsv2 and v3 in our VA v2 reads passengers just fine but in v3 the passenger count is somewhat weird 
as u can see in the screenshot i ve carried some 124125 passengers in a  single flight
![Screenshot_714](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/cb7e77db-865b-4f0e-b554-1af04fb78601)
 
 we are using api 0.3.4 and smartcarsv2 works fine with the passengers issue

### How do you reproduce this bug?

Passengers issue in PIREP

### Expected behavior

the passenger count should be something realistic 

### Screenshots

![Screenshot_714](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/69a9a490-65e4-41f0-95be-12bf9a6a3743)

### Operating system

Windows 10 /11

### Community airline

Airlink Virtual 

### smartCARS Version

0.12.1

### Plugins installed

logbook flight tracking chat simbrief

**Comment by GenericNerd** [comment]
The passenger and load information is (in 0.3.5 of the public API) entirely handled by the virtual airline. You can replicate this behaviour by removing the following line:

https://github.com/invernyx/smartcars-3-public-api/blob/master/0.3.4/handlers/phpvms5/flights/complete.php#L42

For this reason, this isn't an issue anymore and will not be fixed.

**Comment by EpicHax7** [comment]
thanks 
will check it out

**Comment by bryan737dfw** [comment]
Is removing this one line the only thing that will need to be done?  Is the passenger count coming from somewhere else, as it is not entered in SC3 like it was in SC2?

**Comment by EpicHax7** [comment]
> Is removing this one line the only thing that will need to be done? Is the passenger count coming from somewhere else, as it is not entered in SC3 like it was in SC2?

yeah man this didnt fix it our devs tried this but nno luck
