### ISSUE TITLE
[BUG] - Block Time Working?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#309]
### Describe the bug

I don't think block time is working? Can one of the TFDi admins verify?

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/e1e1ea28-5a35-439b-aa9b-782b049d08fc)

See attached PosRep array and the times.

> [15] => Array
>                 (
>                     [name] => position15
>                     [time] => [15:14]
>                     [lat] => 6.0577532189060035
>                     [lng] => 125.09907669022773
>                     [alt] => 519.62
>                     [head] => 58
>                     [gs] => 2
>                     [phase] => PUSH_BACK
>                     [warning] => 1
>                     [warningdetail] => 1
>                 )
                

> [228] => Array
>                 (
>                     [name] => position228
>                     [time] => [17:00]
>                     [lat] => 14.515699064421392
>                     [lng] => 121.01612597241942
>                     [alt] => 74.37
>                     [head] => 45
>                     [gs] => 0
>                     [phase] => DEBOARDING
>                     [warning] => 1
>                     [warningdetail] => 1
>                 )

"flightTime":"1.4747316666667383"

1 hours : 28 minutes : 29 seconds

It should have been closer to 1 hour 46 minutes if "block" is pushback to deboard?

### How do you reproduce this bug?

1. Enabled Block Time
2. Submit PIREP and validate times against POS logs

### Expected behavior

Should record time as defined.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.13.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by Thien42** [comment]
Whenever you apply a setting in SC central you need to restart any open SC3 instance for that new setting to be applied, this is a limitation of the current system that we might work on in the future.

Did you have SC3 already opened and started a flight directly after changing this setting?

**Comment by walkerairtrans** [comment]
No, the app was relaunched.

My pilots were also instructed and the same results.

Block time doesn’t appear to be in effect. Time is being logged between
take off and landing.

**Comment by Thien42** [comment]
I will look into it

**Comment by bryan737dfw** [comment]
I am also seeing this... air time still being used.  I'll check with the person who has access to the SC Central, but he thought he had set to block time yesterday and today it was set to air when he checked earlier, so he set it again.  I wonder if the setting isn't sticking?

**Comment by Thien42** [comment]
The issue will be fixed in the next release
