### ISSUE TITLE
[FEATURE] - Ability to remove Create Flight/New Bid Buttons in flight center

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#31]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Ability to disable or remove the create flight and new bid buttons.

**Describe alternatives you've considered**
None available as we have a specific use case for it. We would like to see the same feature in smartCARS 2 (Disable Flight Search) made available.

**Additional context**
None at the moment.

**Comment by walkerair** [comment]
I see the 'Create Flight' button is gone, possible we can have the option to do that for 'new bid' too?

**Comment by turbofandude** [comment]
Will be supported as of flight-center 0.6.1
