### ISSUE TITLE
[BUG] - Flight Center - Selected Aircraft Not Used/Logged

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#310]
### Describe the bug

On my last flight the scheduled aircraft was a Boeing 737-700 but I was flying the 737-800.  I selected the 737-800 from the dropdown list on the bid line.  In Flight Tracking, it showed I was flying the 737-800, but when I filed my PIREP it logged with the scheduled 737-700 aircraft.

I am used the "plan with SimBrief" option and using my last SimBrief plan, not sure if that is impacting this as well?

### How do you reproduce this bug?

1. Bid on a flight that is not scheduled in the aircraft that you will be flying.
2. Select the actual aircraft from the dropdown list.
3. Use Plan with SimBrief.
4. Import last OFP.
5. Fly the flight.
6. At end of flight file flight plan.
7. Check phpVMS for PIREP... will show scheduled aircraft.

### Expected behavior

PIREP will be filed with the actual aircraft that was selected.

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.13.0

### Plugins installed

Chat 0.11.2, Flight Center 0.11.0, Flight Tracking 0.13.2, Logbook 0.12.3, Map 0.10.2, SimBrief 0.11.1

**Comment by GenericNerd** [comment]
I'm going to try and reproduce this issue with the outlined steps.

**Comment by GenericNerd** [comment]
I've not been able to recreate this issue. Are you able to let me know what API version your community is using, as well as the platform? (phpVMS 5/7)

**Comment by bryan737dfw** [comment]
API I believe is 0.3.4 and platform is phpVMS v5).  Definitely still get this.  On Sunday did a flight which was scheduled in the A320.  I used and selected B737-800.  In the Flight Tracking screen in SC3 it showed my selected type on the display, but on the filed PIREP it logged as the scheduled A320 aircraft.

**Comment by GenericNerd** [comment]
Does it show the correct aircraft in the log, but not in the booking itself?

**Comment by bryan737dfw** [comment]
Negative.  It logs with the scheduled aircraft.  For example, this flight bid below is how it appears on the Flight Center screen after I bid:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/a3798bdd-d359-4837-b203-a35b8ea90d5e)

The flight is scheduled in the Airbus A321.  When I go to fly, if I change the value in the drop list to Boeing 737-800, the flight tracking screen will show the 737-800, but when I file the PIREP it will log the flight with the A321.  I initiate the flight via  the Plan with Simbrief button, so not sure if flight tracking is picking up the 737-800 from there or the drop list on the Flight Center.

**Comment by GenericNerd** [comment]
I have finally gotten around to testing this on a community that has the feature enabled, and I am able to replicate the behaviour you are seeing. The issue is that it would be incredibly difficult to change the aircraft selection automatically, as the community might not have the aircraft available for selection in the first place.

For this reason, I believe it is up to the community to verify that the aircraft is as they are expecting. This behaviour was the same in smartCARS 2, so I don't believe that this is new behaviour for communities to get used to. Thanks for the report!

**Comment by bryan737dfw** [comment]
I really do not understand how the current behavior in SC3 is like SC2.  In SC2 when the user selects the actual aircraft they are using and starts the flight, THAT is the aircraft that will be sent when the PIREP is filed.  So, in SC2 if the pilot selects the 737-800 as the actual aircraft they are flying that is what will be submitted as the aircraft when they file the PIREP (even if scheduled aircraft was something else).  SC3 ignores the actual aircraft selected when starting the flight when the PIREP is filed, so the PIREP always shows the scheduled aircraft.
