### ISSUE TITLE
[BUG] - Flight Center - Aircraft Dropdown Does Not Default to Scheduled Aircraft

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#311]
### Describe the bug

The new aircraft dropdown always shows the first aircraft in the list regardless of what the scheduled aircraft is.  The bid is actually stored with the scheduled aircraft, so the flight in the bid list should reflect this.

### How do you reproduce this bug?

1. Bid on a scheduled flight in Flight Center.

### Expected behavior

When bidding on a scheduled flight the aircraft should show the scheduled aircraft for that flight.  When flying the flight the actual aircraft that will be used can be selected, but the list should begin with the scheduled aircraft selected.

### Screenshots

Bid on flight:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/1dfc75d8-3e3d-40c5-a781-1df145506a94)

When bid appears in list of bids, the aircraft shown is the first aircraft in the database and not the scheduled aircraft:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/04ec5a85-73a8-4499-bafe-932f025d2fee)

Viewing the bid in phpVMS Flight Center:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/80c746b2-d145-4e8a-b619-7e92cc2ad1fd)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.13.0

### Plugins installed

Chat 0.11.2, Flight Center 0.11.0, Flight Tracking 0.13.2, Logbook 0.12.3, Map 0.10.2, SimBrief 0.11.1

**Comment by Thien42** [comment]
This is the behavior when the option to allow any aircraft in the fleet is enabled

**Comment by bryan737dfw** [comment]
It behaved quite well in SC2.  The scheduled aircraft was selected, but you were able to change it, if needed, when starting the flight.  

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/0cc6750f-9fbb-4073-addd-8d74df861233)

**Comment by GenericNerd** [comment]
We have issued this a low priority since this only happens when allowing a pilot to select any aircraft. While the default should be the scheduled aircraft, we don't think this is a massive UX issue when the setting is enabled.

**Comment by bgiorgio0506** [comment]
this issue will be resolved in the next update
