### ISSUE TITLE
[BUG] - Disconnect on Simulation Pause

### ISSUE THREAD

**Issue by fleurenf55** [invernyx/smartcars-3-bugs#314]
### Describe the bug

When the sim is paused, SC3 disconnects and will not automatically reconnect when the Sim is unpaused.

### How do you reproduce this bug?

Set simulation pause

### Expected behavior

Should automatically reconnect.

### Operating system

Windows 11 pro

### Community airline

QVirtual

### smartCARS Version

Latest

### Plugins installed

Xpuipc

**Comment by bgiorgio0506** [comment]
@fleurenf55 Hey can you elaborate more about your setup : 
Which sim are you using? Are you using UDP or fsuipc/xuipc tracking provider? Can you share you log in `%localappdata%/TFDi Design/smartCARS/resources/logs`

**Comment by turbofandude** [comment]
I am closing this issue out as stale. Please re-open with more details when possible.
