### ISSUE TITLE
[BUG] - Aircraft Registration and ICAO are not shown on the live map.

### ISSUE THREAD

**Issue by Osviel02** [invernyx/smartcars-3-bugs#315]
### Describe the bug

Since its launch I have presented the same error with smartCARS V3 and I know that many have experienced it, in fact there are thousands of reports like this, but none proposes the correct solution although many have already solved it. But in my VA I continue presenting the same, the flights that are reported with the smartCARS V3 do not send the information of the plane that is being flown to the web. Please I require the help of some genius to solve this problem once and for all.

### How do you reproduce this bug?

Flight Board, aircraft 

### Expected behavior

The information that ACAR exports to the web does not show the data of the plane that is using the reservation

### Screenshots

![sad](https://github.com/invernyx/smartcars-3-bugs/assets/74525133/77784889-c314-4e5c-a64e-03ae6f997973)

### Operating system

windows 11

### Community airline

smartCARS v3

### smartCARS Version

0.3.5

### Plugins installed

aircraft

### Additional context

The information that ACAR exports to the web does not show the data of the plane that is using the reservation

**Comment by GenericNerd** [comment]
What version of phpVMS are you using? It is possible this is an API issue. If it is, we'll move it to that repository.

**Comment by Osviel02** [comment]
phpvms v5.5.5

**Comment by GenericNerd** [comment]
Can you please tell me what API version you are using?

**Comment by GenericNerd** [comment]
Closed as stale since no answer was obtained within 2 weeks. If this is still an issue, open up a new issue with a mention to this one
