### ISSUE TITLE
[BUG] - No flight restoration on premium

### ISSUE THREAD

**Issue by SilentDevCoPro** [invernyx/smartcars-3-bugs#316]
### Describe the bug

Smartcars3 crashed, I restarted it, it had lost tracking of my flight and didn't give me an option to continue the flight.

### How do you reproduce this bug?

1. Start flight in x plane 12
2. Start tracking before takeoff in smart cars 3
3. Check that cloud backups are running, icon has turned green.
4. During flight pause flight using SC3 pause button
5. Come back next day and SC3 has crashed
6. Start SC3 back up
7. Tried to start flight tracking again but get error "Flight Tracking, Scenario Validation Error, Please ensure that you are the right airport and have your wheels on the ground".
8. There are no restore flight options.

### Expected behavior

After restarting a crashed SC3, it should give an option to restore flight.

### Screenshots

<img width="657" alt="Screenshot 2023-08-05 at 9 03 18 AM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/c9100eda-9ec2-4c0c-9228-fb38784b912a">
<img width="1297" alt="Screenshot 2023-08-05 at 11 15 34 AM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/b08b5162-d5e6-4f7d-b274-bfa1f6f99a62">
<img width="1283" alt="Screenshot 2023-08-05 at 11 16 21 AM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/82d7a017-5fbf-4817-9213-ec0be8550b02">

### Operating system

M1 Mac, Ventura 13.5

### Community airline

qvirtual

### smartCARS Version

0.12.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, Simbrief

### Additional context

Flight was left paused using the SC3 pause button overnight, came back and the application had crashed. Had an error saying "Are you sure you would like to close SC3", this error kept persisting even after clicking no a few times and some other errors on the application, however I did not grab a screenshot unfortunately.

**Comment by dcherrie** [comment]
I had a simulator crash yesterday and went to use the restore feature however there was no restore button when I opened smartCARS with the simulator running.

During my flights I can see the restore button on the "My Flights" page and I see the cloud icon on the tracking log saying my flight is being backed up by smartCARS Premium.

This was on PC and not on Mac.

**Comment by GenericNerd** [comment]
> I had a simulator crash yesterday and went to use the restore feature however there was no restore button when I opened smartCARS with the simulator running.
> 
> During my flights I can see the restore button on the "My Flights" page and I see the cloud icon on the tracking log saying my flight is being backed up by smartCARS Premium.
> 
> This was on PC and not on Mac.

Did the flight backup cloud show red or green while you were flying?

**Comment by SilentDevCoPro** [comment]
@GenericNerd Green.

**Comment by GenericNerd** [comment]
Have you been able to recreate the smartCARS crash since?

**Comment by SilentDevCoPro** [comment]
@GenericNerd The other day I just closed x plane by mistake and the recover flight button was not an option when I started it back up. 

I did get the opportunity try a recovery a few days ago, got the plane off the ground and cleaned up. Clicked recover and it put me into an unrecoverable flat spin into the ground.

**Comment by Thien42** [comment]
Are you able to provide some more details?

Which aircraft were you flying? Around what speed/altitude/flight phase were you at?

**Comment by SilentDevCoPro** [comment]
Flight I was trying to restore to, this is both flights:
Toliss A319, FL330-370, 0.78m, Cruise. To Recover I flew to FL10, 250 knots, aircraft clean.
Toliss A321, FL350, 0.78m, Cruise. To Recover I flew to FL10, 250 knots, aircraft clean.

**Comment by Thien42** [comment]
Thank you for your input, we managed to identify some issues with the premium flight restoration that should be fixed in the next update.
