### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by bennetttheboi** [invernyx/smartcars-3-bugs#317]
### Describe the bug

When I bid on an E175 flight with Alaska air, it does not allow me to fly it. It says: No suitable aircraft for this flight

### How do you reproduce this bug?

1. Bid on QXE2212 KSEA to KPDX
2. Go to flight center. 
3. Click fly on QXE2212
4. NO SUITABLE AIRCRAFT.
5.

### Operating system

Windows 10

### Community airline

Alaska 

### smartCARS Version

3

### Plugins installed

Flight map, flight center, simbrief logbook

**Comment by GenericNerd** [comment]
This is an airline-specific issue (specific with phpVMS 7). Please let your VA know about this and have them reach out or open a issue on here so that we can continue this with them :)
