### ISSUE TITLE
[FEATURE] - Minimize to system tray 

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#318]
### Is your feature request related to a problem? Please describe.

Can we get a feature to minimize the acars app to the tray because it makes my taskbar very cluttery i personally dont like many application showing up on my taskbar i have seen with many acars they can be minimized to system tray so if u guys can consider this in the future update 
thank you

### Describe the solution you'd like

Option to minimize to tray 

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Thien42** [comment]
Closing for now, we may revisit in the future
