### ISSUE TITLE
[BUG] - reconnection to network after brief internet loss

### ISSUE THREAD

**Issue by MAC0124-SteveK** [invernyx/smartcars-3-bugs#319]
### Describe the bug

Had a momentary loss of internet connection while on a flight.  SC3 continued to track the flight normally.  Internet service was restored before landing sequence was started.  However, it appeared SC3 didn't properly reestablish connection.  After engine shutdown, button to submit PIREP was available, but when pressed it said the flight could not be submitted due to an error.  Discovered later on the website actually did receive the PIREP even though SC3 produced no indication of submission.  

Screenshot of SC3 showing the error message is attached, along with the combined and error log files.

[combined-2023-08-09.log](https://github.com/invernyx/smartcars-3-bugs/files/12313740/combined-2023-08-09.log)
[error-2023-08-09.log](https://github.com/invernyx/smartcars-3-bugs/files/12313741/error-2023-08-09.log)
![CHR13445 attempt to file PIREP](https://github.com/invernyx/smartcars-3-bugs/assets/131482474/d0732794-44bc-4679-bae4-ce10a32ee85d)

### How do you reproduce this bug?

Unknown how to reproduce.... unplug network cable perhaps?

I'm in a region of the world where internet drops are common... I'm sure I've had internet drops while SC3 was running during prior flights, so no idea what made this particular instance different from the others.

### Operating system

Windows 10 Pro 22H2

### Community airline

Millennium

### smartCARS Version

0.13.0

### Plugins installed

chat, flight center, flight tracking, logbook, map

**Comment by GenericNerd** [comment]
Hi, could you please provide the log for this issue? It would be found in %localappdata%\TFDi Design\smartCARS 3\resources\app\logs.

**Comment by turbofandude** [comment]
Please ensure your API is up to date (we are also releasing an update next week) and let us know if this reoccurs. Until then, I am closing this issue out as stale as we try to close out this list.

**Comment by GenericNerd** [comment]
Since we didn't receive a log, we will be applying a change to the time it takes for a Premium flight to be removed from 30 minutes to 1 hour of inactivity. If you provide those logs, we can look into this further.
