### ISSUE TITLE
[BUG] - Cannot Start a Flight

### ISSUE THREAD

**Issue by CaptainMac2336** [invernyx/smartcars-3-bugs#32]
**Describe the bug**
When I click on the "Flight Center" the options to bid on flights etc. flash on the screen for a split second and then disappear. I am unable to bid on flights or select any flights that I have already bid on because all of the "buttons" etc. disappear immediately and the screen in blank. 

**To Reproduce**
Since no one else is having this issue, I'm not sure you can reproduce it. But...
1. Open SC3
2. Select Flight Center (Airplane Icon)
3. Observe options flashing briefly and then disappearing.

**Expected behavior**
Options to select currently bid flights or to bid on new flights should be available. 

**Screenshots**

https://user-images.githubusercontent.com/127910779/225709421-3cee49ff-9c03-4a3c-885c-32181bb7a4b2.mp4

**System Information (please complete the following information):**
 - OS: Windows 10
 - Community ID: [e.g. 2/any]
 - Version 0.5.6

 - Plugins used: This is using the TFDi Flight Center plugin found here: https://smartcars.tfdidesign.com/central/community

**Additional context**

**Comment by jordanhavard** [comment]
Can confirm this is happening to me too. It looks like the aircraft json isn't being parsed correctly

**Comment by turbofandude** [comment]
@CaptainMac2336 Thank you for the report! The system definitely shouldn't be going blank, but the problem is actually caused by an error coming from your server. The error is:
```
<br />
<b>Warning</b>:  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in <b>/home/macairvi/public_html/core/newSC/0.2.3/handlers/phpvms5/assets/database.php</b> on line <b>12</b><br />
{"message":"Database credentials could not be loaded"}
``` 
@GenericNerd Can I get you to review the above? 

@jordanhavard I'm willing to bet you are also experiencing some web error from the bookings endpoint as well, which breaks the JSON.

Overall, this is definitely an issue, but it seems like it may be more than one combined. We should definitely be validating that server responses are actually JSON, which could cause the blanking issue to go away.

**Comment by GenericNerd** [comment]
> Overall, this is definitely an issue, but it seems like it may be more than one combined. We should definitely be validating that server responses are actually JSON, which could cause the blanking issue to go away.
#33

**Comment by jordanhavard** [comment]
If it helps, I swapped my airport and aircraft responses server side and can see that correct responses returned for both in the airports endpoint (using console log in app) but both aircraft and airport fails when using the aircraft endpoint.

**Comment by GenericNerd** [comment]
@jordanhavard I'm pretty curious as to how you obtained your result. From what I can see, your URL is still set to a tunnel that no longer exists. That may be the cause of your issues

@CaptainMac2336 The issue was a user error (on my side). You should hopefully not have these issues in the future.
