### ISSUE TITLE
[BUG] FFA320 not reporting engine start / stop in smartcars log

### ISSUE THREAD

**Issue by Ezilinx-Craig** [invernyx/smartcars-3-bugs#320]
### Describe the bug

Upon landing at EGLL was unable to submit a Pirep as the system didn't detect engine off.
No engine off appeared in the GUI log viewer.

### How do you reproduce this bug?

I flew the same flight sometime later after a restart, including checked for updates and the same result.
In my testing I noted 
- SC detected the engine on only if XP was configured for engines on start up
- SC did not detect engine start if started by user

After testing flew same route in Zibo 737, SC detected engine start and stop and was able to submit Pirep.

It appears the problem only exists with FF A320 

### Expected behavior

Expected that upon engine shutdown, it appears in the GUI log and the button submit Pirep to appear

### Operating system

Windows 10 22H2

### Community airline

Qantas 

### smartCARS Version

0.13.0

### Plugins installed

flight center, flight tracking

**Comment by Thien42** [comment]
Are you using the fsuipc/xpuipc tracking or x-plane native tracking for your flights?

This can be found in the app settings.

**Comment by Ezilinx-Craig** [comment]
fsuipc tracking, do you want me to try xplane?

**Comment by Thien42** [comment]
It would actually help us a lot if you could.
If this is an issue with xpuipc itself, there won't be much we can do about it unfortunately

**Comment by Ezilinx-Craig** [comment]
Can confirm when using xplane it works :-)

**Comment by GenericNerd** [comment]
Since using the correct tracker seems to have fixed this issue, we will be closing it for now.
