### ISSUE TITLE
[BUG] SC3 disconnects from XP12 during flight 

### ISSUE THREAD

**Issue by Robbo31** [invernyx/smartcars-3-bugs#321]
### Describe the bug

I can sit on the ground for 30-40 mins with no issue. I take off and at any time out of nowhere with no input of any controls, keyboard or mouse the SC3 will disconnect from the simulator. It is totally random and can happen in any stage of flight. The aircraft can fly for hours with no disconnect or the SSC3 will disconnect multiple times within minutes. After disconnect the issue  can suddenly stop and not happen again. Sometimes I get a scenario validation error and can no longer reconnect to the flight in progress.

### How do you reproduce this bug?

Not applicable, happens without external input.

### Expected behavior

Maintain connection to simulator

### Screenshots

[000003.log](https://github.com/invernyx/smartcars-3-bugs/files/12367837/000003.log)
[000003.log](https://github.com/invernyx/smartcars-3-bugs/files/12367841/000003.log)

### Operating system

Windows 11 22H2

### Community airline

Qvirtual

### smartCARS Version

0.13.0

### Plugins installed

Runs through XP12 output, Flight Centre, Flight Tracking, Simbrief

### Additional context

None available

**Comment by Thien42** [comment]
Can you tell me if you are using the XPUIPC or X-Plane native tracking?

**Comment by Robbo31** [comment]
Hi, I am using Xplane native tracking. Can you confirm the XP12 data output port?

**Comment by Thien42** [comment]
Thank you for the information, I will investigate this

**Comment by Robbo31** [comment]
I have tried to add the combined log which shows the errors, hopefully you can work through it: [Error 200 
](error: could not update flight to va with error code 200 and message:  {"code":200,"name":"HttpClientError","response":true,"sourceUri":"flights/update","timestamp":"2023-07-13T00:05:10.192Z"})[combined.log](https://github.com/invernyx/smartcars-3-bugs/files/12377548/combined.log)
