### ISSUE TITLE
Livery not detected by Smartcars

### ISSUE THREAD

**Issue by Robbo31** [invernyx/smartcars-3-bugs#322]
### Is your feature request related to a problem? Please describe.

When I select Fly and Smartcars connects to my simulator, 99% of the time the livery is not found by SC3. The aircraft type is detected but not the livery.

### Describe the solution you'd like

I want SC3 to detect the livery of  the aircraft being used.

### Describe alternatives you've considered

I have tried starting SC3 at different states of aircraft power up.

### Additional context

![Screenshot 2023-08-17 190443](https://github.com/invernyx/smartcars-3-bugs/assets/128005455/39517593-daca-4d8d-8063-2001baba3e71)
![Screenshot 2023-08-17 191224](https://github.com/invernyx/smartcars-3-bugs/assets/128005455/5f195747-e5b6-40f7-80d7-2696d6a28a0f)
As can be seen the liveries are labelled in the folder for the the selected aircraft.

**Comment by GenericNerd** [comment]
Due to technical limitations with the platform, we cannot detect liveries with X-Plane 12.
