### ISSUE TITLE
[BUG] - SimBrief callsign shows up as [object Object]

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#323]
### Describe the bug

The simBrief callsign will show up as [object Object] when the airline field is left blank. This is given a default of N on simBrief, but it does not seem like this carries over.

### How do you reproduce this bug?

1. Create a simBrief flight with **no airline**
2. Bring the flight into smartCARS
3. Start the flight
4. View your incorrect callsign

### Expected behavior

The default callsign should be carried over

### Operating system

Windows 11 22H2

### Community airline

Any

### smartCARS Version

0.13.0.0

### Plugins installed

simbrief, flight-tracking

**Comment by Thien42** [comment]
Will be fixed in the next release
