### ISSUE TITLE
[BUG] - SC3 Crashing unexpectedly during flights.

### ISSUE THREAD

**Issue by SilentDevCoPro** [invernyx/smartcars-3-bugs#327]
### Describe the bug

SC3 quit unexpectedly. 3rd time in 2 days this has happened during long haul flights. The flights are not recoverable when this occurs. This just also occurred on the new build of SC3 for mac and prior build.

Bug report attached from apple.

### How do you reproduce this bug?

Random occurrence during a flight in X Plane 12

### Screenshots

<img width="269" alt="Screenshot 2023-08-29 at 12 19 31 PM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/55455a53-e46c-4f30-a5c0-1aeb83840c84">

### Operating system

M1 Mac, Ventura 13.5

### Community airline

qvirtual

### smartCARS Version

0.14.0

### Plugins installed

Flight Center, Flight Tracking, Simbrief

**Comment by GenericNerd** [comment]
How much RAM do you have available on your Mac?

**Comment by SilentDevCoPro** [comment]
32GB

**Comment by Thien42** [comment]
How far into the flight do the crashes happen? Is it random and can happen at any time or does it usually happen in the same  flight phase?

Would you be able to include the logs located in `/Applications/smartCARS 3.app/Contents/Resources/app/logs`?

**Comment by SilentDevCoPro** [comment]
These were roughly 5-6hrs into the flight they occurred during cruise. Unsure of exact timings.

These are the logs that are available in that location.

[combined-2023-08-29.log](https://github.com/invernyx/smartcars-3-bugs/files/12474170/combined-2023-08-29.log)
[combined-2023-08-30.log](https://github.com/invernyx/smartcars-3-bugs/files/12474171/combined-2023-08-30.log)
[error-2023-08-29.log](https://github.com/invernyx/smartcars-3-bugs/files/12474172/error-2023-08-29.log)
[error-2023-08-30.log](https://github.com/invernyx/smartcars-3-bugs/files/12474173/error-2023-08-30.log)

**Comment by GenericNerd** [comment]
What else are you running on your Mac? How much RAM is in use?

**Comment by GenericNerd** [comment]
Having viewed your log in detail, it seems like the response from the update endpoint for the community that is returning `true`. This is not what smartCARS expects at all and I have a suspicion that this is part of the issue. Can you let your community administrator know of this issue so they can resolve it?

**Comment by jordanhavard** [comment]
> Having viewed your log in detail, it seems like the response from the update endpoint for the community that is returning `true`. This is not what smartCARS expects at all and I have a suspicion that this is part of the issue. Can you let your community administrator know of this issue so they can resolve it?

Looking at the official API, the update response doesn't appear to return anything. What is SC3 expecting, no response at all ? or a 204 response ? Appreciate any guidence

**Comment by GenericNerd** [comment]
> > Having viewed your log in detail, it seems like the response from the update endpoint for the community that is returning `true`. This is not what smartCARS expects at all and I have a suspicion that this is part of the issue. Can you let your community administrator know of this issue so they can resolve it?
> 
> Looking at the official API, the update response doesn't appear to return anything. What is SC3 expecting, no response at all ? or a 204 response ? Appreciate any guidence

Per the OpenAPI spec, there is meant to be a 200 with no response

https://github.com/invernyx/smartcars-3-public-api/blob/0b048e66d85d43a51e35c5344f41f8d6b3199f2f/openapi.json#L555

**Comment by GenericNerd** [comment]
I'm going to be closing this issue as stale for now. If you recreate this crash again when your community has fixed their incorrect update return, please let us know by creating a new issue and referencing it. We'll investigate it further at that point.

**Comment by jordanhavard** [comment]
API has been updated
