### ISSUE TITLE
[BUG] - Livery not recorded in UDP Tracking

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#328]
### Describe the bug

The livery is not being captures alongside the aircraft type in UDP tracking.

**UDP Tracking**
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/bc96c2a4-5a6d-4e0b-a80f-5c83eddb56a4)

**XPUIPC Tracking**
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/70e5a9a1-389c-4adb-8e30-4ce5169cbd32)

### How do you reproduce this bug?

1. Use XPLANE tracking (UDP)

### Expected behavior

The livery should be captured.
This causes a major issue for our VA as we use this information for our systems.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

0.14.0

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by Thien42** [comment]
I have identified the issue and it will be fixed in the next release
