### ISSUE TITLE
[BUG] - Invalid JSON with HTTP 200 Breaks App

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#33]
**Describe the bug**
If an API response is supposed to serve JSON, but serves non-JSON content with a 200 status code, internal APIs treat it as valid and attempt to use it as JSON, causing errors.

**To Reproduce**
1. Identity or temporarily create a broken API (i.e. call echo()/die/etc. early)
2. Access part of smartCARS that uses it
3. You should experience undefined behavior and/or various errors, as the code will not have properly validated the JSON

**Expected behavior**
The system should more strictly verify that responses from the server are actually JSON (at a minimum) and potentially add some type/member field validation.

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: Tested on Mac Air, but presumably applies to any
 - Version: 0.5.6
 - Plugins used: Tested in flight-center, but presumably applies to any

**Comment by GenericNerd** [comment]
@turbofandude I wonder whether this is also an API issue. Could we potentially add a VA server-side configuration that enables or disables errors, overriding the servers existing configuration?
