### ISSUE TITLE
[BUG] - Can't log in to Smartcars3

### ISSUE THREAD

**Issue by liveopenskies** [invernyx/smartcars-3-bugs#330]
### Describe the bug

Hello, when i launch smartCars3 all is white, there is nothing i can click or do. I uninstall and reinstall and it still the same.

### How do you reproduce this bug?

Just by launching the app

### Operating system

Windows 11 Professional 22h2

### Community airline

QVirtual

### smartCARS Version

the latest version i got from TFDI website

### Plugins installed

I dont know i only install the smartCars3 and all run good before

**Comment by GenericNerd** [comment]
Please reinstall smartCARS 3. I think this should fix your issue.

**Comment by liveopenskies** [comment]
Reinstalled it and nothing change, cant use smartCARS 3.
