### ISSUE TITLE
[BUG] - Smartcars3 will not detect the simulator

### ISSUE THREAD

**Issue by natedog60** [invernyx/smartcars-3-bugs#331]
### Describe the bug

As requested from the TDFi site, I am posting this here. Hi, I fly with MSFS2020/FSUIPC7 under walker air. Trying out smart cars 3 and it will not connect as it doesn't detect the sim. I am at the correct airport with neither application running as administrator as the warning error instructed and it still won't connect.

### How do you reproduce this bug?

1. Open flight simulator
2. Have the flight selected with your VA so it populates to SC3
3. Attempt to hit "fly"
4. SC3 gives you an error when it tries to connect

### Expected behavior

It should connect to the plane and simulator and allow you to fly the flight.

### Screenshots

[error-2023-08-31.log](https://github.com/invernyx/smartcars-3-bugs/files/12529193/error-2023-08-31.log)
[error-2023-09-01.log](https://github.com/invernyx/smartcars-3-bugs/files/12529195/error-2023-09-01.log)
[combined-2023-08-31.log](https://github.com/invernyx/smartcars-3-bugs/files/12529196/combined-2023-08-31.log)
[combined-2023-09-01.log](https://github.com/invernyx/smartcars-3-bugs/files/12529198/combined-2023-09-01.log)
![Capture (1)](https://github.com/invernyx/smartcars-3-bugs/assets/144184302/77e252c6-ee0a-4fd0-896b-4b7535e3490d)
![Capture1 (1)](https://github.com/invernyx/smartcars-3-bugs/assets/144184302/3d9cd672-32a9-430f-a200-ccabf73686bf)

### Operating system

Windows 10

### Community airline

Walker Air Transport

### smartCARS Version

The latest one as of 9/1/2023

### Plugins installed

chat, flight center, flight tracking, logbook, map

### Additional context

The screenshots I posted was one showing the error and one showing proof on my taskbar that FSUIPC7 is running

Specs 

Flight Simulator and Version
MSFS2020 latest version as of 9/1/2023

OS
Windows 10

CPU
AMD ryzen 3700X

Graphics Card
NVIDIA GTX 1050ti

RAM
64GB DDR4

**Comment by Thien42** [comment]
Do you have UAC (User Access Control) disabled in Windows?

**Comment by natedog60** [comment]
No I do not. The thing that notifies me if a program might be harmful? That is on as it's important.

**Comment by bgiorgio0506** [comment]
@natedog60 the log shows clearly that you are running your simulator as administrator please try to run the sim without admin permission. 

And let me know if it works ;)

**Comment by GenericNerd** [comment]
As we haven't received a response on whether Giorgio's suggestions fixed the issue, we are going to be closing this issue as stale for now. If you still encounter this, please open a new issue and reference this one in the new issue.
