### ISSUE TITLE
[BUG] - Logbook - Column Header (Premium) Missing

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#333]
### Describe the bug

In the logbook, the "Status" column is not aligned and appears on a separate line:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/53701282-539f-4b86-a503-4d5fe5231f53)

I have seen a screenshot on Discord showing the logbook with an additional column header called "Premium" and having the columns all one a single line as expected.  This column heading does not appear in my SC3.

### How do you reproduce this bug?

Go to the Logbook in SC3.

### Expected behavior

Would expect columns to appear aligned with all column headers appearing as in the following screenshot from the "ask-staff" channel on Discord.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/c56a392c-2c6c-45e0-9eb8-52e0e8952161)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.14.1

### Plugins installed

Chat 0.11.3, Flight Center 0.11.3, Flight Tracking 0.14.2, Logbook 0.13.1, Map 0.10.3, SimBrief 0.11.2

### Additional context

Not sure if the "premium" column heading is tied to user having premium access?

**Comment by GenericNerd** [comment]
That's curious, I'm assuming you have Premium. If not, could you please let us know?

If you do have Premium, please try logging out and then back in to TFDi Design on smartCARS and let me know if this possibly resolves the issue for you as well.

**Comment by bryan737dfw** [comment]
I do **not** have premium.

**Comment by bgiorgio0506** [comment]
This will be fixed in the next update
