### ISSUE TITLE
[BUG] - smartCARS 3 CTD on Selecting VA

### ISSUE THREAD

**Issue by tiggerntatie** [invernyx/smartcars-3-bugs#334]
### Describe the bug

smartCARS 3 window goes away (CTD) when selecting my VA (or after attempting to log in to my VA)

### How do you reproduce this bug?

First time:
Select Walker Air VA
Enter login credentials  (remember me, but no desktop shortcut)
*poof*
Second time:
Select Walker Air VA
*poof*

### Expected behavior

I think I should see the "Pilot Center" screen, or some kind of message telling me why it isn't working.

### Screenshots

I would love to include a log file. Where is it?

### Operating system

Windows 10

### Community airline

Walker Air

### smartCARS Version

There is no visible indication of a version before it goes *poof*

### Plugins installed

don't know

**Comment by bgiorgio0506** [comment]
@tiggerntatie can you provide your logs located at %appdatalocal%\TFDi Design\smartCARS\resources\app\logs

**Comment by tiggerntatie** [comment]
Thanks for responding! Here they are:
[error-2023-09-06.log](https://github.com/invernyx/smartcars-3-bugs/files/12551361/error-2023-09-06.log)
[combined-2023-09-06.log](https://github.com/invernyx/smartcars-3-bugs/files/12551362/combined-2023-09-06.log)

**Comment by GenericNerd** [comment]
Do you know if you have any application running on port `8881`?

**Comment by tiggerntatie** [comment]
No applications are using port 8881.
Firewall policy for smartCARS 3:
![Screenshot 2023-09-07 181339](https://github.com/invernyx/smartcars-3-bugs/assets/343592/6ae51d8a-eb16-45e9-acd4-cfce61fda804)

**Comment by tiggerntatie** [comment]
Based on some googling on the issue, I saw there was a possibility the problem was related to Docker. I have docker installed, but am not currently using it. I uninstalled docker and rebooted. There apparently is an associated hyper-v vEthernet network interface that also disappeared once the reboot completed. Now that Docker is off the system, smartCARS 3 is working as expected.

I'm not sure how you should interpret this observation. I have had Docker installed for the past year, and have had no similar issues with many other networked applications on my machine. I think the issue should be better understood and (I hope) prevented in the future. At the very least, the app should present a meaningful error message before closing.

**Comment by GenericNerd** [comment]
I'm not sure why having Docker installed on your machine would particularly cause this issue. Both myself and @Thien42 use Docker on our development machines and we don't have this issue. Are you able to replicate this by reinstalling Docker with no running containers?

**Comment by GenericNerd** [comment]
I'm going to close this issue, but I'll continue to monitor it and reply when you do
