### ISSUE TITLE
[BUG] - SimBrief plugin does not honor weight units

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#335]
### Describe the bug

When planning a flight on Simbrief, the output is always in KGS, regardless of unit settings.

### How do you reproduce this bug?

1. Set units to LBS
2. Plan a flight on Simbrief
3. Observe KGS in the output

### Expected behavior

Allow me to use Freedom UnitsTM

### Operating system

Windows 11

### Community airline

SCDC (v5 - Production)

### smartCARS Version

0.14.1

### Plugins installed

simbrief@0.11.2

**Comment by Thien42** [comment]
Will be fixed in the next release
