### ISSUE TITLE
[BUG] - logbook does not navigate to PIREP after auto-submission

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#336]
### Describe the bug

After completion of a PIREP, the logbook plugin is activated, but no PIREP is displayed. Instead, it is on the main page with the "Could not find the specified PIREP" notification displayed.

### How do you reproduce this bug?

1. Complete a PIREP
2. Observe reported behavior

### Operating system

Windows 11

### Community airline

SCDC (v5 - Production)

### smartCARS Version

0.14.1

### Plugins installed

logbook@0.13.1,flight-tracking@0.14.2

### Additional context

If needed, the PIREP was N906HJ from EHAM to EDDB on SCDC (v5/prod). The flight was also filed with Premium and I was actively logged in to my TFDi Design account.

**Comment by bgiorgio0506** [comment]
@turbofandude this has been fixed in logbook 0.13.2 (which might still not be in production)
