### ISSUE TITLE
[BUG] - Simbrief plugin UI spacing is off and text is partially unreadable

### ISSUE THREAD

**Issue by turbofandude** [invernyx/smartcars-3-bugs#337]
### Describe the bug

When the SimBrief plugin is open, reducing the size of the window obstructs the top rows. Additionally, the element padding/spacing is uncomfortable and not consistent with the rest of the application.

### How do you reproduce this bug?

1. Open simbrief plugin
2. Plan a flight
3. Observe aforementioned UI bugs

### Operating system

Windows 11

### Community airline

SCDC (v5 - Production)

### smartCARS Version

0.14.1

### Plugins installed

simbrief@0.11.2

### Additional context

See attached image for reference. At this stage, I recommend a refactor and/or rewrite of the layout code as this page has been the source of layout issues more than once.

Reference:
![image](https://github.com/invernyx/smartcars-3-bugs/assets/3858710/2ea32603-9774-4f08-8409-3741e2aae7cf)

**Comment by Thien42** [comment]
Will be fixed in the next release
