### ISSUE TITLE
[BUG] - Flight Center - Clicking on Schedule Header Sorts By Callsign

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#338]
### Describe the bug

In the flight center, when the "schedule" column header is clicked to sort the list by the scheduled time values, it instead sorts the list by the callsign.

### How do you reproduce this bug?

Go to Flight Center.
Click New Bid to display multiple flights in the flight list.
(optional) Sort by any column other than Schedule.
Click the Schedule column header.  List will be sorted (ascending) by callsign.
Click the Schedule column header.  List will be sorted (descending) by callsign.

### Expected behavior

When the Schedule column header is clicked, the list should be sorted by the scheduled departure and arrival times.

### Screenshots

Ascending sort by schedule is sorting ascending by callsign:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/864306de-3c14-4b58-89d7-497021642093)

Descending sort by schedule is sorting descending by callsign:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/76494398-be29-4b20-9d3f-1af25e14c6f1)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.14.1

### Plugins installed

Chat 0.11.3, Flight Center 0.11.3, Flight Tracking 0.14.2, Logbook 0.13.3, Map 0.10.4, SimBrief 0.11.3

**Comment by Thien42** [comment]
Will be fixed in the next release
