### ISSUE TITLE
SmartCars 3 will not Connect to MSFS

### ISSUE THREAD

**Issue by SnowHawk6** [invernyx/smartcars-3-bugs#339]
### Describe the bug

When loaded into MSFS and trying to have SmartCars 3 start tracking the flight, the software keeps attempting to connect until eventually it times me ou. I have ensured administrator is not being ran on MSFS or FSUIPC and even uninstalled and reinstalled FSUIPC. I have attached the logs below from SmartCars 3 along with the screenshot of the screen of SmartCars 3. 

### How do you reproduce this bug?

1. Opened SmartCars 3
2. Logged into VA 
3. Went to flight tracking and noticed it would not connect

### Expected behavior

SmartCars 3 should be able to connect and start tracking flights. 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/145467484/f75ff92b-7746-4918-9430-13792f3fc52c)

[combined-2023-09-19.log](https://github.com/invernyx/smartcars-3-bugs/files/12660979/combined-2023-09-19.log)
[error-2023-09-19.log](https://github.com/invernyx/smartcars-3-bugs/files/12660980/error-2023-09-19.log)

### Operating system

Windows 11

### Community airline

American Virtual

### smartCARS Version

3.0.0

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, and Map

**Comment by GenericNerd** [comment]
It seems there is an error internally that's happening. Do you know whether you're running any application on 7172?

**Comment by SnowHawk6** [comment]
The only applications that are running concurrent with SmartCars is MSFS, Navigraph, SimToolkit Pro, and Pilot Core IVAO.

**Comment by Thien42** [comment]
Can you double check if the tracking provider is set to FSUIPC in the smartCARS settings?

**Comment by SnowHawk6** [comment]
Yes tracking provider is set to FSUIPC in the SmartCars settings

**Comment by GenericNerd** [comment]
Can you try the following commands? You will need an administrative command prompt. To get one, type "Command Prompt" into the search, right click and click "Run as an administrator":

`net stop winnat`
`net start winnat`

Please let me know if this fixes it.

**Comment by GenericNerd** [comment]
Hi @SnowHawk6, has this worked for you? If we don't hear back soon, we will close this issue out as stale

**Comment by SnowHawk6** [comment]
@GenericNerd Hello, sorry for the late reply. The command did not work for this.

**Comment by GenericNerd** [comment]
Can you run the following command?:

`netstat -aon`

And let me know if **any** of the following appear under the `TCP` port section:
`0.0.0.0:7172`
`127.0.0.1:7172`
`::1:7172`
`[::]:7172`
`[::]:1:7172`

**Comment by GenericNerd** [comment]
Closed as stale. If this is still happening, please resubmit this bug.
