### ISSUE TITLE
[BUG] - Altitude value reported incorrectly

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#34]
**Describe the bug**
The `altitude` value that is sent to the API doesn't reflect the correct altitude (or at least requires some conversions). I'm receiving a value of `10587013120` however I'm not sure what's suppose to happen with this value

**To Reproduce**
1. Start flight
2. open dev tools
3. inspect `data` requests

**Expected behavior**
Potentially this will be something that is configured by VAs on what [type of altitude](https://pilotinstitute.com/altitude-types/) they want to send however looking for guidance on what this value is currently representing

**Screenshots**
MFS Aircraft sim info
![image](https://user-images.githubusercontent.com/67948773/226146783-fa283f84-c50c-48b5-a389-e88ab7997634.png)
In smartcars, this is the `data` that is being received from `http://localhost:7172/api/com.tfdidesign.flight-tracking/data`
![image](https://user-images.githubusercontent.com/67948773/226146881-4702a837-f7cc-47c3-94b3-fcf5342b266b.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: 3
 - Version client`0.5.6` api`0.2.3`
 - Plugins used: chat, flight-center, flight-tracking

**Additional context**

**Comment by turbofandude** [comment]
Fixed in 0.5.7
