### ISSUE TITLE
[FEATURE] - Implement `SC3` User agent for VA requests

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#341]
### Is your feature request related to a problem? Please describe.

A recent bug caused a huge spike in traffic from the SC3 to VA servers. 
The user agent was `axios/1.3.5` without any real context. 

### Describe the solution you'd like

To help VA administrators filter out potentialy DDoS attacks, please include something like `SC3` in the user agent, so this can be monitored

### Describe alternatives you've considered

n/a

### Additional context

Screenshot for reference
![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/83e23568-669e-4a8e-8aa5-824d0eb9fbb5)

Discord link for reference
https://discord.com/channels/589851727373795331/589858287004942356/1156422082838667275

SC2 user agent for reference
![image](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/c8ed954b-12d0-47a3-b3f6-38e3f0d27a5c)

___ 

EDIT: 
It appears the login is sending the user agent but not the tracking plugin
![CleanShot 2023-09-27 at 16 47 26](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/e819654c-6758-4ede-97d0-37e039820e7e)

**Comment by jordanhavard** [comment]
SC2 user agent for reference
![CleanShot 2023-09-27 at 16 33 46](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/4b2eea47-6e3a-41a4-a528-c9436a68bbcb)

**Comment by GenericNerd** [comment]
As much as I understand the intention behind this change, there are a couple of things I want to point out:

1. I do not believe this type of issue will occur any time soon. We are aware of the problems that caused this to happen, both in code and through our review processes and we are working on changes internally to ensure that these types of issues never occur again.
2. While all the TFDi Design plugins could do this if another plugin does not, it completely goes against the point of adding it to our plugins in the first place. I do not see this contributing to the overall experience of the program for community administrators or for users of smartCARS
