### ISSUE TITLE
[BUG] - VA traffic not visible on map 

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#342]
### Describe the bug

in the sc3 map when i enable current va traffic i cant see any of my pilots flying 

### How do you reproduce this bug?

1.SC3 MAP 
2.ENABLE CURRENT VA TRAFFIC
3.NO FLIGHTS VISIBLE 

### Expected behavior

current va traffic shhould be visible 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/9fde8be6-9a71-4aae-9921-871b3acfc5b7)

### Operating system

Windows 10 /11

### Community airline

Airlink Virtual 

### smartCARS Version

smart cars 3 latest

### Plugins installed

logbook flight tracking chat simbrief

**Comment by GenericNerd** [comment]
I am not able to reproduce this behaviour. Are you logged in to TFDi Design?

**Comment by EpicHax7** [comment]
negative do we need to be logged in on tfdi  also?

**Comment by GenericNerd** [comment]
You need to be logged in to TFDi Design to appear on the VA map in the first place. This may be why no flights are currently showing.

**Comment by GenericNerd** [comment]
(Accidental close)

**Comment by EpicHax7** [comment]
sure thank you very much

**Comment by GenericNerd** [comment]
Has this resolved your issue?

**Comment by EpicHax7** [comment]
yes sir thank you

**Comment by GenericNerd** [comment]
Amazing!
