### ISSUE TITLE
[BUG] - Plugin icons not visible

### ISSUE THREAD

**Issue by chelinho1** [invernyx/smartcars-3-bugs#343]
### Describe the bug

I have smartcars3 installed but it doesn't work, I even took a printout to see because I can't start the flight
I already uninstalled and reinstalled but it doesn't work and I don't know what to do
no plugins chat map logbook

### How do you reproduce this bug?

[](url)
![Unbenannt](https://github.com/invernyx/smartcars-3-bugs/assets/146431790/c7e7d7e2-f2fb-45e5-ba43-c6de4fa55271)

### Operating system

Windows 11 Home 22H2

### Community airline

QVIRTUAL

### smartCARS Version

3.0.0.0

### Plugins installed

no plugins

**Comment by GenericNerd** [comment]
Can you please delete the following folder with smartCARS closed and re-open it?
`%localappdata%\TFDi Design\smartCARS\resources\app\dist\plugins`


Once the plugins are redownloaded, please let me know whether this has resolved the issue.

**Comment by chelinho1** [comment]
I deleted the plugins folder but nothing still appears

**Comment by GenericNerd** [comment]
What is your smartCARS Version now?

**Comment by GenericNerd** [comment]
This issue is stale and will now be closed.
