### ISSUE TITLE
[BUG] - CTD

### ISSUE THREAD

**Issue by retepetab** [invernyx/smartcars-3-bugs#346]
### Describe the bug

7 Minute from landing Smartcars 3 crashed to desktop.

Would send log file but unsure where to find it

### How do you reproduce this bug?

Has happend beforemainly towards the end of a flight of  approx 1 to 3 hours long 

### Expected behavior

not crashing to desktop

### Operating system

Mac OS Ventura 13.5.2

### Community airline

Q Virtual

### smartCARS Version

0.14.1

### Plugins installed

Flight Centre 1.0.2       Flight Tracing 1.0.5

### Additional context

nothing unusual

**Comment by GenericNerd** [comment]
I've replied on issue #348 so I will close this one as a duplicate.
