### ISSUE TITLE
[BUG] - Flight Tracking "Not Found"

### ISSUE THREAD

**Issue by BigWoody86** [invernyx/smartcars-3-bugs#347]
### Describe the bug

Unable to begin flight with Walker Air VA. When selecting to start flight from Flight Center tab, the Flight Tracking tab shows "Not Found" and a broken image link for the tab symbol. Attempted to complete flight anyway, as perhaps it was just failing to render, but the flight never showed as started on the Walker website. 
![SC3 Bug](https://github.com/invernyx/smartcars-3-bugs/assets/93415035/ba039991-caa6-4c83-9558-1e0d3329f087)

### How do you reproduce this bug?

Open SC3, attempt to select Flight Tracking tab, or start flight from Flight Center tab.

### Expected behavior

If flight is not loaded, SC3 would previously instruct user to start flight from Flight Center, or if started from Flight Center, it would show details from flight sim including speed and location data.

### Screenshots

![SC3 Bug](https://github.com/invernyx/smartcars-3-bugs/assets/93415035/1dffd817-fde4-40b5-a1ce-1d07804aac70)

### Operating system

Windows 10 22H2 

### Community airline

Walker Air Transport

### smartCARS Version

3.1.1

### Plugins installed

Chat 1.0.2., Flight center 1.0.2., Flight Tracking 1.0.5., Logbook 1.1.3., Map 1.1.1., SimBrief 1.0.0.

**Comment by GenericNerd** [comment]
Can you please delete the following folder with smartCARS closed and re-open it?
`%localappdata%\TFDi Design\smartCARS\resources\app\dist`


Once the plugins are redownloaded, please let me know whether this has resolved the issue.

**Comment by BigWoody86** [comment]
Upon deleting \dist folder, smartCARS encountered a javascript error preventing it from running, so I deleted and reinstalled it, now all good—Issue Resolved. I had previously reinstalled SC3 before entering a ticket, but that didn't work. This time it appears to have done the job. THANKS!!
________________________________

**Comment by GenericNerd** [comment]
Glad to hear it's working again! Sorry I initially gave the wrong location!
