### ISSUE TITLE
[BUG] - Crashed PIREPs still auto sending

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#349]
### Describe the bug

We had a pilot whos AC crashed however the flight still auto submitted with SC3

### How do you reproduce this bug?

(assuming)
1. Turn engines off before landing
2. once plane is at complete stop, pirep files

### Expected behavior

The flight is not auto submitted

### Screenshots

![CleanShot 2023-10-04 at 16 26 13](https://github.com/invernyx/smartcars-3-bugs/assets/67948773/8217db17-3989-4ba0-9346-b36c99fad46b)

### Operating system

unsure

### Community airline

QVirtual 

### smartCARS Version

latest

### Plugins installed

flight centre & tracking

**Comment by GenericNerd** [comment]
As this is a third party report, we cannot continue with this exact report. I do believe there is a crash message in the default flight tracking configuration.
