### ISSUE TITLE
[BUG] - Unable to `View/Edit Route` in flight tracking

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#35]
**Describe the bug**
When a flight is being tracked, clicking the `View/Edit route` button doesn't seem to do anything

**To Reproduce**
1. Start flight
2. view flight tracking page
3. click view/edit route

**Expected behavior**
Unsure on expected functionality however I assume its to edit the entered route on the previous page

**Screenshots**
Pic for reference
![image](https://user-images.githubusercontent.com/67948773/226147289-cfe70895-2bd5-45ad-83ed-25c86e0166fb.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: 3
 - Version client`0.5.6` api`0.2.3`
 - Plugins used: chat, flight-center, flight-tracking

**Additional context**

**Comment by turbofandude** [comment]
Fixed in 0.5.7
