### ISSUE TITLE
[BUG] - No .env found

### ISSUE THREAD

**Issue by FroztIkon** [invernyx/smartcars-3-bugs#350]
### Describe the bug

after updating the plugin to 0.3.8 from 0.3.6 and visiting the /smartcars/phpvms7/api/, it gives
no .env found with the correct api version info

### How do you reproduce this bug?

1.upload the newer 0.3.8 version of api
2.attempt to visit web url

### Expected behavior

show no error regarding .env file

### Operating system

windows 10

### Community airline

uavirtual.org

### smartCARS Version

3

### Plugins installed

chat,flight center,flight tracking, logbook,map, simbrief

### Additional context

change enviroment.php
force users/operators/owners/whomever to modify

0.3.8\handlers\phpvms7\enviroment.php from:

`$envFilepath = __DIR__ . '/../../../../../.env';`
 to
`$envFilepath = '/home/user/domain/phpvms/.env';`

set direct path to avoid the no .env file error.

**Comment by GenericNerd** [comment]
This seems to be a weird configuration that you have, rather than an overall rule. Usually, the .env file will be found in the directory as previously provided. This is not a direct bug.
