### ISSUE TITLE
[BUG] - smartCARS 3 Crash Mid-Flight

### ISSUE THREAD

**Issue by helinick84** [invernyx/smartcars-3-bugs#353]
### Describe the bug

Smartcars 3 crashing mid flight on xplane 12 with QVA.  Also giving a message of "exceeded 10 degrees nose down" on takeoff

### How do you reproduce this bug?

Happens on every flight about midway through

### Expected behavior

Shouldn't be crashing

### Operating system

Windows 10

### Community airline

Qvirtual

### smartCARS Version

3.1.1

### Plugins installed

flight center, flight tracking

**Comment by GenericNerd** [comment]
Can you please provide a log with this issue? If possible, can you also get event viewer logs?

**Comment by GenericNerd** [comment]
Since there is no response, I will close this issue as it is stale
