### ISSUE TITLE
[BUG] - smartcars3 

### ISSUE THREAD

**Issue by Easternhops4200** [invernyx/smartcars-3-bugs#355]
### Describe the bug

Hello thank you for your time I was told that I had to report an issue with SmartCars 3 here so here it is I am CEO/ Founder of EasternHops we have used your system for years and using SC2 you never had to shut down your aircraft in order to submit your Pirep but now in SmatCars 3 you have to shut down your aircraft for your Pirep to be filed this did not happen with smartcard 2 and I can't see and be told that if we roll out SC3 that we "easternhops" will lose a lot of pilots that are flying payware airplanes like the PMDG and will have to shut down their plane and restart it to file there pirep Smartcars 3 has to have it so you do not have to restart your aircraft you may have a lot of pilots not liking this feature 

thank Robert aka Pizza EasternHops 
email    easternhops@gmail.com
discord     https://discord.gg/kkDfZXXP

### How do you reproduce this bug?

Fly a flight
Come to a complete stop
Set brakes
Try to file Pirep.

### Expected behavior

smartcars 3 should not require you to shut down aircraft in order to file your pilot report 

### Operating system

windows 10 

### Community airline

easternhops

### smartCARS Version

smartcars 3 

### Plugins installed

all of them

**Comment by GenericNerd** [comment]
This is intentional behavior and not a bug. You would need to file a suggestion instead.

**Comment by Easternhops4200** [comment]
I was told by "Fabio Almeida"  to submit it here and here gave me this link

**Comment by GenericNerd** [comment]
> I was told by "Fabio Almeida" to submit it here and here gave me this link

That is me, but you filed the wrong type. You filed a bug report, not a suggestion. This is incorrect.

**Comment by Easternhops4200** [comment]
sorry about that I am not the best with this gib hub things
