### ISSUE TITLE
[BUG] - repeat of #350 no .env found

### ISSUE THREAD

**Issue by FroztIkon** [invernyx/smartcars-3-bugs#358]
### Describe the bug

No .env file found{"apiVersion":"0.3.8","handler":"phpvms7"}

### How do you reproduce this bug?

1. upload phpvms7 to hosting
2. setup phpvms (import fleet,flights,etc)
3. setup phpvms acars and modules
4. upload sc3 api

 phpvms uploaded to:
 /home/user/phpvms/

phpvms public folder:
/home/user/public_html

SC3 files:
/home/user/public_html/smartcars/

### Expected behavior

find the .env files
login with sc3
retrieve flights and bids

### Operating system

windows 10

### Community airline

uavirtual.org

### smartCARS Version

Latest

### Plugins installed

chat,flight center,flight tracking, logbook,map, simbrief

### Additional context

This is related to a closed post #350. However, it was claimed as invalid, when the steps above show it as a valid phpvms install, sc3 api files are installed according to instructions.

http://vms.uavirtual.org/smartcars/api/phpvms7/

**Comment by Thien42** [comment]
Can you make sure the latest version of phpvms7 is installed?

**Comment by FroztIkon** [comment]
Version provided by phpvms7 installed:
7.0.0-beta.5+230828.61433c

As reported by GitHub:
7.0.0-beta.5 61433c

**Comment by FroztIkon** [comment]
fixed my own issue, please change line 5 from
`$envFilepath = __DIR__ . '/../../../../../.env';`
to
`$envFilepath = __DIR__ . '/../../../../../phpvms/.env';`
