### ISSUE TITLE
[BUG] - Aircraft change does not work

### ISSUE THREAD

**Issue by alexan1252** [invernyx/smartcars-3-bugs#359]
### Describe the bug

Everything works perfectly, only when you choose a flight or reserve a flight, the smartcars sends the flight report with the plane in the flight plan, although I changed the plane there

Example:
VA Flight Plan: MDSD TO SVMI AIRCRAFT 737-800
I make the change from 737-800 to Airbus A320
But when the flight report arrives at the VA, the plane on the flight plan appears and the one I assigned does not appear.

### How do you reproduce this bug?

always, I just hadn't reported it

### Expected behavior

the smartcars would have to make the requested change without problem

### Operating system

windows 11

### Community airline

Caribe Virtual Airlines

### smartCARS Version

3.1.1

### Plugins installed

chat 1.0.3 flight center 1.0.4 map 1.1.2 logbook 1.1.4 flight tracking 1.0.5

**Comment by Thien42** [comment]
Can you make sure the latest version of phpvms7 is installed?

**Comment by Thien42** [comment]
Duplicate https://github.com/invernyx/smartcars-3-bugs/issues/344
