### ISSUE TITLE
[FEATURE] - Format timestamp in flight tracking log

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#36]
**Is your feature request related to a problem? Please describe.**
When looking at the flight log inside the smartcars application, Its hard to decode and a glance when each event happened

**Describe the solution you'd like**
Something similar to smartcars 2 (however display the date if flying over midnight for example)

**Describe alternatives you've considered**

**Additional context**
screenshot for reference
![image](https://user-images.githubusercontent.com/67948773/226147843-105c7a03-acca-4266-890b-3b537bc7fbbe.png)

**Comment by GenericNerd** [comment]
This is done because of the format we are outputting the timestamp. I'm sure this is something that we can do to make it more user friendly for sure.

**Comment by turbofandude** [comment]
Fixed in 0.5.7
