### ISSUE TITLE
[BUG] - Flight time displayed as Hours instead of minutes or HRS::MM

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-bugs#360]
### Describe the bug

We are using php vms 7 latest build with sc3 
the flight time in acars is shown as hours not minutes or hours and minutes 
vms 7 takes time data in minutes rather than hours but sc3 is unable to display it correctly 
thank you

### How do you reproduce this bug?

go to sc3
search for flights 
flight time in hours like 70h and 80 h

### Expected behavior

flight time should show as 70 minutes not 70 h 

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/117974892/7891d765-ee43-4eb3-bef7-cb07a66f3448)

### Operating system

Windows 11/10

### Community airline

Airlink Virtual

### smartCARS Version

Latest

### Plugins installed

all

**Comment by GenericNerd** [comment]
How is this shown in the database?

**Comment by EpicHax7** [comment]
in minutes according to the php vms 7 format

**Comment by GenericNerd** [comment]
Is it 70 minutes in the database, or 70 hours?

**Comment by EpicHax7** [comment]
Php vms 7 asks us to input flight time in minutes so its 70 minutes which should be shown as 1 hour 10 minutes as it is on our crew center

**Comment by EpicHax7** [comment]
@GenericNerd any updates on this?

**Comment by GenericNerd** [comment]
> @GenericNerd any updates on this?

Can you try using the new phpVMS 7 API and see if this resolves your issue?

**Comment by EpicHax7** [comment]
negative we are using the latest 0.4.4 api and 0.4.3 phpvms 7 smart cars native 
still no luck it shows us in hours like 454 hours

**Comment by EpicHax7** [comment]
As phpvms 7 asks us to upload the time in minutes in the excel sheets and then display it as hours and minutes 
it should also be read by Smart cars but instead it just shows the minutes without converting it to HH::MM @GenericNerd

**Comment by BossOfGames** [comment]
https://github.com/invernyx/smartcars-3-phpvms7-api/pull/9 fixes this issue

**Comment by GenericNerd** [comment]
Resolved by the latest API version. Please update and try again.
