### ISSUE TITLE
[BUG] - Position Reports Not Stopping on Simulator Crash

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#362]
### Describe the bug

If a simulator CTD occurs, smartCARS does not detect and stop the position reports. It did this in smartCARS 2.

I had a pilot who started a flight yesterday in MSFS, had a CTD while gone from home, and did not get back until nearly 24 hours later (that's not for debate.) I have 5,765 position reports from him -- on a larger scale this can be a problem and lead to unnecessary database consumption.

### How do you reproduce this bug?

1. Start a flight.
2. Intentionally drop the simulator
3. Watch the position reports continue until you close smartCARS 3.

### Expected behavior

If a simulator crashes to the desktop, the application should cease sending position reports and notify the pilot of the disconnect. This was the behavior in smartCARS 2.

### Screenshots

11/4 19:48 UTC to 11/5 19:55 UTC
![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/f4421a07-9f14-45c6-ac31-a01b7e839d7e)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by walkerairtrans** [comment]
Update; pilot got home and the app said it lost connection but the position reports did not stop. At the end we had over 7000 entries in the database from him.

**Comment by GenericNerd** [comment]
> Update; pilot got home and the app said it lost connection but the position reports did not stop. At the end we had over 7000 entries in the database from him.

Do you know whether it kept the same data as to before the crash, or whether it went to default values?

**Comment by walkerairtrans** [comment]
> > Update; pilot got home and the app said it lost connection but the position reports did not stop. At the end we had over 7000 entries in the database from him.
> 
> Do you know whether it kept the same data as to before the crash, or whether it went to default values?

Let me recreate it -- I didn't think to grab the database dump and I don't keep bad position reports beyond a few weeks.

**Comment by walkerairtrans** [comment]
> > Update; pilot got home and the app said it lost connection but the position reports did not stop. At the end we had over 7000 entries in the database from him.
> 
> Do you know whether it kept the same data as to before the crash, or whether it went to default values?

Here you go, video showing it -- I launched the plane and then after a bit I killed MSFS. You can see as I refresh it's still sending position reports and it's using the same data over and over.

![image](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/bc7aceb7-5de5-4cc5-8f63-36ccae14ee63)

Video as well if you need it.

https://github.com/invernyx/smartcars-3-bugs/assets/127605985/5faee4ee-4b1b-4b54-9c63-c6779f7d1d03

**Comment by GenericNerd** [comment]
Alright, that gives me an idea about what is happening, thanks for the report!

**Comment by Thien42** [comment]
Will be fixed in the next release
