### ISSUE TITLE
[BUG] - "How are you flying?" screen using Dark Mode Community logo in Light Mode

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#364]
### Describe the bug

When using the mentioned screen, it's using the darkmode logo.

### How do you reproduce this bug?

1. Enable light mode
2. Launch smartCARS after Community Loaded

### Expected behavior

Use of the light mode logo for last community.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/d2557f13-eb9f-432d-adf5-2b4111b33604)

### Operating system

Windows 11

### Community airline

Spark Virtual Airlines

### smartCARS Version

3.1.1

### Plugins installed

phpvms7-native-flight-center, logbook, chat, flight-tracking

**Comment by GenericNerd** [comment]
Thanks for reporting this, we'll look into getting this fixed ASAP

**Comment by Thien42** [comment]
Will be fixed on the next release
