### ISSUE TITLE
[FEATURE] - Pause State in Position Reports

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#365]
### Is your feature request related to a problem? Please describe.

Not really, just useful to provide a PAUSE status on live maps.

### Describe the solution you'd like

The simulator already detects/logs pause in the app log -- make a status for "pause" and switch to it and then return to the previous status when the user un-pauses the sim.

### Describe alternatives you've considered

None

### Additional context

N/A

**Comment by Thien42** [comment]
Will be added in the next release

**Comment by walkerairtrans** [comment]
@Thien42 @GenericNerd did this ever get implemented? I have yet to see a pause state come through on any of our pilots.
