### ISSUE TITLE
[BUG] - Refresh Flight Center does not update Route Box

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#367]
### Describe the bug

If a route is appended to a flight by the website, the refresh button does not update the route box with the new data.

### How do you reproduce this bug?

I just bid on this flight. It has no flight level or route.

![smartcars3_iGMzL5jjfr](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/6cc4a09a-163f-4bf6-b89f-4f5659c5f410)

I update the bid to now have a flight level/route on the website. I click refresh on Flight Center. Only the flight level is now updated and route box remains blank.

![smartcars3_IsRM8SIVgY](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/d2921eca-a278-47d5-81ad-643e80655769)

I go to Chat and then back to Flight Center and now the bid shows both flight level and route.

![smartcars3_sAeOccyfkK](https://github.com/invernyx/smartcars-3-bugs/assets/127605985/c0701ac6-06cd-4de3-bc32-8da7920bd01d)

### Expected behavior

If I click refresh bids, it should update all data. This was an issue in the alpha and it was corrected, however it seems the behavior is now back again.

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

3.1.1

### Plugins installed

chat, map, flight center, flight tracker, logbook

**Comment by GenericNerd** [comment]
I can recreate this bug, is there a case where you are updating the route field extremely often or is it just a "nice to have" rather than a "need to have"? If there's a good reason, I'm willing to bump the priority of this issue up for sure!

**Comment by walkerairtrans** [comment]
I find it more of, if I click refresh, then I would expect it all to update. I wouldn't call it high priority but it should still be fixed at some point. :)

**Comment by GenericNerd** [comment]
> I find it more of, if I click refresh, then I would expect it all to update. I wouldn't call it high priority but it should still be fixed at some point. :)

Agreed :)

**Comment by Thien42** [comment]
Will be fixed in the next release
