### ISSUE TITLE
[FEATURE] - Automatic PIREP submission default to OFF

### ISSUE THREAD

**Issue by dcherrie** [invernyx/smartcars-3-bugs#368]
### Is your feature request related to a problem? Please describe.

Since the introduction of the automatic PIREP submission and being defaulted to ON without users knowledge, many PIREPs are being submitted that shouldn't be submitted. This includes aircrafts that have crashed but also the main issue is when people go back to the main menu with smartCARS still running at any stage, this includes without landing will then be filed.

### Describe the solution you'd like

Either make automatic PIREP submission default to off or included better conditions to stop PIREPs filing when flights are obviously not complete, such as if the aircraft is not at the destination then it should not automatically file.

### Describe alternatives you've considered

We have over a thousand rejected PIREPs because of pilots not knowing about automatic PIREP submission and starting a flight, then cancelling then having it automatically submitted because the submission thinks the flight is complete even though the plane has not landed but just gone back to the main menu.

### Additional context
QVirtual staff member

**Comment by walkerairtrans** [comment]
Totally support this too! It's getting really irritating on my side with all these erroneous PIREPS being submitted. I run a SUPER lean staff and we are not here to manage 3k pilots. I had to build and implement a 72-hour delete option to combat this.

**Comment by GenericNerd** [comment]
Hey guys, can you provide me a list of scenarios that cause these erroneous PIREPs? I have yet to experience one myself with many flights performed with smartCARS 3, but I'm not discounting the possibility and need more information so that I can try and see if we can resolve it so it can stay on, rather than turn it off by default.

**Comment by walkerairtrans** [comment]
> Hey guys, can you provide me a list of scenarios that cause these erroneous PIREPs? I have yet to experience one myself with many flights performed with smartCARS 3, but I'm not discounting the possibility and need more information so that I can try and see if we can resolve it so it can stay on, rather than turn it off by default.

If a pilot crashes their plane while away from the computer, PIREP gets submitted as it detects the landing.

If a pilot goes to MSFS main menu for any reason and forgets they started a flight, it will automatically detect a landing and submit. I don't know what it is with MSFS main window but it somehow triggers SC3 into thinking you landed.

**Comment by dcherrie** [comment]
Agree with @walkerairtrans for those scenarios. The MSFS main menu actually puts the aircraft at 0 degrees LAT and LONG so essentially acts like a teleport which is why there is a landing rate and the engines change from on to off because that is where the hangar simulation is for the background in the menu.

@GenericNerd, basically the automatic PIREP submission should only submit the PIREP if the aircraft has landed at the correct airport. If smartCARS triggers the message "On ground X nm from planned arrival airport" at all in the log then it should not automatically file.

**Comment by dcherrie** [comment]
Any updated on this having this fixed? In the past 2 weeks we have had over 200 PIREPs of flights that have fallen under this issue.

**Comment by GenericNerd** [comment]
> > Hey guys, can you provide me a list of scenarios that cause these erroneous PIREPs? I have yet to experience one myself with many flights performed with smartCARS 3, but I'm not discounting the possibility and need more information so that I can try and see if we can resolve it so it can stay on, rather than turn it off by default.
> 
> If a pilot crashes their plane while away from the computer, PIREP gets submitted as it detects the landing.
> 
> If a pilot goes to MSFS main menu for any reason and forgets they started a flight, it will automatically detect a landing and submit. I don't know what it is with MSFS main window but it somehow triggers SC3 into thinking you landed.

If the plane crashes, the flight is not auto-submitted from my testing (accidental testing, but testing regardless). I can see your other case being an issue that occurs, but it is incredibly hard to detect.

**Comment by GenericNerd** [comment]
> Agree with @walkerairtrans for those scenarios. The MSFS main menu actually puts the aircraft at 0 degrees LAT and LONG so essentially acts like a teleport which is why there is a landing rate and the engines change from on to off because that is where the hangar simulation is for the background in the menu.
> 
> @GenericNerd, basically the automatic PIREP submission should only submit the PIREP if the aircraft has landed at the correct airport. If smartCARS triggers the message "On ground X nm from planned arrival airport" at all in the log then it should not automatically file.

I don't agree with you that this should be the case. If a pilot actively lands at another airport, they have still landed, and they still shut off their engines. That is still a complete flight which would be filed under those circumstances you have given.

**Comment by dcherrie** [comment]
@GenericNerd In MSFS, if the plane crashes because it has run out of fuel (engines are off and it slams into the ground) or the user goes back to the main menu (because of how the main menu works is that it changes the state of the aircraft to be in the hangar in the background at 0,0), in both scenarios the PIREP automatically files.

I can provide you with thousands of cases in the past few months of this reliably happening, all in MSFS.

I'd also add that if an pilot actively lands at another airport, they would still need to explain this decision in the PIREP comments as to why, which they wouldn't have the chance to do if it auto-files.

**Comment by dcherrie** [comment]
@GenericNerd any update?

**Comment by GenericNerd** [comment]
> @GenericNerd any update?

No update at the moment, the focus is wholly on the MD-11 at the moment.

**Comment by bgiorgio0506** [comment]
Hey guys sorry to brake into the convo here I was looking at the code today as I had time... I would like to have a couple of more info because we technically have crash support in code: 
1. Does your log show `Aircraft crashed` message (assuming you have it set in the log config)?
IF YES
The current behaviour  is that the smartcars will show the submit button. 
IF NO 
I am ssuming it detect landing and subsequent `DEBOARDING ` state is it true? 

The current logic activate AutoFile attempt only at `DEBOARDING` if is set to true in settings

**Comment by walkerairtrans** [comment]
> Hey guys sorry to brake into the convo here I was looking at the code today as I had time... I would like to have a couple of more info because we technically have crash support in code:
> 
> 1. Does your log show `Aircraft crashed` message (assuming you have it set in the log config)?
>    IF YES
>    The current behaviour  is that the smartcars will show the submit button.
>    IF NO
>    I am ssuming it detect landing and subsequent `DEBOARDING ` state is it true?
> 
> The current logic activate AutoFile attempt only at `DEBOARDING` if is set to true in settings

None of these have a crash message; they all show landed. Usually the FPM recorded is like 20k fpm. And it’s usually the ran out of fuel and engines cut.

**Comment by bgiorgio0506** [comment]
Do you guys fly with damages or crash enabled ?

**Comment by dcherrie** [comment]
@bgiorgio0506 In MFS for VAs, everyone flies with damage and crashed disabled seeing how unstable the detection is. You could be taxiing after an 18 hour flight and have a tiny bump or hit an invisible collision object that will make you lose a flight.

This is the latest PIREP which was automatically submitted and below is the log. You can see the plane overflown their destination, run out of fuel, engines have flamed out and gradually fell back to earth landing in the ocean. We get several of these a day from our pilots.

The easiest solution is to simply not automatically file if the "On ground x nm from planned airport" is triggered. It gives them an opportunity to also fill out a comment as to why they didn't land at their destination.

09:27:41 | Using Microsoft Flight Simulator
09:27:41 | Flying PMDG 737-800 Qantas (VH-VXM \| 2021 \| Mount Hotham)
09:27:41 | Aircrafts weights: DOW: 41413kgs FOB: 6803kgs ZFW: 62732kgs
09:27:41 | Now boarding
09:29:09 | Engine 1 On
09:29:45 | Engine 2 On
09:31:29 | Pushing back with 6775 kgs of fuel
09:33:19 | Flaps set to 13% at 14 kts
09:33:27 | Flaps set to 25% at 14 kts
09:33:31 | Flaps set to 38% at 14 kts
09:33:54 | Taxiing out
09:36:13 | Taking off at heading 168, wind 270 at 15 kts
09:36:37 | Climbing at 171 kts, 8 degrees pitch, -0 degrees bank
09:36:41 | Gear lever raised at 183 kts
09:36:46 | Flaps set to 25% at 194 kts
09:36:50 | Flaps set to 13% at 201 kts
09:36:57 | Flaps set to 0% at 212 kts
10:01:25 | Cruising at 37000 ft
10:45:33 | Bank exceeded 35 degrees
11:47:00 | Engine 1 Off
11:47:00 | Engine 2 Off
11:47:24 | Pitch exceeded 10 degrees nose down
11:47:25 | Descending with 496 nm to go
11:47:34 | Overspeeding at 299 kts
11:47:39 | Reached maximum speed of 357 kts
11:48:22 | Exited overspeed at 77 kts
11:48:24 | Reached 450 kts below 10,000 feet
11:48:25 | Touched down at -1887 fpm, 1.3g, 14 kts, 5 degrees pitch, -0 degrees bank, wind 113 at 23 kts with 158 kgs of fuel (6617kgs in flight)
11:48:25 | On ground 501 nm from planned arrival airport
11:48:27 | Taxiing to gate, landed in 0 m

<img width="325" alt="image" src="https://github.com/invernyx/smartcars-3-bugs/assets/22925698/8cdb88cf-7a11-4ca6-866e-29c2c0fa21ce">

**Comment by bgiorgio0506** [comment]
> @bgiorgio0506 In MFS for VAs, everyone flies with damage and crashed disabled seeing how unstable the detection is. You could be taxiing after an 18 hour flight and have a tiny bump or hit an invisible collision object that will make you lose a flight.
> 
> This is the latest PIREP which was automatically submitted and below is the log. You can see the plane overflown their destination, run out of fuel, engines have flamed out and gradually fell back to earth landing in the ocean. We get several of these a day from our pilots.
> 
> The easiest solution is to simply not automatically file if the "On ground x nm from planned airport" is triggered. It gives them an opportunity to also fill out a comment as to why they didn't land at their destination.
> 
> 09:27:41 | Using Microsoft Flight Simulator 09:27:41 | Flying PMDG 737-800 Qantas (VH-VXM | 2021 | Mount Hotham) 09:27:41 | Aircrafts weights: DOW: 41413kgs FOB: 6803kgs ZFW: 62732kgs 09:27:41 | Now boarding 09:29:09 | Engine 1 On 09:29:45 | Engine 2 On 09:31:29 | Pushing back with 6775 kgs of fuel 09:33:19 | Flaps set to 13% at 14 kts 09:33:27 | Flaps set to 25% at 14 kts 09:33:31 | Flaps set to 38% at 14 kts 09:33:54 | Taxiing out 09:36:13 | Taking off at heading 168, wind 270 at 15 kts 09:36:37 | Climbing at 171 kts, 8 degrees pitch, -0 degrees bank 09:36:41 | Gear lever raised at 183 kts 09:36:46 | Flaps set to 25% at 194 kts 09:36:50 | Flaps set to 13% at 201 kts 09:36:57 | Flaps set to 0% at 212 kts 10:01:25 | Cruising at 37000 ft 10:45:33 | Bank exceeded 35 degrees 11:47:00 | Engine 1 Off 11:47:00 | Engine 2 Off 11:47:24 | Pitch exceeded 10 degrees nose down 11:47:25 | Descending with 496 nm to go 11:47:34 | Overspeeding at 299 kts 11:47:39 | Reached maximum speed of 357 kts 11:48:22 | Exited overspeed at 77 kts 11:48:24 | Reached 450 kts below 10,000 feet 11:48:25 | Touched down at -1887 fpm, 1.3g, 14 kts, 5 degrees pitch, -0 degrees bank, wind 113 at 23 kts with 158 kgs of fuel (6617kgs in flight) 11:48:25 | On ground 501 nm from planned arrival airport 11:48:27 | Taxiing to gate, landed in 0 m
> 
> <img alt="image" width="325" src="https://private-user-images.githubusercontent.com/22925698/319194558-8cdb88cf-7a11-4ca6-866e-29c2c0fa21ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTgwODcsIm5iZiI6MTcxMjU5Nzc4NywicGF0aCI6Ii8yMjkyNTY5OC8zMTkxOTQ1NTgtOGNkYjg4Y2YtN2ExMS00Y2E2LTg2NmUtMjljMmMwZmEyMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE3MzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYzdmZDNlZmNhN2UyZTNlNjVkYmQ2ZWE0YzA5ODEzZDgwNGQzOTc2ZDY0ZWQ0NWYwMWQ3MGExOGZhNzk1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Xzshrm_NIpE6cem6xiTftQ87yV7m1i0yWFdw5EDZc4">


I see what is happening MSFS or P3D send the crash event only if you have it anabled and I agree is not optimal to have it anbled will workout something

**Comment by dcherrie** [comment]
> I see what is happening MSFS or P3D send the crash event only if you have it anabled and I agree is not optimal to have it anbled will workout something

@bgiorgio0506 thank you!

**Comment by Thien42** [comment]
This will be changed in the next release. However due to how the system works we can't force a settings update for existing installations, existing users will still need to change the setting manually.

New users will have setting off by default.
