### ISSUE TITLE
[BUG] - Marking the route of the plane on the map

### ISSUE THREAD

**Issue by jftejeiro** [invernyx/smartcars-3-bugs#369]
### Describe the bug

1.- Buy smartCARS 3 for one month as a test driver. After making two flights, the number of flights made or the sum of hours made does not appear.
2.- I think it would be of interest if on the smartCARS 3 map during the flight, the route segment flown and the remaining route segment to the destination could be shown with a line by clicking on the plane.
For example, a straight line would be shown between the airport of origin and destination in one color, and a line in another color, with the actual route that the aircraft is taking.
If the flight plan is imported from simbrief, it would be interesting for the route points to appear marked with their names on the line that marks the route on the map.
Thank you
Marking the route of the plane on the map

### How do you reproduce this bug?

Upon completion and completion of the flight

### Expected behavior

I think that after completing the flight, the number of hours and flights completed should appear in mni smartCARS 3. I attach a screenshot that shows the Landing rate, but the hours and flights carried out are not visible.

### Screenshots

<img width="260" alt="Captura de pantalla 2023-12-29 123525" src="https://github.com/invernyx/smartcars-3-bugs/assets/38476851/ee5af48b-22a7-41e6-a10b-8da8d998bd57">

### Operating system

Windows 11

### Community airline

smartCARS 3 Only as a pilot without an airline

### smartCARS Version

I can't find the version number, I understand it is the latest

### Plugins installed

Flight Tracking, chat, simbrief,Flight Center Logbook, Fleet manager

**Comment by GenericNerd** [comment]
This is now resolved.
