### ISSUE TITLE
Aircraft Selection List Not Sorting Correctly 

### ISSUE THREAD

**Issue by RandyD59** [invernyx/smartcars-3-bugs#370]
### Describe the bug

In the Flight Center the aircraft selection dropdown is not sorted alphabetically. Note: If you are creating a new flight (charter), the aircraft selection list sorts properly. 

### How do you reproduce this bug?

1.	Open the client and click the Flight Center.
2.	Select any flight you have added to your flights list and click the aircraft dropdown.
3.	View flights not sorted correctly.

### Expected behavior

Should sort the aircraft list as it does in Create Flight and New Flight dropdowns

### Screenshots

![Not Sorting Correctly](https://github.com/invernyx/smartcars-3-bugs/assets/9601781/08144d6c-3f48-4ab9-8082-2841c5938064)
![Sorting Correctly](https://github.com/invernyx/smartcars-3-bugs/assets/9601781/8e73adfc-2467-4bab-bff6-8b09ff589d6e)

### Operating system

Windows 11 23H2

### Community airline

Fly Virtual

### smartCARS Version

API 0.3.9. Flight Center plugin 1.0.4

### Plugins installed

Chat, flight center, flight tracking, logbook map, and simbrief

### Additional context

Should be a straightforward fix just by applying the same sort code used in create flight and new (search schedules).

It’s really nice to have this selection feature as airlines often use different aircraft on the same schedule from one day to next.

**Comment by Breenild** [comment]
I have the same issue.
Is there any fix available?

**Comment by Thien42** [comment]
Will be fixed with https://github.com/invernyx/smartcars-3-phpvms5-api/pull/110 https://github.com/invernyx/smartcars-3-bugs/issues/370
