### ISSUE TITLE
[BUG] - Flight Center - Flight Times are Not Correct

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#372]
### Describe the bug

On the flight tracking flight display, the flight time that is displayed is not correct.  The hours appear to be good, but the minutes are wrong.

### How do you reproduce this bug?

1. Go to flight center.
2. Display flights from schedule.

### Expected behavior

The flight time (hours : minutes) should be correct.

### Screenshots

SC3 (Incorrect):
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/fdc5bfed-8a02-4133-b23e-0da6d8c60482)

SC2 (Correct):
![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/2dafd285-0332-4ec9-973e-a1faef3e4de9)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

3.1.1

### Plugins installed

Chat 1.0.3, Flight Center 1.0.4, Flight Tracking 1.0.6, Logbook 1.1.4, Map 1.1.3, SimBrief 1.0.0

### Additional context

phpVMS 5

**Comment by GenericNerd** [comment]
From what I recall, the schedule times are provided by phpVMS itself. Can you confirm that the times are provided correctly for those schedules?

**Comment by bryan737dfw** [comment]
I should have been more clear with my wording.  The issue is the duration.  The departure and arrival times are correct, but the flight duration is not correct.  After doing some math, it looks like you may be multiplying the minutes by 60?  I believe the flight time is stored as a float, and the decimal is the number of minutes.  So, if you have a flight duration of 6 hours and 14 minutes (i.e.: 6.14), it looks like you are doing .14 * 60 rather than .14 * 100.

**Comment by bryan737dfw** [comment]
Hoping to bump this one as it is still an issue.  The flight DURATION shown in the list is not correct.  See my comment from 1/30 for additional details of the issue.

**Comment by Thien42** [comment]
This will be fixed in the API, see: https://github.com/invernyx/smartcars-3-phpvms5-api/pull/109
