### ISSUE TITLE
[BUG] - Flight Tracking Didn't Detect Takeoff

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#373]
### Describe the bug

One of our users experienced an issue where he flew the whole flight, however smartCARS got stuck in the Taxi state for the entire flight.

### How do you reproduce this bug?

1. Start a flight like normal
2. May be related to MSFS and the Learjet 35A

### Expected behavior

Flight States would properly show the states changed, however they have not.

### Screenshots

The following is screenshots of the user's logs after the flight was completed, and he couldn't submit the flight.

![Screenshot_2024-01-16_101810](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/557f0de2-8a46-4fe7-aa43-f40e914d98d9)
![Screenshot_2024-01-16_101653](https://github.com/invernyx/smartcars-3-bugs/assets/2882332/eca06054-98cd-4780-9332-7d645867e303)

### Operating system

N/A

### Community airline

Spark Virtual Airlines

### smartCARS Version

3.1.1

### Plugins installed

phpvms7-native-flight-center, logbook, chat, flight-tracking

### Additional context

I have attached the complete telemetry as reported to the server for the entire duration of the PIREP.
[ErrorPirepTelemetry.csv](https://github.com/invernyx/smartcars-3-bugs/files/13964275/ErrorPirepTelemetry.csv)

**Comment by GenericNerd** [comment]
Has this happened since?

**Comment by BossOfGames** [comment]
I don't think it has, but that user has not flown in a while either.

I will check with them.

**Comment by GenericNerd** [comment]
I'll close this since there hasn't been a reply, but feel free to mention me and I'll reopen this if you get a response.

**Comment by BossOfGames** [comment]
Hey this actually came up with another pilot yesterday. Their hours logged as 0 when they flew the whole flight according to the telemetry I have.

This seems to be a once in a blue moon type of problem. They were using MSFS.
