### ISSUE TITLE
[BUG] - Incorrect simulation scenario: not on ground

### ISSUE THREAD

**Issue by Miguelitoxxx** [invernyx/smartcars-3-bugs#375]
### Describe the bug

This problem only happens when I try to do a flight with Flight Factory 763. I have several other aircrafts and this problem doesnt exist. I'm assuming that the plane has something different that doesnt allow the smartCARS to detect it is on the ground. Could you do something to solve this?

Flight Simulator and Version
X-Plane 11 - Lastest Version

OS
Windows 11

CPU
13th Gen i5-13600KF

Other details
error: Failed to call local API {"endpoint":"api/credentials/retrieve/tfdidesign","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"[http://localhost:7172/api/credentials/retrieve/tfdidesign","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request](http://localhost:7172/api/credentials/retrieve/tfdidesign%22,%22xsrfCookieName%22:%22XSRF-TOKEN%22,%22xsrfHeaderName%22:%22X-XSRF-TOKEN%22%7D,%22message%22:%22Request) failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n at [http://localhost:7172/app/static/js/main.9b2a3464.js:2:233847\n](http://localhost:7172/app/static/js/main.9b2a3464.js:2:233847/n) at XMLHttpRequest.d ([http://localhost:7172/app/static/js/main.9b2a3464.js:2:233995)","status":404},"timestamp":"2024-01-29T00:16:22.725Z"](http://localhost:7172/app/static/js/main.9b2a3464.js:2:233995)%22,%22status%22:404%7D,%22timestamp%22:%222024-01-29T00:16:22.725Z%22)} **error: Incorrect scenario {"data":"not on ground","timestamp":"2024-01-29T00:**16:38.645Z"} error: Incorrect scenario {"data":"not on ground","timestamp":"2024-01-29T00:18:20.930Z"} error: Failed to call local API {"endpoint":"api/credentials/retrieve/tfdidesign","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http"],"data":"{}","env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","params":{},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"[

Graphics Card
RTX 4060 Ti

RAM
16

### How do you reproduce this bug?

Just using FF 767 and trying to use smartcars 3

### Operating system

11

### Community airline

United Airlines

### smartCARS Version

Can't find

### Plugins installed

every plugin available

**Comment by GenericNerd** [comment]
@Thien42 Can you look into this with one of the default aircraft in XP-11 please?

**Comment by GenericNerd** [comment]
For transparency, @Thien42 is currently away and it may take a while before this issue can be verified. It is possible that the aircraft you are using doesn't correctly report it's variables to FSUIPC. Can you try using the X-Plane tracking provider (you can switch this in the settings of smartCARS)

**Comment by Thien42** [comment]
If this issue is only happening on the FF 763 then I won't be able to test it.

Please try to go into the settings and change the tracking provider to X-Plane if you haven't already.
