### ISSUE TITLE
[BUG] - NOT counting the PAX Fares in phpvms7  

### ISSUE THREAD

**Issue by Luxuryceo** [invernyx/smartcars-3-bugs#376]
### Describe the bug

Smartcars 3  IS NOT counting the PAX Fares in phpvms7  

### How do you reproduce this bug?

book a flight on phpvms7  do the flight with smartcars  and file it  then accept it in phpvms7 and check the pirep you will see that its a -£/-$ in red with a count of a loss 

### Expected behavior

we exprected the software to work the same as VMSAcars  and count the PAX/ CArgo Fares that come with phpvms7 

### Screenshots

![phpvms7 PAX fares](https://github.com/invernyx/smartcars-3-bugs/assets/63414496/4ae51d7c-1652-4260-b248-cf1d1a785c4f)
![SC3](https://github.com/invernyx/smartcars-3-bugs/assets/63414496/b3fa16f2-bf35-4893-a8d9-6e2c67ccfedb)
![VMSAcars](https://github.com/invernyx/smartcars-3-bugs/assets/63414496/d3ff86bf-c0b5-47a4-9f5a-d1424c99e846)
![SC3 1](https://github.com/invernyx/smartcars-3-bugs/assets/63414496/ce2e1615-4876-4a1c-8b37-d4f69561d8b3)

### Operating system

Windows 11 22H2

### Community airline

Luxury Airways Virtual

### smartCARS Version

0.8.0.2

### Plugins installed

chat, logbook, Flight Tracking, Map , Flight Center

### Additional context

we are looking to either get this fixed or cancelling our Smartcars 3  and i dont think you want us to cancel it

**Comment by GenericNerd** [comment]
@BossOfGames is this something that you're aware of?

**Comment by BossOfGames** [comment]
> @BossOfGames is this something that you're aware of?

Yes, it's complicated...

Fares are not required in the POST request to the built-in `prefile` API endpoint which normally is what's used to check if the system is ready to start the flight, create the pirep, and have everything in place to start receiving ACARS data, so I completely missed it when I was originally developing my original API (smartCARS Native). Also, I didn't have vmsACARS at the time, which of course uses the API endpoint, to know the exact format for the fares.

The only consequence for this is that flights, as far as phpVMS's finances are being told, are flying with 0 loading. For some VAs, like mine, where we  don't take the "airline's finances" seriously, this isn't a big deal. Also, pilot pay is **NOT** affected by this.

So, to solve this issue, there's two methods.

- Fake it in the API side using default loading where pilots can't adjust the finances in client before starting the flight
- Add something within smartCARS 3, just like how vmsACARS implements it (side note: I did see a request in the past in Discord for a VA wanting to have this implemented in-client like vmsACARS)

**Comment by BossOfGames** [comment]
If you decide to want to solve it on the API side of the house, I would move the issue over to the phpVMS 7 API repo so that it can be worked and linked to a PR when it's fixed.

If you're wanting to budget time for this. I'm expecting this, with testing, could probably be solved in 5-6 hours. 8 hours tops from start to PR.

**Comment by GenericNerd** [comment]
This should be resolved by the [pirep-fares branch](https://github.com/invernyx/smartcars-3-phpvms7-api/tree/bug/pirep-fares) on the phpVMS 7 API.
