### ISSUE TITLE
[BUG] - PIREPS not displaying after selecting in logbook

### ISSUE THREAD

**Issue by charmor38** [invernyx/smartcars-3-bugs#377]
### Describe the bug

From the Logbook screen, select a PIREP and the screen displays a blank page, using "back" mouse button returns to Logbook screen with all PIREPs displayed.

### How do you reproduce this bug?

1. Navigate to Logbook page
2. Select any PIREP

### Expected behavior

Details of PIREP/flight should be displayed when selected in Logbook, not blank page

### Screenshots

![Picture1](https://github.com/invernyx/smartcars-3-bugs/assets/41695074/d6ccb5e9-b194-4b44-b129-5ffbc8079707)
![Picture2](https://github.com/invernyx/smartcars-3-bugs/assets/41695074/77ca3fad-031a-423a-bad8-7bbd77c9227f)

### Operating system

Windows 10 22H2

### Community airline

American Virtual

### smartCARS Version

3.1.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map

### Additional context

Behavior is unique to American Virtual; UPSVAC Logbook displys PIREPs correctly when selected.

**Comment by GenericNerd** [comment]
Can you please provide a log for this? You can find the logs at %localappdata%\TFDi Design\smartCARS 3\resources\app\logs.

**Comment by charmor38** [comment]
[combined-2024-02-12.log](https://github.com/invernyx/smartcars-3-bugs/files/14253664/combined-2024-02-12.log)
[error-2024-02-12.log](https://github.com/invernyx/smartcars-3-bugs/files/14253678/error-2024-02-12.log)

**Comment by bgiorgio0506** [comment]
> [combined-2024-02-12.log](https://github.com/invernyx/smartcars-3-bugs/files/14253664/combined-2024-02-12.log) [error-2024-02-12.log](https://github.com/invernyx/smartcars-3-bugs/files/14253678/error-2024-02-12.log)

The log does not seems to indicate any issue with the logbook could you try to reproduce and then send the log

**Comment by BossOfGames** [comment]
If the logbook plugin is turning blank, this could be a problem with a corrupted pirep being sent to smartCARS and the React component not handling it properly.

On your computer, with smartCARS running, navigate to https://localhost:7172/app in Google Chrome (or another Chrome based browser) and open up the developer tools by right clicking and inspect element. Once there, you should see at the bottom of the new window a Javascript console.

With the javascript console now open, in the main window, use smartCARS via Chrome and open up the logbook plugin. Once the plugin crashes you may find errors in red in your Javascript console.

Paste those here.

**Comment by Thien42** [comment]
Closing this one for inactivity. If the issue persists, please re-open after going through the steps mentioned above
