### ISSUE TITLE
[BUG] - SmartACARS 3 cannot run as administrator issue

### ISSUE THREAD

**Issue by piacaptain** [invernyx/smartcars-3-bugs#378]
### Describe the bug

I am trying to run smartCARS 3 and it is throwing error that smartCARS 3 cannot run as administrator, whereas i have checked all settings and properties application is not been running as admin.
![WhatsApp Image 2024-03-18 at 12 18 57 AM](https://github.com/invernyx/smartcars-3-bugs/assets/52542693/69c58233-90ff-405b-b4f3-421edb38c16b)

### How do you reproduce this bug?

simply running the exe file and SC3 throwing the continues error

### Operating system

WIndows 10

### Community airline

Pakistan International Airline Virtual

### smartCARS Version

0.8.0.2

### Plugins installed

chat, map, flight center, logbook

**Comment by GenericNerd** [comment]
Your smartCARS version is not the latest. Version 3.1.1 is the latest. Please update and if it still doesn't work, open a new issue
