### ISSUE TITLE
[BUG] - White screen when opening

### ISSUE THREAD

**Issue by nintendojezz** [invernyx/smartcars-3-bugs#379]
### Describe the bug

When l open the application, it loads white and does nothing else

### How do you reproduce this bug?

open the app
Application launches white

### Expected behavior

Should show the login screen and be functional

### Operating system

Windows 10 Pro 22H2

### Community airline

Qvirtual

### smartCARS Version

3.1.1.

### Plugins installed

N/A

### Additional context

tried updating graphics card
deleting and reinstalling Windows updates
Ran disk scans with no issues
Installed it on another computer (Which smartcars is working on) and copied the files to this computer.
reinstalled it to this computer several time (Via the VA download and the TFDI download section, INluded trying to install an earlier version, But was unable to launch without an update)

None of these troubleshooting steps had fixed the issue

**Comment by Thien42** [comment]
Is this still happening on the latest version?

**Comment by Thien42** [comment]
Closing this for now, feel free to re-open if the issue persists or if you have additional information
