### ISSUE TITLE
[BUG] - Currently selected page color indicator not using the correct accent

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#38]
**Describe the bug**
The color of the indicator of the currently selected plugin not consistent with the accent color of the VA

**To Reproduce**
1. Login to any VA
2. The accent color on the navigation menu does not match the accent colors of the selected VA

**Expected behavior**
The color of the indicator of the currently selected plugin should be the accent color of the VA

**System Information:**
 - OS: Windows 11 22H2
 - Community ID: 1
 - Version: 0.5.7

**Comment by turbofandude** [comment]
Fixed in 0.5.8
