### ISSUE TITLE
[BUG] - Jetstream Radio button on smartCARS 3 Inop

### ISSUE THREAD

**Issue by AvalancheGaming** [invernyx/smartcars-3-bugs#380]
### Describe the bug

The Jetstream Radio button displays the correctly playing song and it is still up on the Jetstream Radio website, however when clicking the Jetstream Radio button in the application, it only pulls up Sky Blue Radio. Kind of disappointing as JSR is the better of the 2 in my opinion.

### How do you reproduce this bug?

1. Open the main application of smartCARS 3
2. Navigate to the bottom of the window to the area that has the link for Jetstream Radio as well as the currently playing song
3. Click the Jetstream Radio icon button to open up the player, however Sky Blue Radio appears.

### Expected behavior

It should bring up the Jetstream Radio player instead of the Sky Blue Radio one.

### Screenshots

![image](https://github.com/invernyx/smartcars-3-bugs/assets/53883383/ff537861-35e6-4e5b-a4bb-e70650c0dcc3)
![image](https://github.com/invernyx/smartcars-3-bugs/assets/53883383/655c9f04-83f8-4632-a9c6-24ad6331aed0)

### Operating system

Windows 11

### Community airline

The Delta Virtual

### smartCARS Version

3.1.1

### Plugins installed

chat, flight center, flight tracking, logbook, map

**Comment by GenericNerd** [comment]
This is intended behaviour due to the way the radio player works with SkyBlue/JetStream. You can click the button on the top right of the radio player to switch station.
