### ISSUE TITLE
[BUG] - smartCARS flight center not following Airline's Aircraft restrictions

### ISSUE THREAD

**Issue by mohammedbkr** [invernyx/smartcars-3-bugs#381]
### Describe the bug

When you restrict the Bids to only show the Aircafts at the departing Airport, the Flight Center plugin does not follow it as it should it shows all the fleet of that airline.

### How do you reproduce this bug?

- Create a bid

- Select a flight 

-Select an aircraft
![Screenshot 2024-05-03 130042](https://github.com/invernyx/smartcars-3-bugs/assets/54552867/74a3945c-6b76-4c3e-91a3-8f9a2b915d6c)

this should not be happenning

### Expected behavior

- Create a bid

- Select a flight 

-Select only the available aircrafts at the departure airport
![Screenshot 2024-05-03 124438](https://github.com/invernyx/smartcars-3-bugs/assets/54552867/3a9a1cc7-547e-4ec3-ab69-6384e57138f4)

This picture was taken from phpVMS 7 Flight Center plugin that uses the old phpvms 7 native api

### Operating system

Windows 11

### Community airline

Zeus Airways

### smartCARS Version

3

### Plugins installed

Flight Center, Flight Tracking, SimBrief, Chat, Logbook, Map

**Comment by BossOfGames** [comment]
@GenericNerd Will be fixed by https://github.com/invernyx/smartcars-3-phpvms7-api/pull/9

**Comment by GenericNerd** [comment]
Resolved by an API update to phpVMS 7's API. Please update and try again
