### ISSUE TITLE
[BUG] -  Taxi Time Trigger Changed

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-bugs#383]
### Describe the bug

Last year the taxi time trigger, where the phase changed from pushback to taxi, was changed to 5kts.  In one of the last updates this has increased to approximately 9kts.  Similar to the original ticket (#289), this can cause the plane to only switch from pushback phase during the takeoff roll.  This is especially impactful if using the announcements plugin, as the safety announcements will not begin until you are taking off.

On a recent flight departing gate 7 at KSNA, the parking/gate area is near the departure end of the runway, so the aircraft only reached 6kts during the very short taxi. The safety announcement began playing during the takeoff roll since did not reach a speed of 9kts during the taxi.

### How do you reproduce this bug?

1. Taxi at a (max) speed under 8kts.
2. Takeoff.

### Expected behavior

The trigger should go back to 5kts as was implemented with the fix for issue #289.

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

3.2.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, SimBrief, Announcements

**Comment by Thien42** [comment]
Taxi speed is currently configured at 8 knots.

If we lower it, people will complain that the taxi phase gets triggered while the plane is pushing back, which has happened in the past and is the reason behind the current value.
