### ISSUE TITLE
[BUG] - smartCARS3 cannot be ran as an administrator

### ISSUE THREAD

**Issue by theplanefreak** [invernyx/smartcars-3-bugs#387]
### Describe the bug

First time installing smartCARS3, downloaded from TFDI website. Upon starting the program, I am thrown the error "smartCARS3 cannot be ran as an administrator and will now close." I have confirmed that the program's compatibility properties DID NOT have the "Run this program as an administrator" checked in the \AppData\Local\TFDi Design\smartCARS directory provided in the screenshot below.

I have also ran the updater in the \AppData\Local\TFDi Design\smartCARS directory and used the .exe file that was downloaded to update to the latest version. I have ran the file to Modify the program to no success and I have ran the file to Repair the program, also yielding no success. The updater .exe in the \AppData\Local\TFDi Design\smartCARS directory shows I have the latest smartCARS3 version. 

Also attached are my logs from \AppData\Local\TFDi Design\smartCARS\resources\app\logs
[combined-audit.json](https://github.com/user-attachments/files/16325725/combined-audit.json)
[error-2024-07-21.log](https://github.com/user-attachments/files/16325726/error-2024-07-21.log)
[error-audit.json](https://github.com/user-attachments/files/16325727/error-audit.json)
[combined-2024-07-21.log](https://github.com/user-attachments/files/16325728/combined-2024-07-21.log)

as well as my updater.ini as a txt file
[updater.txt](https://github.com/user-attachments/files/16325757/updater.txt)

### How do you reproduce this bug?

1. Navigate to \AppData\Local\TFDi Design\smartCARS\
2.  Double-clicked on smartcars3.exe
3. An error appears stating, "smartCARS3 cannot be ran as an administrator, the app will now close."

### Expected behavior

I should be led to a screen to begin my login process. 

### Screenshots

![error](https://github.com/user-attachments/assets/c513816c-7ae6-4aaf-85f9-39460a57d0cb)
![error_2](https://github.com/user-attachments/assets/a605f9ce-54a0-4746-b59d-2a072605ace4)
![up_to_date](https://github.com/user-attachments/assets/243b7850-6880-489e-873d-e5dad19ec08a)

### Operating system

Windows 10 Pro 22H2

### Community airline

TheDeltaVirtual

### smartCARS Version

3.2.2.0

### Plugins installed

(None)

### Additional context

I am able to run smartCARS2 without any issues.

**Comment by Thien42** [comment]
Do you have UAC disabled in Windows? https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/

If so, Windows treats any app as running as administrator, which would explain why you are getting this error message.

**Comment by theplanefreak** [comment]
I did. Turning it On has resolved my issue.

Thank you so much! :)

**Comment by jordanhavard** [comment]
@Thien42 any chance this can be pinned in issues ?
