### ISSUE TITLE
[BUG] - SC Mobile Login Doesn’t Handle additional / after URL properly

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-bugs#388]
### Describe the bug

The login request fails due to the attached issue. It appears that an edge case where community URLs have a / at the end is causing failed logins. 

### How do you reproduce this bug?

Have a SC Community URL ending in a / in smartCARS Central.
Attempt to login via the web app.

### Operating system

iOS

### Community airline

Air Canada Virtual

### smartCARS Version

N/A

### Plugins installed

N/A

### Additional context

See https://discord.com/channels/589851727373795331/1265100221159964777

**Comment by turbofandude** [comment]
An update to address this was deployed today
