### ISSUE TITLE
[BUG] - SC3 fails to pause at T/D even when asked to

### ISSUE THREAD

**Issue by mp1963** [invernyx/smartcars-3-bugs#390]
### Describe the bug

Flight from KOAK to KAUS in the MD-11F. Asked SC3 to pause at T/D. Came back find aicraft out of fuel in a field.

### How do you reproduce this bug?

Start SC3
Select flight
Start flight
Ask SC3 to pause at T/D

### Expected behavior

SC3 should pause at T/D

### Screenshots

![Screenshot 2024-08-08 153350](https://github.com/user-attachments/assets/48ead4e6-5fd4-44d9-9852-61b26bedccf1)
![Screen Shot 08-08-24 at 03 33 PM](https://github.com/user-attachments/assets/acdf5128-076d-4b1f-be0
[combined-2024-08-08.log](https://github.com/user-attachments/files/16549691/combined-2024-08-08.log)
8-93f85e163f47)
[error-2024-08-08.log](https://github.com/user-attachments/files/16549694/error-2024-08-08.log)
[error-audit.json](https://github.com/user-attachments/files/16549696/error-audit.json)

### Operating system

Windows 11

### Community airline

Walker Air Transport

### smartCARS Version

Latest whatever that is

### Plugins installed

chat,map, logbook., the usual ones

**Comment by Thien42** [comment]
Was this a one-time occurrence or did you manage to reproduce this behavior consistently?

**Comment by mp1963** [comment]
Since the new version of SC3 was released this has not happened again I am pleased to say.

**Comment by Thien42** [comment]
Thanks for letting us know!
