### ISSUE TITLE
[BUG] - development center VAs present

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#4]
Looks like the dev environments are present when searching for a VA
![image](https://user-images.githubusercontent.com/67948773/224463742-c6de3f35-bdf8-4c4e-864d-fcf4b174b2c1.png)

**Comment by GenericNerd** [comment]
Considering that the Development Centers are still there, I believe we may be using the development server as you said. I’ll let @turbofandude know and it should be fixed by Monday.
