### ISSUE TITLE
[BUG] - Log shows "Reached 285knots below 10,000 feet" when at an altitude higher than 10,000

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-bugs#40]
**Describe the bug**
flight tracking log improperly reports a high speed below 10,000 feet, when the aircraft is higher than 10,000

**To Reproduce**
1. Start a flight
2. When getting close to 10,000ft the autopilot will start accelerating and may go beyond 250kt.
3. However the recorded speed is the one taken at the end of the 5s timeout (in this case 285kt), but at that point the aircraft is already above 10,000ft

**Expected behavior**
The speed should only be recorded while the aircraft is below 10,000ft

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: 1
 - Version 0.5.7
 - Plugins used: flight-tracking

**Additional context**
Was using the FSLabs A321 for that flight

**Comment by turbofandude** [comment]
This should be resolved in 0.5.8
