### ISSUE TITLE
[BUG] - Flash of default colour on change

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#43]
**Describe the bug**

**To Reproduce**
1. Login to VA
2. Click on Flight Center
4. See temporary flash of default colour on buttons

**Expected behavior**
The buttons should not change colour temporarily

**Screenshots**
https://i.imgur.com/OjnAVvF.gif

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: Any that don't use default colour
 - Version 0.5.8
 - Plugins used: flight-center

**Comment by Thien42** [comment]
@GenericNerd I can't seem to be able to reproduce the issue on my side :(

**Comment by GenericNerd** [comment]
Fixed in 0.5.11
