### ISSUE TITLE
[BUG] - 404 on /plugins/chat/globe.png and /plugins/chat/person.png

### ISSUE THREAD

**Issue by GenericNerd** [invernyx/smartcars-3-bugs#44]
**Describe the bug**
Console error - no large effect

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to VA
2. Click on chat
3. Click on a user
4. Open console through Control+Shift+I
5. See both errors

**Expected behaviour**
There should be no error

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: Any
 - Version 0.5.8
 - Plugins used: chat

**Comment by Thien42** [comment]
Will be fixed in 0.5.10
