### ISSUE TITLE
[FEATURE] - My Flights - Fly

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#46]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
When you on 'My Flights' and you click the 'Fly' button, move the window to 'Flight Tracking'.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by walkerair** [comment]
> smartCARS 3 already does this. Are you on the most up-to-date version?

I think so? I ran the sc3_updater and it says I am.
Just loaded into an airport, hit "Fly" and got the green pop up, and as of right now it's still on "My Flights". It's not moving to "Flight Tracker".

![image](https://user-images.githubusercontent.com/127605985/227005664-b8f2626d-0cc9-45c3-ba51-158a7a3ed169.png)

**Comment by GenericNerd** [comment]
@walkerair Bump on this :)

**Comment by GenericNerd** [comment]
Excellent! Glad to hear it!
