### ISSUE TITLE
[FEATURE] - Cancelling a flight should bring you back to the flight centre

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#47]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
When clicking on 'Cancel Flight', give a prompt confirming this, and then move the window to 'My Flights'

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Thien42** [comment]
Will be fixed on 0.5.10
