### ISSUE TITLE
[FEATURE] - Discord Rich Presence

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#48]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Would like to see Discord Rich Presence integrated so that pilots in VA discords can show that they're actively flying.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

<sub>[SC-1](https://linear.app/invernyx-inc/issue/SC-1/[feature]-discord-rich-presence)</sub>

**Comment by GenericNerd** [comment]
We intend to have this feature available soon!

**Comment by walkerair** [comment]
Do we know when this will be included? I see it tagged for 0.6 but assuming it didn't make it right?

**Comment by GenericNerd** [comment]
The version tag simply shows when it was last looked at by the team, not when it will be implemented. We don't have a timeline for this at the moment since we're prioritising bugs.

**Comment by GenericNerd** [comment]
Just wanted to provide an update and let you know that we do still intend for this feature to happen at some point!

**Comment by walkerairtrans** [comment]
> Just wanted to provide an update and let you know that we do still intend for this feature to happen at some point!

Thanks! I hope that the VA icon will be usable in it but I'm going to assume that for DRP it uses a single icon.

Fingers crossed--be an awesome addition!

**Comment by Thien42** [comment]
Will be added in the next release
