### ISSUE TITLE
[BUG] - Incorrect Distance from smartCARS 3 being reported.

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#50]
**Describe the bug**
I'm doing a test flight from KAUS-KSAT, sitting on the ground and my reported distance is 106,373. I intercepted the POST and read the value coming directly from the inbound API and that is what is being sent.

**To Reproduce**
1. Start flight
2. Review ACARS table and see 'distremain' showing incorrect distance

**Expected behavior**
It should show the standard range of 57nm in this case, as shown in the ACARS application.

**Screenshots**
Here is a view of my table.

![image](https://user-images.githubusercontent.com/127605985/227059568-b0542137-5d49-4a21-b0a6-17115086718a.png)

Here is the app showing 57nm.

![image](https://user-images.githubusercontent.com/127605985/227059615-ab6ba067-ccaf-49ef-b8f5-44fc20e5539f.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: 
 - Version 0.5.9
 - Plugins used: flight-center, flight-tracking, pilot-center

**Additional context**
N/A

**Comment by bgiorgio0506** [comment]
@walkerair the flight-tracking is sending meters instead of nm. I will fix this issue

**Comment by GenericNerd** [comment]
Closed by mistake, re-opened
