### ISSUE TITLE
[FEATURE] - Increase size of configuration fields in smartCARS Central

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#51]
**Describe the suggestion**
Make the logger configuration area larger to be easier to make changes

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/227481051-9efe4b1a-1d5d-4a3c-bbd4-630fb7758816.png)

**Comment by jordanhavard** [comment]
Side note, is there any documentation on what variables can be placed here ?

**Comment by GenericNerd** [comment]
This is more of a suggestion rather than a bug. This has been corrected
