### ISSUE TITLE
[FEATURE] - Offer VAs ability to upload light and dark variants of logo

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#52]
**Is your feature request related to a problem? Please describe.**
Now that dark mode has been enabled, VAs that have a dark logo get lost with the background. 

**Describe the solution you'd like**
Have the ability to upload light and dark mode variants. If only 1 variant is used, make the both variants by default

**Describe alternatives you've considered**

**Additional context**
screenshot
![image](https://user-images.githubusercontent.com/67948773/227482282-1fc27427-752c-46c7-905b-92faabba3a46.png)
![image](https://user-images.githubusercontent.com/67948773/227490105-8ff68376-e252-43b5-8079-02e69592929c.png)

**Comment by turbofandude** [comment]
Added to APIs and Central; this will be available and supported by the next update.
