### ISSUE TITLE
[BUG] - Chat colours off in dark mode

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#54]
**Describe the bug**
Now that dark mode has been enabled, the chat colour bubble backgrounds make it hard to read the text

**To Reproduce**
1. Click chat (ensure dark mode is enabled)

**Expected behavior**
Text should be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/227483643-30639f8d-30c4-413f-9b50-158347850831.png)

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: Any
 - Version 0.5.10.1
 - Plugins used: chat

**Additional context**

**Comment by Thien42** [comment]
Will be fixed in the next release
