### ISSUE TITLE
[BUG] - Profile card dark mode

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#55]
**Describe the bug**
Looks like this was missed for dark mode. 

**To Reproduce**
1. Login to chat (dark mode)
2. click pilot

**Expected behavior**
dark variant

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/227484438-982c8177-4ba8-47d7-b8d1-7cf8768d5ca0.png)

**System Information (please complete the following information):**
 - OS: Windows 11 22H2
 - Community ID: Any
 - Version 0.5.10.1
 - Plugins used: chat

**Additional context**

**Comment by Thien42** [comment]
Will be fixed in the next release
