### ISSUE TITLE
[BUG] - Page flashes white when changing state in dark mode

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#57]
**Describe the bug**
Related to #43 

In addition to the default blue flashing before changing to the VA colour (observed in bookings, specifically the `view pireps` `refresh icon` and `create flight` button), when navigating pages in dark mode, the screen flashes white on initial page load

**To Reproduce**
Video attached

**Expected behavior**
No white flashing and default blue is not shown when VA colours selected

**Video**
https://www.loom.com/share/2a492d0060104021a34150f3a72cee2f

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: QVirtual
 - Version 0.5.10.1
 - Plugins used: chat, flight-center, flight-tracking, pilot-center

**Additional context**
In loom, you can slow the video down to `0.8x` if needed however its still visible at `1.0x`

**Comment by GenericNerd** [comment]
Fixed in 0.5.11
