### ISSUE TITLE
[FEATURE] - Shortcut to Desktop use VA icon

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#59]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
When creating the VA shortcut to the desktop. Have the application use the "logo" we define in community to be the shortcut icon.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GenericNerd** [comment]
This should already be the case. Is this not happening for you?

**Comment by GenericNerd** [comment]
Can you re-upload your logo through smartCARS Central and try to create the desktop shortcut again? The icon may not be generated for your logo yet, causing this issue

**Comment by walkerair** [comment]
> This shouldn't be happening. Would you mind if I created a pilot account on your VA and test this on my end to see whether this happens?

Not at all -- I'll keep an eye out for the registration and approve you. :)

**Comment by GenericNerd** [comment]
Signed up!

**Comment by walkerair** [comment]
> Signed up!

All set!

**Comment by jordanhavard** [comment]
This is also happening for QV as well - default logo is showing when desktop shortcut is being created

**Comment by walkerair** [comment]
Looks like it's working now! :)

![image](https://user-images.githubusercontent.com/127605985/229256601-a539a0d0-6666-4bfb-9d1d-60205a204aaf.png)

**Comment by jordanhavard** [comment]
This is still happening for QVirtual. Full reinstall of SC3 yet still the base icon is being added to the desktop.
![image](https://user-images.githubusercontent.com/67948773/230692252-0747b219-f6fd-4f04-bf48-6c4e6b397c66.png)

**Comment by jordanhavard** [comment]
Still having issues with this. I've uploaded a new logo (in #87) however its still displaying the default logo
