### ISSUE TITLE
[BUG] - Dark Mode Flight Tracking Airplane Icon

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#60]
**Describe the bug**
The airplane icon in Flight Tracking has a white background.

**To Reproduce**
Start a flight.

**Expected behavior**
It should be transparent.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/227615889-99342c45-0367-426c-ac1c-93e02d3377a3.png)

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - Community ID: [e.g. 2/any]
 - Version [e.g. 0.1.0]
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**
N/A

**Comment by Thien42** [comment]
Will be fixed in the next release
