### ISSUE TITLE
[FEATURE] - Sound an alarm or tone if plane movement is detected

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#61]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would like the ability (unless we can do this through custom plug-in) to sound an alarm, tone, something that will occur if smartCARS is not tracking a flight and it detects ground speed increase. This would help so many VA pilots who forget to start their tracking.

**Describe alternatives you've considered**
An inflatable hammer or a trunk monkey (if you know that commercial LOL)

**Additional context**
N/A

**Comment by GenericNerd** [comment]
You can do this in a future update through a custom plugin. We don't plan to have an "alarm" or generic alarm sound in a TFDi Design.
