### ISSUE TITLE
[BUG] - Comments are `undefined` when completing flight

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#62]
**Describe the bug**
When finish flight is clicked with comments added, the comments are coming through as `undefined` to the api

**To Reproduce**
1. Start tracking flight
2. add comments
3. finish flight
4. submit pirep
5. view logs (server side for incoming request) and observe comments are undefined

**Expected behavior**
comments are sent in an array format similar to `flightlog`

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/227718344-3280eb44-975f-4e6f-b5ce-c5a890f299bb.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: qvirtual
 - Version 0.5.10.1
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**

**Comment by GenericNerd** [comment]
Fixed in 0.6
