### ISSUE TITLE
[FEATURE] - Load Option

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#67]
**Is your feature request related to a problem? Please describe.**
It does not exist at the moment.

**Describe the solution you'd like**
Add a box that will allow us to enter a load that cannot exceed the preset load value in the database (identical to smartCARS 2). If the flight type is P, it would be passenger and if it's C, it would be cargo.

**Describe alternatives you've considered**
N/A

**Additional context**
I suppose one option I could do is either A) put it into a bid and carry to the app through plugin and/or write plugin that ties into simbrief XML.

If that is what we intend to do let me know so I can plan accordingly.

**Comment by GenericNerd** [comment]
The issue with this suggestion is that not all aircraft report a load, so we have no way of *always* knowing what the upper bound is. We also can't always use the simBrief input since it may not always have a simBrief flight plan associated

Do you have any other suggestions? Otherwise, it may be necessary to mark this issue as "wont fix"

**Comment by walkerair** [comment]
Why can't you do what we did in smartCARS 2?
You pull the aircraft info and get the MAXPAX and MAXCARGO values.
You set the load box to either passenger or cargo based on whether the flight is a C or a P.
And then you don't let them go past that value.

**Comment by walkerair** [comment]
I guess, if you are not going to provide that box or capability -- then I just need to manage load myself on the back-end.

**Comment by GenericNerd** [comment]
> You pull the aircraft info and get the MAXPAX and MAXCARGO values.
Because not all platforms provide this value for definite (namely phpVMS 7).

**Comment by GenericNerd** [comment]
This won't be fixed per the reasoning outlined.
