### ISSUE TITLE
[FEATURE] - Reduce Cruise Status Timer

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#68]
**Describe the bug**
I feel like the cruise phase detection is a bit long -- it took almost 5 minutes for my status to change.

**To Reproduce**
1. Take off, and climb.
2. Reach cruise, takes about 5 minutes.
3. Climb again (think step climb) and get to cruise, takes about 5 minutes.

**Expected behavior**
Maybe reduce by 1/2? I'm not sure. I supposed you're trying to account for departure altitudes where you might be capped for a bit?

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: Flight-Tracking

**Additional context**
N/A

**Comment by GenericNerd** [comment]
Has this been the case for each flight you've flown so far?

**Comment by walkerair** [comment]
> Has this been the case for each flight you've flown so far?

Yes, it's been on couple flights I tested -- and it also happens repeated. I can climb, level (wait 5-ish minutes), climb or descend, level -- it takes about 5ish minutes.

**Comment by turbofandude** [comment]
I have reduced the detection time to 3 minutes and 6 minutes (6 if it isn't sure, 3 if it's pretty sure).
