### ISSUE TITLE
[FEATURE] - Add Landing Rate to Log

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#69]
**Describe the bug**
Log file doesn't include landing rate.
Is it possible to also get info on how we determine? I know in SC2 it was based on vertical speed at time on_ground = ON.

**LOG FILE**
3/31/2023 9:07:48 PM	Flying Black Square A36 Bonanza Turbo WAT Black Red
3/31/2023 9:07:48 PM	Flight phase set to boarding
3/31/2023 9:08:04 PM	Paused
3/31/2023 9:08:15 PM	Unpaused
3/31/2023 9:08:17 PM	Paused
3/31/2023 9:08:29 PM	Unpaused
3/31/2023 9:08:47 PM	Paused
3/31/2023 9:10:09 PM	Unpaused
3/31/2023 9:11:12 PM	Paused
3/31/2023 9:12:19 PM	Unpaused
3/31/2023 9:15:19 PM	Engine 1 On
3/31/2023 9:17:59 PM	Flight phase set to push back
3/31/2023 9:18:09 PM	Flight phase set to taxi
3/31/2023 9:20:51 PM	Flight phase set to take off
3/31/2023 9:20:56 PM	Flight phase set to climb
3/31/2023 9:21:01 PM	Gear level raised
3/31/2023 9:29:51 PM	Flight phase set to cruise
3/31/2023 10:10:10 PM	Flight phase set to climb
3/31/2023 10:17:03 PM	Flight phase set to cruise
3/31/2023 10:20:04 PM	Flight phase set to descent
3/31/2023 10:21:22 PM	Flaps set to 50%
3/31/2023 10:22:00 PM	Gear level lowered
3/31/2023 10:22:24 PM	Flaps set to 100%
3/31/2023 10:23:21 PM	Flight phase set to landed
3/31/2023 10:24:14 PM	Flight phase set to taxi to_gate
3/31/2023 10:24:50 PM	Flaps set to 0%
3/31/2023 10:26:57 PM	Engine 1 Off
3/31/2023 10:26:57 PM	Flight phase set to deboarding

**To Reproduce**
Just do a flight.

**Expected behavior**
Should have a landing rate indicated in the log file.

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: Flight-tracking

**Additional context**
N/A

**Comment by GenericNerd** [comment]
We have access to the data, but we have not given a log for this yet.

**Comment by turbofandude** [comment]
This will be implemented along with a slew of other things in flight-tracking 0.6.1.

**Comment by walkerairtrans** [comment]
![image](https://user-images.githubusercontent.com/127605985/230518954-46f08f5c-7619-4e13-bfd2-c85aa2dc7b4d.png)
