### ISSUE TITLE
[BUG] - Approach & Final Not Detected

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#70]
**Describe the bug**
Approach and Final was not detected in my flight.

**Log File**
3/31/2023 9:07:48 PM	Flying Black Square A36 Bonanza Turbo WAT Black Red
3/31/2023 9:07:48 PM	Flight phase set to boarding
3/31/2023 9:08:04 PM	Paused
3/31/2023 9:08:15 PM	Unpaused
3/31/2023 9:08:17 PM	Paused
3/31/2023 9:08:29 PM	Unpaused
3/31/2023 9:08:47 PM	Paused
3/31/2023 9:10:09 PM	Unpaused
3/31/2023 9:11:12 PM	Paused
3/31/2023 9:12:19 PM	Unpaused
3/31/2023 9:15:19 PM	Engine 1 On
3/31/2023 9:17:59 PM	Flight phase set to push back
3/31/2023 9:18:09 PM	Flight phase set to taxi
3/31/2023 9:20:51 PM	Flight phase set to take off
3/31/2023 9:20:56 PM	Flight phase set to climb
3/31/2023 9:21:01 PM	Gear level raised
3/31/2023 9:29:51 PM	Flight phase set to cruise
3/31/2023 10:10:10 PM	Flight phase set to climb
3/31/2023 10:17:03 PM	Flight phase set to cruise
3/31/2023 10:20:04 PM	Flight phase set to descent
3/31/2023 10:21:22 PM	Flaps set to 50%
3/31/2023 10:22:00 PM	Gear level lowered
3/31/2023 10:22:24 PM	Flaps set to 100%
3/31/2023 10:23:21 PM	Flight phase set to landed
3/31/2023 10:24:14 PM	Flight phase set to taxi to_gate
3/31/2023 10:24:50 PM	Flaps set to 0%
3/31/2023 10:26:57 PM	Engine 1 Off
3/31/2023 10:26:57 PM	Flight phase set to deboarding

**To Reproduce**
Do a flight.

**Expected behavior**
Would get an approach and final phase during flight.

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: Flight-Tracking

**Additional context**
N/A

**Comment by GenericNerd** [comment]
This is likely an issue with the default configuration of the flight tracking code. I will @turbofandude and @bgiorgio0506 to look into this

**Comment by turbofandude** [comment]
Fixed in 0.6
