### ISSUE TITLE
[FEATURE] - Route

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#72]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Provide a spot where we can enter a custom route like in smartCARS 2.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GenericNerd** [comment]
Do you mean to edit the route before a flight is started, or during a flight?

**Comment by walkerair** [comment]
> Do you mean to edit the route before a flight is started, or during a flight?

I was referencing the box in smartCARS so that pilots could put the route they receive from simBrief (or anywhere) into it.

![image](https://user-images.githubusercontent.com/127605985/229601698-7d7de265-7de0-4f7e-8303-c78e4c8d9e22.png)

**Comment by GenericNerd** [comment]
You can edit the route during your flight by pressing "View/Edit Route" in the Flight Tracking plugin. From this screen, I assume you mean to add an ability to edit routing before you start flying a flight?

**Comment by GenericNerd** [comment]
If that is the case, you can click the flight itself (rather than the fly button right away) which will expand the flight tab and allow you to edit the route like before.

**Comment by walkerairtrans** [comment]
> If that is the case, you can click the flight itself (rather than the fly button right away) which will expand the flight tab and allow you to edit the route like before.

Sorry! I forgot to reply back that I found the route box.
