### ISSUE TITLE
[BUG] - Flight Tracking aircraft icon at starting point upon switching back from another item.

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#76]
**Describe the bug**
If you switch to another screen in the app, say chat for example, and go back to flight tracking. The icon sits at the starting point for a few seconds.

**To Reproduce**
1. Start tracking and fly so you icon is somewhere that isn't the start.
2. Go to chat, or flight center, or settings.
3. Go back to flight tracking.

**Expected behavior**
I would think the app could keep track of the location and the icon would be in the right spot instantly upon loading the flight tracking page.

**Screenshots**
![smartcars3_oHPvipPftr](https://user-images.githubusercontent.com/127605985/229841617-01d2500d-c301-44af-a909-6bbb162c6bd4.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: flight-center, flight-tracking

**Additional context**
N/A

**Comment by turbofandude** [comment]
Resolved in next release - thank you!
