### ISSUE TITLE
[BUG] - Time Remaining logic appears off?

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#78]
**Describe the bug**
I feel this is a bit inaccurate compared to smartCARS 2. I'm 62 miles from the airport and the clock is show 0:0 -- looking at the raw data coming from the app it's showing 0 (whereas smartCARS 2 will show a minute 4NM out from the airport.)

**To Reproduce**
Just run a flight and monitor the time.

**Expected behavior**
Just accuracy -- I don't know your logic so maybe this is right (now versus older version.)

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/229896742-387feb46-cfe8-4a46-919d-d760ffd8f6f0.png)

![image](https://user-images.githubusercontent.com/127605985/229896882-24eec73c-ecd2-4a14-95eb-2934513ca698.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**
N/A

**Comment by walkerair** [comment]
Additional information:
I was getting data of 0.1899 from the app to my database. It was translating to 11 minutes until arrival, but I was at the field.

![Navigraph_Charts_moqyFLqzpJ](https://user-images.githubusercontent.com/127605985/230129228-0bf3a7d4-a1fc-4165-8b12-e9a90eb72642.png)

**Comment by Thien42** [comment]
Current logic is using the duration of the flight based on the bid and assumes it is airtime. You may notice the remaining time only starts to go down once you get airborne.

If you are using the Simbrief plugin, we will use the airtime calculated by simbrief instead (as we assume it is most likely more accurate).

This means there can be some inaccuracies if for whatever reason it takes you more time to reach the destination.

**Comment by walkerair** [comment]
> Current logic is using the duration of the flight based on the bid and assumes it is airtime. You may notice the remaining time only starts to go down once you get airborne.
> 
> If you are using the Simbrief plugin, we will use the airtime calculated by simbrief instead (as we assume it is most likely more accurate).
> 
> This means there can be some inaccuracies if for whatever reason it takes you more/less time to reach the destination.
> 
> So I would say this is working as intended, although we can certainly bring some improvements to the logic in the future.

Current logic duration is based on which fields in the schedule (bid)? deptime and arrtime?

Is there an opportunity to rethink the logic so that it's a little more simple -- perhaps just distance of the flight schedule / aircraft speed? I believe that is how smartCARS 2 is setup? Or am I mistaken? I don't think I've seen this kind of inaccuracy before.

Our times in the database not 100% accurate -- we let pilots choose the aircraft for every flight so storing an accurate dep/arr time in a schedule is not in our process. However, if this is how the logic will behave and that we need to provide a deptime/arrtime that is accurate for the type of plane being used--I'll need to re-engineer my code (not terrible, as I've had to do it for other things you all have introduced in SC3.)

**Comment by jordanhavard** [comment]
I'd also agree that the current logic does seem counter intuitive and that a distance remaining / speed calculation would get my backing.

> If you are using the Simbrief plugin, we will use the airtime calculated by simbrief instead (as we assume it is most likely more accurate).

For the most part this may be correct however some airframes don't exist within simbrief so if a pilot was to fly an airframe that doesn't exist, I'd imagine this would throw the current logic out (maybe more of a reason to use a distance / speed)

**Comment by Thien42** [comment]
> Current logic duration is based on which fields in the schedule (bid)? deptime and arrtime?

Yes

> Is there an opportunity to rethink the logic so that it's a little more simple -- perhaps just distance of the flight schedule / aircraft speed? I believe that is how smartCARS 2 is setup? Or am I mistaken? I don't think I've seen this kind of inaccuracy before.

I can't speak for smartCARS2, but the previous logic before `0.6.0` was using the current ground speed divided by the remaining distance. I believe the problem with that is the remaining time won't go down in a consistent manner during some flight phases when the speed is changing, and will go up during descent as you slow down. Moreover you're not always flying in a straight line from your current position towards your destination - and might even fly away from it during approach.

Both calculations are going to be inaccurate, just in a different way.

If the community sentiment is that we should change that logic, we are definitely open to it. We could offer it as a setting where users can decide which method of calculation they prefer.

**Comment by walkerair** [comment]
> > Current logic duration is based on which fields in the schedule (bid)? deptime and arrtime?
> 
> Yes
> 
> > Is there an opportunity to rethink the logic so that it's a little more simple -- perhaps just distance of the flight schedule / aircraft speed? I believe that is how smartCARS 2 is setup? Or am I mistaken? I don't think I've seen this kind of inaccuracy before.
> 
> I can't speak for smartCARS2, but the previous logic before `0.6.0` was using the current ground speed divided by the remaining distance. I believe the problem with that is the remaining time won't go down in a consistent manner during some flight phases when the speed is changing, and will go up during descent as you slow down. Moreover you're not always flying in a straight line from your current position towards your destination - and might even fly away from it during approach.
> 
> Both calculations are going to be inaccurate, just in a different way.
> 
> If the community sentiment is that we should change that logic, we are definitely open to it. We could offer it as a setting where users can decide which method of calculation they prefer.

Totally agree and I see both inconsistencies equally with you. My thought for the community is that it would be better to see time increase and decrease based on speed/direction then to land at an airfield and see 11m to arrival on the app. 

Perhaps using the current logic we could implement a function in the app where it states late or early? Instead of saying 11m, which people will equate to wieird/bug?

**Comment by Thien42** [comment]
> Totally agree and I see both inconsistencies equally with you. My thought for the community is that it would be better to see time increase and decrease based on speed/direction then to land at an airfield and see 11m to arrival on the app.

We'll keep that in mind and we'll definitely make some refinements in the future.
 
> Perhaps using the current logic we could implement a function in the app where it states late or early? Instead of saying 11m, which people will equate to wieird/bug?

I thought of doing that as well, and it is possible but it will probably only be available if the user is also using the simbrief plugin.

**Comment by walkerair** [comment]
> > Totally agree and I see both inconsistencies equally with you. My thought for the community is that it would be better to see time increase and decrease based on speed/direction then to land at an airfield and see 11m to arrival on the app.
> 
> We'll keep that in mind and we'll definitely make some refinements in the future.
> 
> > Perhaps using the current logic we could implement a function in the app where it states late or early? Instead of saying 11m, which people will equate to wieird/bug?
> 
> I thought of doing that as well, and it is possible but it will probably only be available if the user is also using the simbrief plugin.

There’s got to be a way to do it without that plug-in though. Or like you said before; either go back to previous logic or make it config items in the manager. 🙂

**Comment by turbofandude** [comment]
We have disabled the enhanced time logic in lieu of the traditional time=distance/speed logic it has always used. We plan to return to this at some point and expand the time simulation.
