### ISSUE TITLE
[BUG] - Comment field empty is sending /n's with PIREP.

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#79]
**Describe the bug**
Comment is being sent when a PIREP is filed resulting in "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

**To Reproduce**
Submit a PIREP.

**Expected behavior**
No comment, no submission.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/229908552-b5a39799-59e5-49c5-b449-104a59abaf6f.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: N/A

**Additional context**
N/A

**Comment by walkerair** [comment]
Additional information if needed--here is the POST from the completion.

`{"pilotid":100,"code":"WAE","flightnum":"3603","depicao":"KELP","arricao":"KMAF","route":"","aircraft":"106","load":"4","flighttime":"01:18","landingrate":"-76.8946875","submitdate":"2023-04-05 15:16:20","fuelused":"117","source":"smartCARS 3","log":"2023-04-05T13:56:04.876Z - Flying Black Square A36 Bonanza Turbo WAT Black Red*2023-04-05T13:57:59.279Z - Engine 1 On*2023-04-05T14:01:34.883Z - Flight phase set to push back*2023-04-05T14:01:44.974Z - Flight phase set to taxi*2023-04-05T14:04:43.883Z - Flight phase set to take off*2023-04-05T14:04:54.999Z - Flight phase set to climb*2023-04-05T14:05:04.093Z - Gear lever raised*2023-04-05T14:15:59.229Z - Flight phase set to cruise*2023-04-05T14:31:16.813Z - Paused*2023-04-05T14:31:24.962Z - Unpaused*2023-04-05T14:59:37.377Z - Flight phase set to descent*2023-04-05T15:04:27.657Z - Flight phase set to final*2023-04-05T15:09:25.978Z - Gear lever lowered*2023-04-05T15:09:34.061Z - Flaps set to 50%*2023-04-05T15:11:39.344Z - Flight phase set to landed*2023-04-05T15:12:10.648Z - Flaps set to 0%*2023-04-05T15:12:15.715Z - Flight phase set to taxi to_gate*2023-04-05T15:16:02.135Z - Engine 1 Off*2023-04-05T15:16:02.135Z - Flight phase set to deboarding","comment":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"}`

**Comment by CaptainMac2336** [comment]
My comment field also posted "nnnnnnnnn" which overwrote my comment for the PIREP

**Comment by turbofandude** [comment]
@bgiorgio0506 I know you were looking into this; what was the verdict?

**Comment by bgiorgio0506** [comment]
at end was an edge case should be fixed
