### ISSUE TITLE
[BUG] - Cannot login with Airline ID

### ISSUE THREAD

**Issue by JoshRiley** [invernyx/smartcars-3-bugs#8]
**Describe the bug**
Cannot login with pilot ID to a virtual airline, either using the single digit, numbers only or with the airline ID (tried 4, 0004, and SCD0004). 

**To Reproduce**
1. Open the application
2. Log in to TFDi Design account
3. Select virtual airline
4. Attempt to log in with the pilot ID

**Expected behavior**
Login should be allowed with pilot IDs, not just with an email address.

**Screenshots**
![image](https://user-images.githubusercontent.com/7196643/224486963-70e1553c-a854-4388-a70d-7b26e7f5cf3c.png)

**System Information (please complete the following information):**
- OS: [e.g. Windows 11 22H2] Windows 11 Pro Build 22621
- Community ID: 2
- Version [e.g. 0.1.0]
- Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center] None

**Comment by GenericNerd** [comment]
*Edit*
Corrected community ID

**Comment by GenericNerd** [comment]
Moved to invernyx/smartcars-3-public-api#2
