### ISSUE TITLE
[BUG] - Flight Center, unchecking allow charter flights and clicking save results in error.

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-bugs#80]
**Describe the bug**
Get an error that the checkbox has to be checked when saving (this is when I want to disable create flight.)

**To Reproduce**
1.  Click checkbox for Allow Flight Chartering in Flight-Center plugin and save.
2. Click checkbox to disable flight chartering in Flight-Center plugin and save.

**Expected behavior**
Should allow us to disable it.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/229951612-550fa713-d12a-4298-9dca-ce796376a607.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**
N/A

**Comment by turbofandude** [comment]
This will be fixed today with a Central update
