### ISSUE TITLE
[BUG] - Unable to load SC3

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#81]
**Describe the bug**
Looks like after the recent outage, SC3 is not able to load VA lists. I also am unable to login to SC3 central (may be related)

**To Reproduce**
Open Smartcars 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/230010873-4a2b5c5a-24ba-408e-b766-d312a04bc589.png)

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - Community ID: [e.g. 2/any]
 - Version [e.g. 0.1.0]
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**

**Comment by GenericNerd** [comment]
This was likely caused by an incorrectly set PHP version. Can you try again now and see if this issue still persists?

**Comment by jordanhavard** [comment]
looks like its resolved - can confirm I can login to SC3. Central still having issues
