### ISSUE TITLE
[FEATURE] - Start/Resume POST Variable

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#82]
**Is your feature request related to a problem? Please describe.**
I have this issue in my own VA with flight tracking -- it's really around situations where a pilot will start flying, have a CTD, and then restart their flight. There's no flag in smartCARS 2 that tells me this is a "start from scratch" connection -- versus one that is a recovery (with say SC Premium, or a plane's autosave.) Not knowing that this update is the start of a new flight, or resume, makes it hard to remove track path rows out of an existing flight. So, I end up at times with duplicated flight lines in a PIREP.

_I recognize that my situation is very specific to my airline and how I've coded my systems and solutions._

**Describe the solution you'd like**
I would like smartCARS 3 to send a POST variable that tells us this is a start from new flight, and (if you implement auto-save resume options) send a POST variable that says it's a resume.

With those two POST variables; dev's can work out how they want to treat stale flight data.

**Describe alternatives you've considered**
Right now to combat this, I have to sweep the rows and do time checks to find major gaps between the start phase (preflight) and (current phase) to try and remove the older stale flight.

**Additional context**
N/A

**Comment by turbofandude** [comment]
We will take the UUID approach - each tracking "session" will generate a new one and send it to help with this. @GenericNerd CC for API ref (no change needed on your part).
