### ISSUE TITLE
[BUG] - Maintenance mode doesn't work

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#84]
**Describe the bug**
Enabling maintenance mode in Central still allows login to SC3

**To Reproduce**
1. Turn on maintenance mode
2. attempt login

**Expected behavior**
Display maintenance message

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/230513299-1961df4f-61de-478a-8b6e-c7125822b728.png)

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - Community ID: [e.g. 2/any]
 - Version [e.g. 0.1.0]
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**

**Comment by turbofandude** [comment]
Resolved in 0.6.1 - thank you!
