### ISSUE TITLE
[FEATURE] - Large logos rejected with a "500" message

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#87]
**Describe the bug**
I'm trying to upload a new logo in Central (as we're still having issues with #59 ) however I get a 500 error when I save 

**To Reproduce**
1. Try to upload new logo to Central

**Expected behavior**
Logo is able to be uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/230692704-1020581f-88d3-48f3-98e5-019f430b3efd.png)

**System Information (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - Community ID: [e.g. 2/any]
 - Version [e.g. 0.1.0]
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**
I've tried both these images below
![square1024](https://user-images.githubusercontent.com/67948773/230692645-f78b5dcd-fdda-408d-9f2b-2063e42ddefb.png)
![square1024_white](https://user-images.githubusercontent.com/67948773/230692647-813a0bcc-5761-4926-85d9-5631019706e6.png)

**Comment by jordanhavard** [comment]
**UPDATE**

I tried smaller dimensions 600x600 and that seemed to work well - maybe just some validation messages are needed

**Comment by walkerairtrans** [comment]
@jordanhavard try reducing the size of your image -- I had this same error with a 1000x1000px logo. I dropped it to 100x100px and it went in fine.

**Comment by turbofandude** [comment]
@GenericNerd I believe this is the backend API and/or server settings denying the upload or erroring out along the way. Can you give it a try and see if we can recreate/fix it?

**Comment by turbofandude** [comment]
@GenericNerd can we possibly spit out a more helpful error message on this one? (I.e. "Logo file is too large" instead of a 500?)

**Comment by GenericNerd** [comment]
I have updated the server which *may* fix this issue. @jordanhavard Can you try again and see if the issue still occurs? If it doesn't, that'll be this fix.

**Comment by jordanhavard** [comment]
Still failing @GenericNerd 
![image](https://user-images.githubusercontent.com/67948773/235129220-f20ddb0e-3856-4ead-93d6-798dd1148d44.png)

**Comment by turbofandude** [comment]
I believe we resolved a similar issue that could have caused this. Please re-open if it reoccurs.
