### ISSUE TITLE
[BUG] - Cruise Log entry show 0 altitude now.

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#88]
**Describe the bug**
When hitting cruise it reads 'Cruising at 0 ft'

**To Reproduce**
1. Do a flight
2. Get to cruise phase

**Expected behavior**
Should state Cruising at X feet.

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/230949414-3e2b3c8c-e5d8-4613-80fc-c6c1d838d084.png)

![image](https://user-images.githubusercontent.com/127605985/230949463-ea57963e-142e-411c-bfe2-773fd3da100a.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version Latest
 - Plugins used: Flight Tracking

**Additional context**
N/A

**Comment by turbofandude** [comment]
Found and fixed in 0.6.1
