### ISSUE TITLE
[FEATURE] - Icon for Dark Mode

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#9]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If you're using dark mode toolbars in Windows 11, the icon should change to a version that has a white S and C -- otherwise you can barely make out the icon.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by turbofandude** [comment]
We have added a rounded white background to the icon to resolve this. Thank you!
