### ISSUE TITLE
[BUG] - Can't re-open smartCARS 3 with/without VA Shortcut

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#92]
**Describe the bug**
Every time I close the app and try to re-open I get a blank screen.
Have to fully restart my PC in order to get back into smartCARS 3.

This only happens with the shortcut option for VA.

**Update: this is actually happening now with the default shortcut and the VA shortcut.**

**To Reproduce**
1. Launch SC3
2. Close it
3. Re-launch again

**Expected behavior**
App should launch

**Screenshots**
![image](https://user-images.githubusercontent.com/127605985/232175265-97b7b843-cc68-43b9-91b2-0165811229d9.png)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: [e.g. 2/any]
 - Version: Latest update you just pushed out
 - Plugins used: [e.g. chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center]

**Additional context**
I just got the update for the latest client--installed it and this started.

Log only shows this;

info: No core update required {"source":"main"}
info: Express server running on http://localhost:7172 {"source":"main"}

**Comment by walkerairtrans** [comment]
I waited about 5 minutes and did something else on my PC; and it opened right up. I closed it again, and reopened and got the same grey screen. Seems like something hangs up and then disappears after a certain amount of time? I don't see anything running as processes when I end the app.

**Comment by walkerairtrans** [comment]
![image](https://user-images.githubusercontent.com/127605985/232254083-987c80b4-ed4a-4514-90e3-d7d2e3426089.png)

This is what I'm seeing when it won't open.

**Comment by jordanhavard** [comment]
I'm in the process of implementing the logbook search API and was able to reproduce a white screen similar to the above (and have similar errors) by not returning a response at all from the API and I'm wondering if that's happening here for you. (As when I followed these steps above, I was unable to reproduce the error)

Try unticking `remember me` when logging in and then close and reopen following your steps above and see if this still happens. If it does, potentially might indicate an error with your `Pilot/Resume.php` script.

**Comment by walkerairtrans** [comment]
> I'm in the process of implementing the logbook search API and was able to reproduce a white screen similar to the above (and have similar errors) by not returning a response at all from the API and I'm wondering if that's happening here for you. (As when I followed these steps above, I was unable to reproduce the error)
> 
> Try unticking `remember me` when logging in and then close and reopen following your steps above and see if this still happens. If it does, potentially might indicate an error with your `Pilot/Resume.php` script.

I don't think it has anything to do with API as nothing is being called to my server (packet capture locally.)
I logged out as you said and it still came up blank. It won't return unless I either reboot or wait awhile.

![image](https://user-images.githubusercontent.com/127605985/232261802-8fc37340-6a67-404a-a2b1-3c816c5a528d.png)

**Comment by walkerairtrans** [comment]
I've found that if I close/open it about 5 times it will come back.
This is using the VA shortcut or the smartCARS default shortcut.
It also doesn't matter if I have remember me or not; it seems to hang up loading something from TFDi side first?
Open to suggestions or troubleshooting steps for you all. Just let me know. :)
