### ISSUE TITLE
[BUG] - extra slash `/` being appended to `statistics` endpoint

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#93]
**Describe the bug**
`Statistics endpoint looks to be appending an extra slash. 
Similar to #14 

**To Reproduce**
1. Load smartcars
2. view console

**Expected behavior**
Extra slash isn't appended

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/232181637-11be45ad-7dc3-4ffb-8325-bdb2f2af6692.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: QV
 - Version 0.7.0.1
 - Plugins used: all except simbrief

**Additional context**
Not sure if this is an edge case with QV as I don't append the `/` in our settings. Only happens on this endpoint. All other endpoints work correctly

**Comment by walkerairtrans** [comment]
It appends the same to our site too.

/appdata/api/phpvms5//pilot/statistics

**Comment by GenericNerd** [comment]
This will be resolved in the next version.

Likely culprit (developers only): https://github.com/invernyx/smartcars-3-application/blame/96e531e8bd1ac144aa47d5a6a7cc69d42929ff0d/web/src/pages/profile.jsx#L141
