### ISSUE TITLE
[BUG] - Avatar is colour inverted in dark mode

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#95]
**Describe the bug**
On the first page, the pilots avatar is a strange colour (looks like a filter is applied) - also it out of vertical alignment relative to the pilots name

**To Reproduce**
1. Login in to SC3

**Expected behavior**
Accurately reflect the logo

**Screenshots**
![image](https://user-images.githubusercontent.com/67948773/232181970-e36d16a8-9faa-443c-bb3e-9bf0b5de8e4a.png)

**System Information (please complete the following information):**
 - OS: Win 10 Pro 10.0.19044 Build 19044
 - Community ID: QV
 - Version 0.7.0.1
 - Plugins used: all except simbrief

**Additional context**

**Comment by jordanhavard** [comment]
After checking the code, looks like `invert` is present on the logo

**Comment by GenericNerd** [comment]
@turbofandude What do you think we can do about this? Other than offering a dark theme icon in Central, I don't think we have another fix.

**Comment by turbofandude** [comment]
Found and fixed the invert. Thank you!
