### ISSUE TITLE
[FEATURE] - Scroll to bottom of chat when loaded

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#97]
**Is your feature request related to a problem? Please describe.**
When loading the chat, you have to scroll to the bottom to see the latest messages

**Describe the solution you'd like**
When loading, the view should be already positioned at the bottom

**Describe alternatives you've considered**

**Additional context**

**Comment by JoshRiley** [comment]
Duplicate of #98
