### ISSUE TITLE
[FEATURE] - Chat UX

### ISSUE THREAD

**Issue by jordanhavard** [invernyx/smartcars-3-bugs#98]
**Is your feature request related to a problem? Please describe.**
When submitting a new chat message, or when a new message is received, the view doesn't auto scroll to the bottom

**Describe the solution you'd like**
When ever a new message is received or posted, scroll the view to the bottom.

**Describe alternatives you've considered**

**Additional context**
If the user has manually scrolled up, If a new message is received, don't auto scroll to the bottom as this would be annoying, instead, show a `New messages` similar to how discord does it with an option for the user to click this and have the view auto scroll to the bottom.

**Comment by walkerairtrans** [comment]
I also, notice that if you go to chat from any window it automatically starts at the top. I think it should be starting from the bottom.

**Comment by JoshRiley** [comment]
I was also about to just report this bug too. Thanks for your help in identifying these bugs!

**Comment by turbofandude** [comment]
This was actually implemented at one point and then accidentally broken. I have restored auto-scroll functionality and it now behaves exactly as requested here. It scrolls to the bottom by default upon chat load, then auto-scrolls on new message but if you are at the bottom when it's received.
