### ISSUE TITLE
[FEATURE] - Formatting allowed in "Welcome Message"

### ISSUE THREAD

**Issue by walkerairtrans** [invernyx/smartcars-3-bugs#99]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Can we allow markup to be used in the community message box much like it was in smartCARS 2?

**Describe alternatives you've considered**
N/A

**Additional context**
Here is how my community message appears. It has the old markup from SC2 control panel.

![image](https://user-images.githubusercontent.com/127605985/232229328-1d560578-b045-4f9d-acb3-189265f49f84.png)

**Comment by GenericNerd** [comment]
This is already allowed, but not through markdown. We expect HTML formatting like `<b>Welcome Walker Air Transport Pilots!</b>` to be used instead

**Comment by walkerairtrans** [comment]
> 

It doesn't appear to work my friend.

![image](https://user-images.githubusercontent.com/127605985/232548433-93228b0e-b052-40ea-b4c7-556087113ea9.png)
